=== demDocket.adoc

- - -
_2024-08-16 16:08 plan for worst case_

https://joycevance.substack.com/p/what-if-trump-tries-to-steal-the?utm_source=post-email-title&publication_id=607357&post_id=147452036&utm_campaign=email-post-title&isFreemail=true&r=ndmt1&triedRedirect=true&utm_medium=email[] +

- - -
_2024-08-15 09:53 Dem candidates in all 8 WI congressional districts_

https://www.dailykos.com/stories/2024/8/15/2263245/-Dems-are-running-in-all-8-of-WI-s-Congressional-districts-we-aim-to-flip-some-seats-flip-the-House?pm_campaign=front_page&pm_source=trending&pm_medium=web

- - -
_2024-08-15 09:12 Volunteering options_

https://www.mobilize.us/dailykos/[] +

- - -
_2024-07-05 19:11 pro-Kamala letter_

https://www.democracydocket.com/analysis/will-election-denialism-plague-wisconsin-once-again-officials-set-stage-for-2024/


I am writing to express my deep concerns regarding the upcoming presidential election and the potential risks associated with another Trump presidency and the fascist regime that he and his allies plan to bring to the United States. 

We must deny Donald Trump a second term or lose the Republic. The sole consideration for the Democratic Party in this situation is to run the candidate with the best possible odds in November. A clear-eyed consideration of all the facts will show that Biden is not that candidate. Our nation’s future depends on decisive action at this critical juncture.

If Biden were to retire in honor after one term, he would end up being celebrated as the president that did more for the average American than any President since Franklin Roosevelt.

                    Sincerely,  Keith Hazelton
                                       khazelton@gmail.com
                                       3006 Pelham Rd
                                       Madison, WI. 53713