=== f2fDenvSept24.adoc
#sjz-20240910-teammtg

- - -
_2024-08-14 13:07 prep for trip_

===== Steve Zoppi: #sjz-20240910-teammtg Preliminary Agenda:

===== Arrivals on Tuesday the 10th / Dinner with whomever is available.

===== Morning / Early Afternoon on Wednesday the 11th: 
* Supplier of Services & Agencies Review (Leveling everyone's understanding of our available resources) in preparation for 2025 Renewals.

===== Later Afternoon on Wednesday the 11th: 
* requirements for Self-Service Attributes System and +
* possible excision of Enrollment Flow / Identifier Creation from COmanage to the this prospective new system.

===== Morning / Early Afternoon on Thursday the 12th
* Continuing Requirements definition

===== Later Afternoon on Thursday the 12th
* Sorting out next steps (What follow-up needs to be done, in what order, with whom).

===== Friday / "The Return Home" for Denver occupants.

- - -
Bill Kaufman +
For supplier services and specifically for Work Segment Approvals we should tighten our process for Who is Copied on the WSAs, and Who should help confirm invoices.  In some case Work Reports are submitted prior to invoices and those also need to be approved.  This is still a little Ad Hoc and can be improved to help the vendors and Accounting

Keith Hazelton +
Virtual is the only real option for me. My son's wedding is in Buffalo NY and we're driving home Monday and Tuesday, Sept. 9 and 10. Back in Madison Tuesday late afternoon or evening.  I can be available by phone  and internet hot-spot. Ana says she's willing to drive.  Not ideal but I'll do the best job I can.

Message #sjz-20240910-teammtg








