=== futures2.adoc

- - -
_2024-08-02 13:56 _

https://docs.google.com/document/d/1nyC85JNcWS1hsnYAPPR3xJIuzUHPZZX3xELXF8tUZWM/edit?pli=1[] <- !! Q2 2024 Futures Quarterly Report 

- - -
_2024-01-10 15:23 Futures2 Draft Review_

Invitation to Provide Feedback on InCommon Futures2 Strategy Report

Ann West
​cacti@internet2.edu;​tac@incommon.org;​CTAB <ctab@incommon.org>;​Nick Lewis;​scott.weyandt@morantechnology.com;​Rob Carter <robert.carter@duke.edu>;​​​​​​​​​​​​steering@incommon.org;​Kevin Morooney;​
Steven Zoppi​
Tue 2024-01-09 2:24 PM

Dear Colleagues,

InCommon Advisory Group members have unique local, national, and (in some cases) global perspectives and expertise, and we appreciate the time and attention that you, the community’s volunteers, and developers, contribute to the collective.

InCommon’s Leadership invites you to comment on the attached final DRAFT of the InCommon Futures2 Strategy Report by end of day (Alaska Time) on Thursday January 11, 2024.

Please treat this document as confidential given it is still in draft. We will circulate it widely once it is finalized.

How to Provide Feedback

Written Comments (Preferred)

We prefer receiving your comments in writing to ensure they are captured accurately. Please add your thoughts by the end of the day Thursday. 

    Access the Advisory Committee Review gdoc.
    https://docs.google.com/document/d/1qrkkmIpbVCmR9nEukEqQx_ByX2wU-AJyg6CILcLl5y0/edit?usp=sharing[]

    Sign the registry at the bottom of this document along with specific initials you will be using to denote your comments. 

    Add your ideas/suggestions under the appropriate section heading below.

Verbal Comments

    Join the Open Office Hours on Friday 11:00 am ET

    Zoom Coordinates: https://internet2.zoom.us/j/82446165750?pwd=DbjQcWGwFKbSg3WdFvfrZFTHJ576bi.1

        Meeting ID: 824 4616 5750 Passcode: 935161

Have other questions? Please email 
Ann at awest@internet2.edu, 
Romy at rbolton@internet2.edu and 
Apryl at amotley@internet2.edu. 

We look forward to hearing from you.

Best, Ann

Ann West AVP, Trust and Identity, Internet2; ED, InCommon
W: 720-379-9666
Email: awest@internet2.edu
