=== project2025.adoc

- - -
_2024-06-17 16:18 countering project 2025_

https://huffman.house.gov/media-center/press-releases/congressional-leaders-form-task-force-to-counter-project-2025-and-defend-democracy[] +

Rep. Huffman. “Through this Task Force, leaders across the ideological spectrum and experts in every policy area that’s under attack are uniting to protect democracy as we know it. Donald Trump and those behind Project 2025 are ready to turn America into a theocratic regime if they get the chance – and we are going to be ready to stop them.” 

Members of the Task Force represent the diversity of the Democratic Caucus and are leaders on many of the issues currently under attack by Project 2025. 

Founding members joining Rep. Huffman are 
Democratic Caucus Vice Chair Ted Lieu (CA-36), 
Chair of the Congressional Hispanic Caucus Nanette Barragán (CA-44), 
Congressional Asian Pacific American Caucus Chair Judy Chu (CA-28), 
!! Equality Caucus and Labor Caucus Chair Mark Pocan (WI-02), 
Pro-Choice Caucus Co-Chair Diana DeGette (CO-01), 
Co-Chair of the Congressional Freethought Caucus and Ranking Member of Oversight Jamie Raskin (MD-08), and Progressive Caucus Chair Pramila Jayapal (WA-07),
Rep, Massachusetts’s 7th cong dist, Ayanna Pressley

https://www.democracynow.org/2024/6/24/project_2025_ayanna_pressley[]

https://democracyforward.org/updates/democracy-forward-responds-to-supreme-court-ruling-in-trump-v-united-states/[] +
https://democracyforward.org/wp-content/uploads/2024/06/2024-05_Peoples-Guide-Pro-2025.pdf[] +

https://www.monitoringinfluence.org/project-2025/[] <- a project of Accountable.US +
https://en.wikipedia.org/wiki/Project_2025[] +


- - -
_2024-06-17 16:49 snippets_

"The fourth pillar of Project 2025 is our 180-day Transition Playbook and includes a comprehensive, concrete transition plan for each federal agency.  Only through the implementation of specific action plans at each agency will the next conservative presidential Administration be successful. 

Pillar IV will provide the next President a roadmap for doing just that.  To learn more about Project 2025’s vision for a conservative administration, please read our recently published book, Mandate for Leadership: The Conservative Promise."



- - -
_2024-06-17 16:16 references and links_

https://www.dailykos.com/stories/2024/8/3/2260219/-The-man-behind-Project-2025-s-most-radical-plans?pm_campaign=front_page&pm_source=top_news_slot_1&pm_medium=web[] +
https://www.project2025.org/[] +
2025_MandateForLeadership_FULL +




