=== voteSuppression.adoc
- - -
_2024-08-19 17:48 election fuckery_

https://www.dailykos.com/stories/2024/7/31/2259579/-Okay-The-70-Names-from-American-doom-com-Currently-being-updated-slipperypeople[] 

So I located the list of 70 election officials who are lined up to put us in Insurrection 2.0.

The owner of the site put it behind a pay window, but I loaded it anyway,

Many editions of American Doom are free but the rest of this story and a complete list of all 70 election denial officials is behind a paywall because it’s the result of two and a half years of investigation. You can support our efforts to expose election deniers, hold right-wing extremists accountable and track other threats to democracy for as little as $5 a month. To show what we’ve been up to, here are some links crucial to understanding American Doom’s work — and why it’s worth your hard-earned money. LINK to site

Cue  The Talking Heads…. Slippery People 

So on to the list: 

I have researched (googled) the first Three names and I was provided with voluminous information on all three fascists. I am sharing the most useful links and I will update as I find more. I just thought it was important to put this out there. This is not Doxing nor is it an invasion of privacy. There is plenty to dig into. If anyone wants to help fill in, then please post links below,

This may well be a red herring, but we know it probably isn’t. The cure is to win by a landslide, but barring that. These fraudsters MUST be exposed. 

70 Fascists, 
 

*Arizona*

Bob Bartelsmeyer 

https://apnews.com/article/cochise-county-elections-director-resigns-election-lies-c8f9baf03984e8f132bc5404bd21270f

David W. Stevens

https://www.votebeat.org/arizona/2023/2/7/23589804/cochise-county-elections-recorder-david-stevens-hand-count/

Peggy Judd

https://www.myheraldreview.com/news/cochise_county/judd-seeks-to-step-down-as-county-board-chair-but-will-retain-her-seat/article_9b788650-b7c2-11ee-bb28-f32c14a5c260.html

Tom Crosby 

Ron Gould 

Steve Christy 

Steve Christensen

Kevin Cavanaugh

Hildy Angius 

*Georgia*

Drew Chestnutt

Ben Johnson

Roy McClain 

Kim Slaughter 

Larry Brown

Larry Ewing

Jeff Hughes

Jack Noa

Dr. Tom Smiley

Alice O'Lenick

Bridget Thorne

Julie Adams

Michael Heekin 

Joel Natt

Pam Peters

Gary Stamper

Anthony Lewis 

Nancy Jester 

Debbie Fisher 

John Wallace 

Larry Hand  

Jeffrey Vance

David Hancock 

*Michigan* 

Ann Weiler

Anne Hill

Bonnie Kellogg

Stephanie Scott

Minde Lux

Bonnie Hakkola

LeeAnn Oman 

*Nevada*

Leo Blundo

Jeanne Herman 

Michael Clark 

Danny Tarkanian

Walt Nowosad

North Carolina

John Adams

George C. Hague

Byron Waters 

Anthony Iovino 

Elizabeth McDowell 

Mary Summa 

Tim DeHaan 

Jerry Forestieri 

*Pennsylvania*

Leslie Osche

Kimberly Geyer

Randy Bunch

Michael S. Rivera

Christian Y. Leinbach

Harry Haas

Alyssa Fusaro

Ray D’Agostino

Charlie Bayle

Nick Sherman

Tim Winters

Todd Graybill 

Chris Chermak 

Rick Wilbur 

Doug McLinko 

Samuel Demarco III 

Scott Hough

Josh Parsons


- - -
_2021-06-03 20:53 orgs fighting voter suppression_

https://movement.vote/funds/wifund/
 <= +
https://www.democracydocket.com/
 <= Mark Elias aligned voting rights group +

- - -
_2020-08-21 11:04 election day countdown_

https://www.timeanddate.com/countdown/election?p0=263&iso=20201103T00&msg=2020%20US%20Presidential%20Election

- - -
_2019-12-14 16:31 references and links_

https://elections.wi.gov/node/6587 +
https://elections.wi.gov/ +
https://elections.wi.gov/public-records +
https://www.jsonline.com/story/news/politics/2019/12/13/judge-orders-wisconsin-purge-more-than-200-000-voters-list/4412776002/ +
https://www.jsonline.com/story/news/politics/elections/2019/11/18/what-know-lawsuit-over-wisconsins-voter-rolls/4202822002/ +
https://www.jsonline.com/story/news/local/wisconsin/2017/03/14/wisconsin-setting-stage-remove-hundreds-thousands-names-voting-rolls/99168190/
https://www.washingtonpost.com/politics/2019/12/14/judge-ordered-up-people-be-tossed-registered-voter-list-swing-state/

https://badgervoters.wi.gov/ +
Statewide List (Wisconsin does not track party affiliations) 2018 general election

Note: If you changed criteria for your search, click the 'Get Estimate' button to refresh data +
Total Count : 6,311,834 +
Total Cost : $12,500.00 +

- - -

They also have the option of fixing their voter registration status before Election Day, either online or in their clerk's office.

People can register online at myvote.wi.gov.

The letters went to about 7% of the state's 3.3 million registered voters.

The largest number of letters were sent to voters in the state's two largest cities, Milwaukee and Madison, which are also the state's Democratic strongholds. About 35,000 voters in Milwaukee and about 18,000 in Madison were sent the letters.

The next largest groups of voters were in Eau Claire, Green Bay and La Crosse. About 4,000 voters were sent letters in each of those cities, according to the Elections Commission.

In New Berlin, a reliably Republican city, about 1,400 voters were sent letters. A similar number of letters were sent to voters in Menomonee Falls, another bastion for Republicans.
