=== Россия.adoc
- - -
_2024-09-11 21:32 "From Russia With Lev"_

Television premiere!

Rachel Maddow's new documentary "From Russia With Lev" will have its television debut on MSNBC two Fridays from now, 

September 20th at 9pm ET.

- - -
_2024-08-25 10:40 news sources_

https://vatniksoup.com[] <- #vatniksoup is a Twitter thread series (and a hashtag!) where I’ll introduce pro-Russian actors and propagandists from around the world +
https://kremlingram.org[] investigating twitter ties to Russia, [English version] [Українська версія] +



- - -
_2024-03-20 18:52 Duntsova dawn party_

https://boosty.to/e.duntsova[] +

- - -
_2024-03-15 18:34 offense vs defense in Russian IT_

https://dossier.center/sorm/[] <- Eyes of the Kremlin How the digital gulag is organized in Russia and what prevents it from earning in full force +
https://dossier.center/sorm/[] initisl view Russian w translate button +

- - -
_2024-02-20 13:34 4-part german doc'tary on rot in RU army_

https://presseportal.zdf.de/pressemappe/putins-krieger[] +

streaming anywhere?


- - -
_2024-01-17 21:15 riots in russia_

https://www.youtube.com/watch?v=ehqlcC_O32U&t=279s[] <- Bashkortostan +
- - -
_2024-01-16 13:17 https://freemoscow.university/_

Онлайн. Бесплатно. Прямой контакт с преподавателем
Online. Free. Direct contact with professors

- - -
_2023-12-15 14:49 guns & butter_

https://plgnmedia.appspot.com/putin-stal-glavnym-faktorom/[] +
https://medium.com/@nadinbrzezinski/end-of-the-year-russian-economy-guns-and-butter-dcf157104022[] +

- - -
_2023-12-07 13:54 Ukraine_

https://www.ifw-kiel.de/publications/news/ukraine-support-tracker-new-aid-drops-to-lowest-level-since-january-2022/[]


- - -
_2023-12-04 16:13 bring them home_

On December 14, Putin will have a direct line, and this is our chance to finally find out when he will return to us our men, whom he took into lifelong slavery 15 months ago? Let's show our president, who prefers not to notice our grief, how many of us there are?

Not all civil society has been burned to the ground yet!

Пример видео в посте. Присылайте видео сюда: https://t.me/put_domoj

- - -
_2023-11-23 10:54 opposition candidate for RF presiden_

https://duntsova2024.ru/[] <- Екатерина Дунцова, юрист и журналист, кандидат в президенты России 

- - -
_2023-11-12 12:12 Khodorkovsky's Dossier Center_

https://dossier.center/[]

- - -
_2023-10-24 20:52 Tolstoy on Russo-Japanese war_

"Again war. Again sufferings, necessary to nobody, utterly uncalled for; again fraud; again the universal stupefaction and brutalization of men."

Lev Tolstoy, ОДУМАЙТЕСЬ! "Bethink Yourselves", 1904

Posted on Telegram by колокол xxi (Bell 21) 
https://tlgrm.ru/channels/@Kolokol_21/5350

file:///Users/kh/My%20Drive/pdf/The%20Project%20Gutenberg%20eBook%20of%20%E2%80%9CBethink%20Yourselves!%E2%80%9D,%20by%20Leo%20Tolstoi.html[] 

- - -
_2023-09-29 18:39 Andrei Soldatov_

_The New Nobility: The Restoration of the Russian Security State_, Andrei Soldatov 
https://agentura.ru/en/[] <- Andrei Soldatov 

- - -
_2023-06-24 12:05:05 prigozhin rebellion_

https://twitter.com/ChakhoyanAndrew/status/1681736868386177024[] +
nevzerov youtube.com +
https://www.youtube.com/watch?v=jKYi_KximCw +


- - -
_2023-06-13 11:09:48 background of 100 occupation officials_

https://www.proekt.media/guide/kto-rukovodit-okkupirovannymi-territoriyami-ukrainy/ +
 
- - -
_2023-05-14 10:56:29 Guardian's Pomerantsev_

https://www.theguardian.com/commentisfree/2023/may/14/what-happens-when-leaders-disregard-truth-putin-trump-about-to-find-out +

- - -
_2023-05-12 21:13:15 Kiselyov and Abbas Galyamov_

https://www.youtube.com/watch?v=jBb7af7I4xw 
- - -
_2023-05-11 19:14:57 ukr scribble map_

https://www.scribblemaps.com/maps/view/The-War-in-Ukraine/091194 +
https://twitter.com/emilkastehelmi/status/1656768748823379971 +

- - -
_2023-05-10 11:54:31 chat gpt 4 on siloviki_

"members of the russian siloviki"

The term "siloviki" refers to a group of high-ranking officials in Russia who have a background in security or military services. The members of the Russian siloviki are individuals who have served in law enforcement agencies, military, and intelligence services. Some of the well-known members of the Russian siloviki include:
  Vladimir Putin - President of Russia and a former KGB officer.  Dmitry Medvedev - Former President of Russia and a lawyer by profession.  Nikolai Patrushev - Secretary of the Security Council and a former KGB officer.  Sergei Ivanov - Former Deputy Prime Minister and a former KGB officer.  Igor Sechin - CEO of Rosneft, the state-owned oil company, and a former KGB officer.  Alexander Bortnikov - Director of the Federal Security Service (FSB) and a former KGB officer.  Viktor Ivanov - Head of the Federal Drug Control Service and a former KGB officer.  Sergei Naryshkin - Director of the Foreign Intelligence Service (SVR) and a former KGB officer.

It should be noted that not all high-ranking officials in Russia with a security or military background are considered part of the siloviki group, as the term is typically used to refer to a specific subset of individuals with close ties to Putin and a shared worldview on national security and foreign policy.

- - -
_2023-04-26 19:09:45 navalny movie_

https://www.youtube.com/watch?v=vps43rXgaZc 

- - -
_2023-04-05 12:02:19 telegram channels of interest_DefMon3DanspiunsmooreBofB1940AC_NavalHistoryArmouredCarrierDrachinifelMilAvHistoryMilHiVisualized/TheBaseLegCBI_PTO_HistoryDrydockDreamsWarintheFutureJack_WatlingMarkHertlingChrisO_wikiChuckPfarrernicholadrummondNavyLookout

- - -
_2023-03-31 12:50:28 vulcan files_

https://www.theguardian.com/technology/2023/mar/30/vulkan-files-leak-reveals-putins-global-and-domestic-cyberwarfare-tactics +

- - -
_2023-03-12 13:06:21 Maria Pecvchikh, Navalny investogator_

https://www.newyorker.com/podcast/political-scene/the-russian-activist-maria-pevchikh-on-the-fate-of-alexey-navalny + +x
https://podcasts.apple.com/podcast/id268213039?pdst_key=df1e65c3eb684bbabcda953605e811ee&pdst_group=83a946fcfb264355b29c24a0dd34adf2&pdst_label=bj0vajYd&app=podcast&at=1000lPBj&ls=1&mt=2

- - -
_2023-03-12 12:50:36 Abbas Galyamov, Polygon_

https://poligonmedia.io/v-rossii-lyubov-k-vlasti-smenitsya-na-nenavist/ +

- - -
_2023-01-03 14:42:02 Khodorkovsky_

https://www.facebook.com/MBK313373 +
https://www.theneweuropean.co.uk/putins-public-enemy-no-1/

- - -
_2022-12-30 20:10:48 RU milbloggers_

The year is coming to an end and we want to thank our colleagues for getting through it together. This is not a promotional post. This is part of the channels that we read and can safely recommend to you. We apologize in advance if we forgot to mention anyone.

ASTRA - independent journalism and honest news
Political circus - on the topic of the day, informative and sarcastic
Nightingale droppings - one of the main enemies of Russian propaganda
NEVZOROV - needs no introduction, like Lidia Nevzorova
Be Or - always informative, high-quality event analytics
The city of Glupov - intellectually and with humor firmly stands on the side of good and truth
Maxim Mirovich is a man who brings the collapse of Putinism closer
Cotton swamp - be careful, there are everyday hordes, short and to the point
Liberty people - about the country of slaves, about the country of masters
Ateo Breaking - news without admixture of propaganda
Yoshkin mole - digs for the benefit of our common victory, digs excellent, I must say

- - -
_2024-02-02 19:58 Nadezhdin by Gallyamov_

https://pointmedia.io/story/65bcd62b6bf847f7ecb75c25[]

- - -
_2022-11-20 18:14 How to kill the dragon_

https://dragonbook.khodorkovsky.com/[] <- RU & EN +
https://soundcloud.com/m_khodorkovsky/sets/kak-ubit-drakona[] <- audiobook +
https://www.youtube.com/watch?v=bi7H-EHw3dE[] +

https://telegra.ph/Kak-ubit-Drakona-i-sohranit-demokratiyu-Razbor-tezisov-Hodorkovskogo-i-novye-idei-o-stroitelstve-postputinskoj-Rossii-11-22[] <- How Kill Dragon Follow-on By Академик РАН Юрий Пивоваров +
https://biblioclub.ru/index.php?page=author_red&id=50551[] <- about Пивоваров Юрий Сергеевич +

- - -
_2022-09-26 10:32 https://t.me/veraafanasyeva recommended telegram channels_

PESKOV'S MUSCLE
http://t.me/Sandymustache
is the main one in unbending braces, insulting the feelings of jingoistic patriots, anti-state irony and the most important news seasoned with bright sarcasm. 🧐

Double Yat
http://t.me/otsuka_bld

writes news in such a way that propagandists feel embarrassed, officials feel pain, Putin is ashamed, and readers have fun. Subscribe to the most witty political and humorous channel on Telegram - otsuka_bld 👩🏻‍💻 Catharsis is the production of meanings. Complex things in simple terms.

👤 Being Or
http://t.me/ToBeOr_Official

is the official channel of Being Or in Telegram. Join. 🤳 In the feeds of governors, mayors, senators and deputies, the channel is SOMETHING LIKE THIS - one channel instead of many will give all the events of the special operation era with meanings that are invisible behind the news lines. About what is hidden behind the headlines and what awaits us in the end. ⭕️vechernii_m +

- - -
_2022-09-19 18:12 existential crisis_

https://medium.com/nadinbrzezinski/russia-will-face-an-existential-crisis-8106c640f50c[] <- +

- - -
_2022-09-14 11:32 documentary on war in Ukraine_

https://www.youtube.com/watch?v=-SGujErc4qo +

- - -
_2022-09-12 17:03 wartranslated_

https://wartranslated.com/[] <-!! +

- - -
_2022-09-12 10:34 green ribbon resistance mvmt_

https://golos-protiv.com/ +

- - -
_2022-09-09 21:08 youtube series, gen. hodges & gary kasperov_

https://www.youtube.com/watch?v=Kaj3ltHeEik

- - -
_2022-08-28 20:55 Bell XXI on Telegram_

Агенты Кремля
August 21, 2022
. Раньше всех. Ну почти. ПУЛ N3
3. Банкста
4. НЕЗЫГАРЬ
5. Выпускайте Кракена!
6. Старше Эдды
7. ПОЛИТУПРАВА
8. Образ будущего9. Темник0. Главный политический1. Навстречу Трансферу2. Мясорубка3. 16 негритят4. БОЛЬШОЙ ТРАНСФЕР 20245. КАК-ТО ВОТ ТАК6. Кремлевский мамковед7. Доктор прописал8. Движение Сорок Сороков9. Мадам Секретарь0. Свои да Наши
1. ГлавМедиа2. BRIEF3. Финансовый Караульный4. ИнформБюро-ЮФО5. Выборный6. СОЛОВЬЁВ7. 17038. Мария Захарова9. Дмитрий Медведев
30. Вячеслав Володин
31. Поддубный
32. Kadyrov_95
33. Кровавая барыня
34. Маргарита Симоньян
35. Реальный Губер
36. Сергей Минаев
37. РОГОЗИН
38. ГАСПАРЯН
39. Kotsnews
40. Президент Гордон
41. Мария Шукшина
42. Неофициальный Безсонов
43. Стрелец-Молодец
44. Фридрих
45. КОРНИЛОВ
46. Павел Островский
47. АНТОН ВЯЧЕСЛАВОВИЧ
48. КЛИШАС
49. Антискрепа
50. Осташко! Важное
51. ШАФРАН
52. Кристина Потупчик
53. DELYAGIN's special
54. РИТА ЭБЗЕЕВА
55. Александр Хинштейн
56. Тина Канделаки
57. popovrtr
58. ПАРФЕНТЬЕВ.КЛУБ
59. Мария Бутина
60. Лобушкин
61. The Гращенков
62. Анастасия Кашеварова
63. Дмитрий Свиридов
64. Роман Бабаян
65. Марина Юденич
66. ДОКТОР СОСНОВСКИЙ
67. Media Малькевич
68. ДЕПУТАТ ЕНГАЛЫЧЕВА
69. Abbas Djuma
70. Максим Кононенко
71. КАРНАУХОВ
72. ДУМАем
73. Эдвард Чесноков
74. Екатерина Мизулина
75. МАРТЫНОВ
76. War Gonzo
77. Barnaul Live
78. ОСТОРОЖНО, Москва
79. Запорожский вестник
80. Battle Z Sailor
81. ТОПОР 18+
82. ТОПОР
83. ТОПОР Live
84. Москва сейчас
85. Как дела, Санкт-Петербург?
86. Ростов N1
87. Крымский
88. Нетипичная Адыгея
89. Сочи Онлайн90. Екатеринбург N191. Мой Нижний Новгород92. Спросите у Расула93. Белгород N194. ВЧК-ОГПУ95. REDACTED R6 (Котёл #6)96. Бахчисарайские гвоздики97. Крылья войны98 РИА Новости99. Осторожно, новости00. ФедералПресс01. RT на русском02. Sports03. Mash04. SHOT05. СИГНАЛ06. КЛИРИК07. Журнал Авто.ру08. ВОРОБЬЕВ09. Карточный Домик: Россия
10. 🇷🇺 Борода вещает Z
11. Постовой
12. Карточный Домик: Европа
13. 360tv
14. Выборный
15. Медиасолдат
16. Кремлёвская прачка
17. БОЛЬШОЙ ТРАНСФЕР 2024
18. Саваничи 🇷🇺
19. Люди и Zвери20. Диванный аналитик21. Военный Осведомитель22. Димитриев23. Венедиктов24. МЕРКУРИ25. КАДЫРОВ26. READOVKA27. Оперативные сводки28. Операция Z: Военкоры Русской Весны29. НЕБОЖЕНА30. Война с фейками31. Sputnik Ближнее зарубежье32. Мюсли Лаврова33. Vоенкор Котенок Z34. Комсомольская правда: KP.RU35. Минобороны России36. Андрей Медведев37. ВОЙНА [ Россия Украина Израиль ]38. Александр Ходаковский39. Объясняет Readovka40. МИГ41. РаZVожаев42. Крючков Z43. Aladdinhabar44. China army45. Daily War46. Fighterbomber47. Greek Military Portal48. MilitaryMaps49. Open China50. PLATONOVA51. Sputnik Афганистан52. The Peacemaker53. UKR_LEAKS54. WARCATS55. Warjournal56. Агрегатор Правды57. Александр Коц58. Анна-Ньюс59. Байки из фавел60. Балканская сплетница61. БелВПО62. Великая Война63. Владимир Карасёв64. Владлен Татарский65. Восточный Синдром66. Голос Мордора67. Дневник иранского журналиста68. Донбасс решает69. Донецк70. Евгений Поддубный71. Заметки фотокорреспондента72. ИА Реалист73. ИнформБюро-ЮФО74. Катехизис Катарсиса78. Лик Войны79. Мадуро - не дура80. Мьянма Myanmar81. Оперативная линия82. Первый Морской83. Повестка дня Турции84. Поисковик ЗВИ85. Проснувшийся дракон86. Радио Sputnik87. РАСПП88. Русский ориенталист89. Рыбарь90. Секс, картели, Фрида Кало91. СИЛОВИКИ92. С «ЛЕЙКОЙ» И С БЛОКНОТОМ93. Zvezdanews94. Украина.ру
 195. Форпост
 196. ЧВК Медиа97. РИА ФАН98. Друид99. Кремлёвский безБашенник00. Андрей Гусий01. Zommerman02. Zаписки авантюриста03.Империя Очень Зла04.Александр Субботин05. Ыыху06. Пакет с пакетами07. Радио Стыдоба08. Во///дь09. lastoppo
10. Бочарик
11. Открытая Украина
12. Караульный Z
13. РОКОТ
14. Украина.ру
15. Кибер Фронт Z
16. Арбалет Говорит
17. Придыбайло
18. Рука Кремля
19. Zergulio20. Русский Демиург21. Лука Ебков22. Антинавальный23. ИноСМИ24. Коза Кричала24. Кот Костян25. Колесо Генотьбы —26. Полина Усенко27. follyflly28. Мойша Шекель29. Тротуары и Олени30. SALOBOY31. Аркаша32. Графиня33. Илья Муромцев34. Брежнев35. Гардемарин36. Хрюн Моржов37. Это правда?38. Эхо Хайфы39. Моменталист40. Выключаем эмоции41. Радио 1000 хохлов42. Юмор и политика43. Что там у Дагестанцев?44. Бумажная Zмея45. Мина Z46. ANSHLAK47. Вячеслав Бриг48. Харисов о политике49. Заметки на полях50. Кукушка51. 11252. Российская Газета | Новости53. КБ54. URA.RU55. Сolonelcassad56. ДВАЧ57. КСТАТИ58. Поздняков
Список будет пополняться...

- - -
_2022-08-19 17:35 General SVR_

General SVR

Dear subscribers and guests of the channel!
 We ask you to be careful about the information that is allegedly presented on social networks on our behalf.  The Russian government continues to fight against us in every possible way.  Earlier, regarding our channel, Roskomnadzor received the Demand of the Deputy Prosecutor General of the Russian Federation dated No.  27-31-2021/ ИД1672-21 order and public safety.  Roskomnadzor demanded that the Telegram messenger remove our channel, but Telegram refused to comply with the demand of the Russian authorities, after which Roskomnadzor went to court and fined Telegram four million rubles for failure to comply with the requirement, but Telegram refused to comply with the requirement to remove our channel, paying a fine.
We are the only opposition channel against which the Russian government is fighting so fiercely.  Not being able to remove our channel, the Russian authorities launched a program through troll factories to discredit our channel and organize attempts to level our information in social networks and groups.  They have created many telegram channels with similar names to our channel, but which have nothing to do with us, and information from fake channels is spread on social networks allegedly on our behalf.
 In addition to this, we have a backup channel in Telegram, to which we regularly provide links and an English-language channel with the translation of our texts, ALL OTHER CHANNELS SPEAKING ON OUR BEHALF ARE FAKE.
 We remind you that we give exclusive insider information, which is ultimately confirmed by official sources.  We were the first to publish the details of the poisoning of Alexei Navalny, which were confirmed first by the Western media, and then by a group of investigators.  We were the first to report in detail about the "Clean Field" plan, developed under the leadership of Security Council Secretary Nikolai Patrushev as early as the year before last, to destroy non-systemic opposition, free press and all types of dissent in Russia, which was implemented within a year and a half and everyone could watch it  implementation.  We were the first to report on preparations for a war with Ukraine before Western intelligence agencies, and despite several postponements of the start date, we not only named the dates, but also described the plan for the start of the military operation.  We were the first, a week before everyone else, to report that the head of the Central Bank, Elvira Nabbiulina, resigned after the outbreak of hostilities.  We were the first to report back at the end of last year, and in February of this year we confirmed the information about the plans for the nationalization of Lukoil, which started in the spring.  We were the first to report on the participation of the Taliban at the St. Petersburg International Economic Forum, and we were right.  And this is only a small part of our information confirmed over time.  We talk about the plans of the Russian leadership and quite often these plans can be thwarted, including due to the fact that they are made public.  We inform about the state of health of Russian President Vladimir Putin and almost all the diagnoses that we made public were confirmed by both investigators and Western intelligence, acting as sources of information for major publications.  We really influence events and correct their course.  Subscribe to our trusted resources and beware of fakes.  Thank you for understanding and support!022-08-16 15:03
https://www.4freerussia.org/how-the-war-in-ukraine-provoked-a-re-awakening-of-national-identity-among-russias-indigenous-peoples/

- - -
_2022-07-28 16:33 maps_

https://soar.earth/maps/12096?pos=46.77925213345954%2C33.031534652372144%2C9

- - -
_2022-07-17 15:43 Ukr Prez press releases_

https://www.president.gov.ua/documents/all

- - -
_2022-07-02 11:51 ukr updates_

https://twitter.com/C_M_Dougherty/status/1554507629367541762[] <- ! 23-tweet thread: Where does the Ukraine war go from here? +
https://wartranslated.com/[] <- ! +
https://twitter.com/i/events/1483255084750282753?s=20[] <- Latest updates on the war in Ukraine +

- - -
_2022-05-16 20:23 ukrainian news source_

https://www.ukrinform.net/[] <- eng / ukr / ... +

- - -
_2022-05-16 19:21 source to evaluate_

https://nvo.ng.ru/

- - -
_2022-05-12 10:20 wwii is all Russia has left_

https://www.theatlantic.com/ideas/archive/2022/05/putin-speech-ukraine-invasion-soviet-union/629825/?utm_content=edit-promo&utm_medium=social&utm_term=2022-05-11T14%3A30%3A30&utm_source=twitter&utm_campaign=the-atlantic[] <- +

- - -
_2022-05-11 20:12 a to z on Russia's military command structures_

https://www.understandingwar.org/backgrounder/russian-general-officer-guide-may-11

- - -
_2022-04-10 21:07 livemap of Ukraine with running updates on the course of the war_

https://liveuamap.com/[] <- +
- - -
_2022-04-04 13:13 russian soldiers in Bucha_

https://docs.google.com/document/d/1byIKYL4eYbqfo6MSwYJwVlfwSnpee1QeMzwvqfqShS0/edit?usp=sharing[] <- form letter to congr reps advocating delivery of specific weapon systems to Ukraine +

Военныепреступникинепосредственно участвующие в совершении военных преступлений против народа Украины в г. Буча – военнослужащие 64 о.pdf

https://gur.gov.ua/content/voennye-prestupnyky-neposredstvenno-uchastvuiushchye-v-sovershenyy-voennykh-prestuplenyi-protyv-naroda-ukrayny-v-h-bucha-voennosluzhashchye-64-otdelnoi-motostrelkovoi-bryhady-35-oa-vvo.html[] <- War criminals directly involved in committing war crimes against the people of Ukraine in Bucha - servicemen of 64 separate motorized rifle brigades 35 OA VVO +

- - -
_2022-03-28 18:44 Zelensky's Economist interview_

https://twitter.com/sumlenny/status/1508568117890457605

- - -
_2022-03-19 10:09 learn russian conversation YouTube_

https://www.youtube.com/channel/UC80GTcFtmWwHylm0fhmyLEw[] <- Learn the Russian Language +

Want to speak Russian so well that you get mistaken for a native speaker? Follow my 30 Day Conversational Russian Challenge here:
https://learntherussianlanguage.com/conversational-russian/[] <- +

Today 5 series that helped me a lot when I just started learning Russian.

Channel of StarMediaEN: https://www.youtube.com/channel/UCuSx...
Documentaries: https://www.youtube.com/channel/UCuSx...
The Dawns here are quiet: https://www.youtube.com/watch?v=9v8v1...
Cardsharp: https://www.youtube.com/watch?v=mmbiu...
Trouble in Store: https://www.youtube.com/watch?v=1NKfG...
Как я стал русским: https://www.youtube.com/watch?v=CtDBJ...

Read the accompanying post here: https://learntherussianlanguage.com/t...

- - -
_2022-03-10 20:46 kara-murza H.R. 806 delegitimation of Putin 2024_

https://www.washingtonpost.com/opinions/2021/11/24/congressional-proposal-reveals-kremlins-achilles-heel/[] <- Kara-Murza's WashPost editorial +
https://www.congress.gov/bill/117th-congress/house-resolution/806/text[] <- H.R. 806 delegitimation of Putin 2024 two-page draft referred to the House Foreign Affairs Committee, Rep. Steve Cohen (D-Tenn.) and Rep. Joe Wilson (R-S.C.) +

- - -
_2022-03-15 08:13 Navalny / War in Ukraine_9 days ago, Putin officially decided to kill innocent people. 9 days ago, our country began to be considered an absolute evil.

Bombs and rockets fall on Ukrainian cities. Russians can no longer buy many brands and read independent media.

Everyone knows that every day the situation will get worse. Putin is closing Russia with an iron curtain - away from free internet, safe world and justice. We will tell you about all the events of the day in our live broadcast.

Come out to rallies against the war! On a weekday at 19:00 and this Sunday, March 6, at 14:00.

Moscow - Manezhnaya Square
Petersburg - Nevsky Prospekt near Gostiny Dvor
Novosibirsk - the square near the opera house
Yekaterinburg - Labor Square
Other cities of Russia and the world - in the central squares.

Send us photos and videos from rallies in your city: https://t.me/protestlivebot

Our social networks:
Telegram: https://t.me/teamnavalny
Instagram: https://instagram.com/teamnavalny
Facebook: https://fb.com/teamnavalny
Twitter: https://twitter.com/teamnavalny

- - -
_2022-02-24 14:45 stream capture and transcription_

` cue up the stream to be recorded +
` start a quicktime recording
` start the stream
` stop recording when done
` save .m4a (goes to iCloud/"QuickTime Player")
` log to AWS as IAM user koop, 059602349466
` goto https://s3.console.aws.amazon.com/s3/home?region=us-east-2`
` upload .m4a to S3 bucket s3://blog.aktis.org/audio/karinOlrlova.m4a
` goto https://us-east-2.console.aws.amazon.com/transcribe/home?region=us-east-2
` create aws transcribe job pointing to the .m4a file
` when transcription completes, download the json document that contains the transcription
` copy the text, paste into https://translate.google.com/?sl=ru
` $

- - -
_2022-03-02 13:17_

https://www.cnn.com/2022/03/06/politics/trump-putin-ukraine/index.html[] <- +
https://www.youtube.com/channel/UC6NQtwx4Bl7Ua_cvtiNe3Fw[] <- леонид волков, Начальник штаба Алексея Навального; основатель Общества Защиты Интернета // Chief of staff for Alexey Navalny // 
https://donate.fbk.world[] // +
https://ozi-ru.org[] +

- - -
_2022-03-02 12:45 Милов: Путин катастрофе__

https://www.youtube.com/watch?v=S1ZpAoG0b9E&ab_channel=%D0%9D%D0%B0%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9LIVE[] <- +
nlnk.ru
- - -
_2022-03-01 08:25 Russia's war on Ukraine_
https://www.bbc.com/russian/live/news-60570934[] <- +
https://www.bellingcat.com/news/2022/02/27/follow-the-russia-ukraine-monitor-map/[] <- +

 9 days ago, Putin officially decided to kill innocent people. 9 days ago, our country began to be considered an absolute evil.

 Bombs and rockets fall on Ukrainian cities. Russians can no longer buy many brands and read independent media.

 Everyone knows that every day the situation will get worse. Putin is closing Russia with an iron curtain - away from free internet, safe world and justice. We will tell you about all the events of the day in our live broadcast.

 Come out to rallies against the war! On a weekday at 19:00 and this Sunday, March 6, at 14:00.

 Moscow - Manezhnaya Square
 Petersburg - Nevsky Prospekt near Gostiny Dvor
 Novosibirsk - the square near the opera house
 Yekaterinburg - Labor Square
 Other cities of Russia and the world - in the central squares.

 Send us photos and videos from rallies in your city: https://t.me/protestlivebot

 Our social networks:
 Telegram: https://t.me/teamnavalny
 Instagram: https://instagram.com/teamnavalny
 Facebook: https://fb.com/teamnavalny
 Twitter: https://twitter.com/teamnavalny

- - -
_2021-09-20 09:23 Lavrov exposé_

https://www.youtube.com/watch?v=xNa5XknuXkQ&t=1s&ab_channel=%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9%D0%9D%D0%B0%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9

- - -
_2020-12-29 09:11 references and links_

https://lookerstudio.google.com/u/0/reporting/dfbcec47-7b01-400e-ab21-de8eb98c8f3a/page/p_wdrgjv1iyc?s=ipoqvE46dxM[] <- +
https://www.jstor.org/stable/j.ctt9qg1cj[] +
*zov.pdf* 141 p from Russian paratrooper, Павел Филатьев +
Подробнее на livelib.ru:
https://www.livelib.ru/work/1007463292-zov-pavel-filatev +
https://zen.yandex.ru/id/62e6388b6138d4474d326a55[] <- !! Времени на раскачку нет (there is no time to slack off) +
https://english.nv.ua[] <- New Voice of Ukraine +
https://www.wired.com/story/ddosecrets-blueleaks-wikileaks/[] <- ddosecrets +
https://ddosecrets.com/wiki[] <- anon repo +
https://novayagazeta.eu/[] <- Novaya Gazeta EU; in RU, EN +
https://twitter.com/novayagazeta_en[] <- Twitter/English +
https://www.youtube.com/channel/UChrHmNulUHipsnmA76vhScA[] <- resources and links for hack your russian with Mila +
https://www.hackyourrussian.com/post/russian-movies-subtitles[] <- !! with explanation and grammar notes +
https://www.rferl.org/[] <- radio free Europe +
https://donate.fbk.world/en[] <- navalny fnd +
https://twitter.com/RALee85/status/1504927427230904320[] <- state of war on 18 Mar 2022 +
https://twitter.com/JaneLytv/status/1502291868628967425[] <- collected sources and suggestions on covering Russia's war on Ukraine +
https://www.4freerussia.org/aquarium-leaks-inside-the-gru-s-psychological-warfare-program/[] <- translated RU psyops docs +
https://odessa-journal.com/bellingcat-investigator-claims-panic-in-kremlin-and-names-two-scenarios-for-putin/[] <- Eng/Ukr lang newssource +
https://www.bbc.com/mediacentre/articles/2022/advice-on-accessing-bbc-news[] <- tor, vpn; по руские +
https://www.agents.media/[] <- по руские +
https://www.theatlantic.com/international/archive/2022/02/vladimir-putin-ukraine-invasion-liberal-order/622950/?utm_source=twitter&utm_medium=social&utm_campaign=share[] <- +
https://www.theguardian.com/world/2022/mar/03/people-leaving-russia-ukraine-war[] <- +
https://novayagazeta.eu/[] <- Novaya Gazetta EU; in RU. EN +
https://meduza.io/en[] +
https://meduza.io/ru[] +
https://www.wilsoncenter.org/event/after-navalnys-poisoning <= Leonid Volkov, CoStaff to Navalny
https://echo.msk.ru/news/2783620-echo.html[] +
https://openmedia.io/category/news/[] +
https://openmedia.io/news/n1/[] + navalnyj-posle-aresta-i-rassledovaniya-o-dvorce-obognal-putina-po-zaprosam-v-yandekse/[] +
https://github.com/OpenCorpora/opencorpora[] +
http://itools.com/tool/google-translate-web-page-translator[] +
https://nlp.stanford.edu/IR-book/html/htmledition/irbook.html[] Info Retrieval Book +
https://github.com/kmike/pymorphy2[] <- Morphological analyzer (POS tagger + inflection engine) for Russian and Ukr lang. Lic. MIT +
- Morphological_Analyzer_and_Generator_for_Russian_a.pdf
http://proling.iitp.ru/etap4[] <- online sentence structure analysis and translator +
https://ovdinfo.org/ <= https://www.opendemocracy.net/en/author/ovd-info/ +
https://www.youtube.com/watch?v=ipAnwilMncI&feature=youtu.be 2 hr putin corruption
https://fbk.info/ <= Фонд борьбы с коррупцией (Anti-Corruption Foundation) +
https://www.readyrussian.org/Handouts/Grammar%205--Case%20Charts.html +
https://www.readyrussian.org/m?/start/subject_index/ +
