=== tiAccMan.adoc groups, policies, access management #i2-icp-data
- - -
_2020-07-02 12:41 Albert Wu group structuring for ICP_

https://docs.google.com/document/d/1MRV4ukDp4mbaVuPu8zh9zVP1jbxQgtEg1UsIilaRmXk/edit#heading=h.uzpo46jsypm6 <= Groups for the ICP

*  BillK: one pattern I want to get out of tomorrow is a collaboration group that includes a wiki space (or spaces), a project, and email list since I want to determine how to represent things to COmanage simple users.  Also need to consider that from a admin point of view

To prompt today’s discussion, and to Bill’s goal above, I suggest the following pattern:

*  Define groups based on the nature of participation and/or responsibility in a collaboration, i.e., Chair, Co-Chair, member, guest, flywheel, ex-officio, etc. We’ll call these Collaboration Roles

*  Place humans in those Collaboration Role groups

*  Designate someone in that collaboration (ooh. Collaboration Admin) to administer the Collaboration’s Collaboration Role memberships

*  For each collaboration tool under ICP control, and the collaborators need access to, define groups to reflect the tool’s access control model, as aligned as possible to the way the tool wants to work. (We’ll call these Tool Access Control groups for now). For example, for Sympa, for each mailing list, create an “owner”, a “moderator”, and a “subscriber” group to match the roles in Sympa list.

*  The Sympa admin should probably be responsible for provisioning these groups when creating the mailing list.

*  Depending on how the collaboration’s business rule about tool use (e.g., all TAC members are auto-subscribed to the TAC discussion list; TAC chairs and flywheels are owner and moderator of the TAC discussion list), add the appropriate Collaboration Role group(s) as members of the Tool Access Control groups.

*  So that: Collaboration admins only need to worry about assigning individuals to the relevant collaboration roles; tool admins only has to touch Grouper once on initial provisioning.

*  And: yes, we’ll need a pattern for dealing with exceptions. TBD

*  There is also another detail we should discuss if time allows: naming.
**   How we name Grouper folders and groups (ID, Name, description), and
**   how they are used in the integrated tools (Confluence, Jira, etc)
**   has a significant impact on the user experience and overall usability. It’ll be good to understand those as early as possible

.

- - -
_2020-07-02 12:26 Mining Grouper Training and Grouper Deployment Guide for emerging best practices_

Map Grouper groups to midPoint account, role, org and archetype

Looking through Grouper Training materials for examples and exercises to build on

Grouper School 201.1:  https://docs.google.com/presentation/d/1_6h3OQqB9XqPEggKzrwvkNcfKKbN6qQHKVJbAFu5Ax8/edit#slide=id.g5c7b068cf7_0_24[Basis and Reference Groups part 1], slide 8, “Hands on: All Students Reference Group”

Grouper School 201.2: https://docs.google.com/presentation/d/1m0eVpgvQ3O5Ljp3PFPyewLtV0GouEquSNjU6g7M3vA8/edit#slide=id.p[Basis and Reference Groups part 2], “Hands on: Other students”

Grouper School 201.3: https://docs.google.com/presentation/d/1D_6XH_DPlzQCuAiB9cdlp18zJ6UndW7T4v8qC3x-KME/edit#slide=id.p[Access Policy Groups]

Grouper School 201.4: https://docs.google.com/presentation/d/1BIocAbosOEHHhbdQRslRac-xMHR0OJQr6qBtkQ0V9lM/edit#slide=id.p[eduPersonAffiliation for Authorization]

Grouper School 201.5: https://docs.google.com/presentation/d/1wbwbjJSzouaJ2yZ_mOcbGTPR6pXD06IEDWUwFiHs4Cw/edit#slide=id.g5b9ef9afc5_1_44[Policy groups and static application permissions, eduPerson entitlement for student access to the wiki]

Grouper School 201.6: https://docs.google.com/presentation/d/1ofMewg8MGJawJDWXBit8uVzuu8t5_yEkCyQxTVoDoBU/edit#slide=id.p[Policy groups and dynamic application permissions, Subject to Role assignments in Grouper]

midPoint / Grouper Integration Demo


KeithH
13:05
Question about GTE 201.6 dynamic app permissions; Why is the folder structure app:cognos:service:……?
Are there other things under the app:cognos stem? (edited)

Bill Thompson  13:16
yes. standard grouper app template provides a set of folders and default grouper privilege settings.
13:17
app:congnos:service, app:congos:security, app:cognos:service:policy,…
13:18
create an new app using the template. there are few options for more complicated structures.

Chris Hyzer  13:22
Maybe the question why not put things in the “cognos” folder?   Because in the security folder is the list of updaters and the list of admins.  If the updaters had recursive UPDATE privilege on the cognos folder, they could elevate their “role” to admin by updating the list of admins.  So we have a “service” folder, the updaters get recursive UPDATE there, and then they can edit the app role lists, but not give themselves or other people ADMIN.  Know what I mean? (edited)

Keith Hazelton  13:24
yes, that’s it, Chris. I see what you mean. Thanks. This will feed into an ICP meeting this afternoon

root
* org
**  collaborations
***    IdPaaS
****     @admin
****     @security
***      @apps
****        _confluence

*****          @service
******             policy
*******                confluence-allowed (collab member-users with access to the wiki)
*****          @security
******             admins
******             updaters
****        _jira
***            @admin
***            @security
***            ...

grouper.staging.at.internet2.edu
