=== tiComanage.adoc 8144413145
- - -
_2019-10-19 16:06_

- - -
_2019-09-16 21:38 Aligning VOperson and midPoint core person schema_

Benn Oshrin 16:16
Following up on last week’s call, I’ve started a spreadsheet
(https://docs.google.com/spreadsheets/d/1jcRplWlpciSMevNxBSeymr9mfRJEsVCvuwNkQu8fxRs/edit)

mapping COmanage attributes to midPoint, Minimal Schema, and R&S.

I didn’t actually complete the midPoint column, hopefully somebody from this channel could volunteer? (Send me a google account if you’re willing!)

https://docs.google.com/spreadsheets/d/1jcRplWlpciSMevNxBSeymr9mfRJEsVCvuwNkQu8fxRs/edit

- - -
_2019-02-13 09:00 COmanage training

- - -
_2019-02-01 14:00 COmanage training zoom 8144413145_

BennO and ScottK discuss potential content/organization for COmanage training

---
_4/19/16 5:01 PM Install TIER COmanage_

- Install Virtual Box per http://www.virtualbox.org/manual/
- download COmanage VM from https://testbed.tier.internet2.edu
  - VERY slow download: est. 1/2 hr.

- install COmanage on virtualbox per https://spaces.internet2.edu/display/TPD/COmanage+VM+Documentation
  - Once VirtualBox is installed and running, you import the .ovm distribution image using the File / Import Appliance function.
  - Another slow step importing the .ovm distro image (5' plus)

  Initial Testing Process

A quick test of the environment includes the following steps:

    Download the COmanage-1.0.ova file (or the most recent version) from the distribution site.
    Import the image into virtual box.
    Potentially change the network setting from NAT to Bridged - see above comments on VirtualBox.
    Start the virtual machine.
    Login to the VM:
        LoginId: comanage
        password: comanage
    Create a self-signed certificate for use in the test.  (See this sample output on the right)
    Fill in appropriate answers for Country and City.
    Be sure to keep track of the domain name that you put into the CN field.
        openssl req -x509 -nodes -days 365 -sha256  -newkey rsa:2048 -keyout coman.key -out coman.crt
    Copy the certificate files to the appropriate locations for the installer
        cp coman.key coman.crt /home/comanage/ssl/httpd
        cp coman.crt /home/comanage/ssl/httpd/incommon_chain.pem
    Run the configuration script:  ./bin/configure.sh
        As you answer the questions, make sure that the FQDN you specify now matches the CN value used when you created the certificate.  For this reason - you may just want to use IP addresses if they will be the same each time you run the virtual machine (as one might on a laptop virtual machine)
        You can safely put in fake answers to the email questions as that feature will not work as part of this simple test.
    Start comanage: ./bin/comanage.sh
        You will see the final build/configuration process.
        When this command returns, the Docker version of COmanage will be up and running.
    Verify that two containers are running via the command: docker ps
    If you enabled bridge mode described above
        Obtain the IP address of your virtual machine if you haven't done so already.
            ip addr | grep -i "inet" and look for and address from your campus network
        With a web browser, connect to: https://ip_addr/registry/
        Ignore the SSL warnings.
        You should connect to a login page.  Do not expect the login function to actually work, that requires InCommon integration and this quick test does not perform any InCommon integration.

192.168.1.233
