=== tiCsu.adoc
- - -
_2019-03-05 11:38 blue jeans session with JeffR and RandyM_

complex demo is up and running @ CSU

] plugins / connectors send link to the table of connectors

] CSU would like to work through Internet2 on mP support

support issues: two types: platform support; connectors

banner connector ethos InfoSys is implementing Ethos in Banner 9

use #tier-midpoint until CSU is on #i2-evolveum

multiple campus system;
- finding banner  Pueblo and Ft. Collins will be sharing Banner via Multi-entity processing: MEP; assigned a 9-char CS identifier; email addr will be campus specific; student record at each entity that where classes are taken;

Banner as SIS all gets into identity system, that drives service eligibility

Highly probable: manage identities from both campuses with midPoint person and course data; use grouper for course data as today, mP for person' out to CSU Pueblo and Ft. Collins; per data banner to mP; pueblo AD connector for pueblo people.

] How should that look in midpoint

Grouper => LDAP <= midPoint

] Erica Lomax midPoint at OSU ??

data flow: setup directions; changed pwd for BobA, etc.

Grouper sysadmin driven from mP -- how?

] list of institutions using mP today; <= only a few started OSU, Lafayette, Mines, W Ontario

Is I2 neutral on on-prem and cloud?

ITAP 1.0 release schedule?
] Find out this week for them
