=== tierDocs.adoc
https://docs.google.com/document/d/1P4dDR16YEiqBfRJp-Z7HNDnKJTxzg8JUA671U15qm60/edit#heading=h.wwso5s93chnm

- - -
_2019-02-21 12:00 ITAP Documentation w DavidWalker, BillK, WarrenC, JimJ, KeithH_

FYI, for discussion in our call on Thursday, I've given the draft outline on
https://spaces.at.internet2.edu/pages/viewpage.action?pageId=143720992[DRAFT - InCommon Trusted Access Platform Documentation] some substance and connecting tissue.  It now looks more like a web page (with a growing list of unresolved issues at the end).

see updated ID Match:  COmanage Match Technical Manual - https://spaces.at.intSernet2.edu/display/COmanage/COmanage+Match+Technical+Manual

https://docs.google.com/presentation/d/1TDqcWpLQY73OLQhmQcJA_UgVt0_fDDr_ZXtjD4QlFzs/edit#slide=id.g4b1de247d1_0_921 Erin's training

https://docs.google.com/presentation/d/1o6X2eN_NIkPAQ89E-MJFdl3KLvqcbqYRCmNTfmx21Y0/edit#slide=id.g4cd7273c45_2_75

https://spaces.at.internet2.edu/display/ITAP/DRAFT+-+InCommon+Trusted+Access+Platform+Documentation

https://docs.google.com/document/d/1EuUYm98rp_kxJu9DTiyFWnNW0td0Om24-bTq5fRHda4/edit  <= TIER Documentation Deliverables Artifacts

Devops Guide is informative;

- - -
_2019-02-12 14:13 Info Arch discussions_


Copying Dean to make sure he is in the loop on this work.

Keith, David, and I spoke yesterday and went through some of the material.

We are pretty much in agreement on an outline to organize things that follows what David has put in the wiki https://spaces.at.internet2.edu/x/BAd0C .

I agreed to use that outline to take another pass at getting a further handle on all of the stuff out there and organizing it under that outline which is getting close at:

https://docs.google.com/document/d/1EuUYm98rp_kxJu9DTiyFWnNW0td0Om24-bTq5fRHda4/edit?usp=sharing

I think I have a most of the up front stuff in good shape, but we will need work under Reference Material to organize all of the API and Entity Registry Documents/artifacts.

Jim – we need you to take a look at all the Packaging stuff as I have suggested that a number of pages should be deprecated.  All we need it your comments on that and not actually doing anything with existing pages.

David, we will need to add something to the wiki, maybe a sub-page, that includes a Plan for what we do with all of the WG pages and references in the wiki and all also mentions the TIER and component pages on the I2 website.   That will help a lot as we determine the full migration to InCommon.org for the Trusted Access Platform.

We might also want a section of the Plan to include a way to archive and lock down all of the google doc material that is not part of go-forward work.

I will work on scheduling another call.

 Best regards

-- Bill Kaufman

Senior PM – Integration & Architecture
Internet2
O - (734) 352-7086 | M - (734) 323-8623

- - -
_2019-01-22 10:00 kick-off meeting https://internet2.zoom.us/j/7343238623_

===== We will do a run through of this:


. Aligning our menagerie of architecture diagrams; Which do we lead with and build on in our communications?
.. Remember the 4 types of documentation

 where does this text show up?

.. (BillK) DavidW will be helping BillT, WarrenC, KeithH sift through)



... Bring in cleaned up packaging diagrams; bring WGs together?



... InCommon.org is being completely reworked, TIER work will be rebranded and incorporated into this side



... See InCSiteMap from BillT



... WarrenC: Be careful of the habit of treating components as stand-alone items, lose focus on the integration



... CareyB: Have we abandoned idea of a standard message schema and falling back to point-to-point integrations? ... Seems like it.



... Look to MichaelG’s beefed up messaging support in Grouper;



.. TIER Reference Architecture (reference) with narrative walkthroughs (how-to’s)



... Add a 2nd page with components overlay



...  Update the details



... Find the underlying Visio




.. TIER ENTITY REGISTRY-IDENTITY ONBOARDING
... Onboarding provides basis for a series of tutorials. DavidW as organizer and tech writer can provide assistance.
... This identifies functions, alluding to components but not specifying choice of components
... (MattB) Add info showing what kind of data is needed to determine student, staff, others; Banner ‘roles’ are misleading in terms of what Mines really considers to be, say, student, faculty...Institutions differ widely in their operational definitions of these basic affiliations. There are situations when degrees are revoked, so even alumni is not necessarily lifelong
... GDRIVE folder including
.... TIER Architecture with Integration Detail (pipeline and protocols
.... Happy Boy (Good graphic to use with narrative walkthroughs)
..... PWM: Is this a level below what should be in our reference diagram?
.... Multiple options for full TIER Reference Implementations (JimJ)
.. COmanage midPoint Integration Approaches to show how COmanage could plug into Reference Architecture as Guest Management System of Record (explanatory documentation for understanding)
.. Complex midPoint Integration demo
... Detailed version of complex midPoint integration demo (reference doc)
.. Packaging Stuff
... Docker Reference Implementations (Purple = Deprecated?)
.... COmanage Docker Reference Implementation
.... Grouper Docker Reference Implementation
.... Shibboleth Docker Reference Implementation
.... midPoint Docker Reference Implementation
.... TIER Docker Container Specification
.... TIER Container Preview Release Program
.... Campus Shibboleth Metadata Management (deprecated)
.... Copy of TIER Docker Container Spec (deprecated)
.... Core Packaging Assumptions Reference (deprecated)
.... Core Packaging Build Documents (deprecated)
.... Core Packaging Methodology (deprecated)
.... Shibboleth Relying Party Configuration (deprecated)
.. Shibboleth Metadata Management GUI (deprecated)
.. ID Match Poc   (is this good for a main ID Match landing page?)
