=== tiMidPointTraining.adoc  on NbP & xps (was oMbP)
https://internet2.app.box.com/notes/392303589694 +
mPdocker-composeBuild.utf +
mPdocker-composeUp.utf +
gD/My Drive/midpointTraining/midpoint-deployment-fundamentals-mid101-slides.pdf +
~/eclipse-workspace/mp-training/guide/LABS-MID101.2018.A-docker.pdf  <= Student Lab Guide +
sudo docker exec -it <containerId> /bin/bash +
https://training.evolveum.com/MID-101.2018.A.docker/ <= training/trMid101aD0ck3r#

- - -
_2019-12-16 08:03 spin up personal copy of training environment on NbP_

```
Successfully built 99ff22ca6c7f
Successfully tagged tier/midpoint:latest
----------------------------------------------------
The midPoint containers were successfully built. To start them, execute the following:

(for simple demo)

$ cd /Users/khazelton/midPoint_container/demo/simple
$ docker-compose up

(for Grouper integration demo)

$ cd /Users/khazelton/midPoint_container/demo/grouper
$ docker-compose up --build

khazelton@MbP-Catalina grouper % docker-compose up --build
Creating network "grouper_net" with driver "bridge"
Creating volume "grouper_grouper_data" with default driver
...
Step 3/9 : RUN yum install -y epel-release     && yum update -y     && yum install -y mariadb-server mariadb     && yum clean all     && rm -rf /var/cache/yum
 ---> Running in b440759412e5
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again
```
- - -
_2019-12-15 21:06 personal copy of midPoint Basics repo_

kh/I2/myD/"midPoint Basics"/ +
aktis.org:/home/khazelton <= archive of mP training code package +
xps:/home/khazelton <= archive of mP training code package +
NbP Documents/_pdf/ <= slides and setup info +
```
- - -
_2019-12-05 21:06 1st run of new 3-day midPoint Basics training_

AWS training environment

ssh -L8443:localhost:8443 -L10443:localhost:443 -L4443:localhost:4443  -L15672:localhost:15672 -L10389:localhost:389 -l student    3.136.108.147 +
14e51641

Available 'til Dec 20
```
- - -
_2019-11-26 04:47 2019-12 Training Run-through_

https://drive.google.com/drive/u/2/folders/1ePMtqIgLKoRXlU0VIvf2NwlfZ6yg73y4 <= mP basics training folder

```
~/Downloads
total 106712
-rw-rw-r-- 1 khazelton khazelton 106351664 Nov 26 04:44  zulu8.42.0.23-ca-jdk8.0.232-linux_amd64.deb
-rw-rw-r-- 1 khazelton khazelton    248072 Nov 26 04:40  LABS-basics-prerequisites.pdf
-rw-rw-r-- 1 khazelton khazelton    380282 Nov 26 04:38  LABS-basics.pdf

https://aboullaite.me/switching-between-java-versions-on-ubuntu-linux/

(base) khazelton@xps:~$ java -version

openjdk version "1.8.0_232"
OpenJDK Runtime Environment (Zulu 8.42.0.23-CA-linux64) (build 1.8.0_232-b18)
OpenJDK 64-Bit Server VM (Zulu 8.42.0.23-CA-linux64) (build 25.232-b18, mixed mode)
(base) khazelton@xps:~$
```

*LAB 1-1*
```
Local port (your machine)         AWS Workstation Port Description
_________________________         ________________________________
8443                              "" midPoint GUI (https)
4443                              "" Grouper UI (https)
10443                             "443" Shibboleth IDP (https)
15672                             "" Rabbit MQ GUI (http)
10389                             "389" Directory server LDAP port

my training ssh command:

ssh -L8443:localhost:8443 -L10443:localhost:443 -L4443:localhost:4443  -L15672:localhost:15672 -L10389:localhost:389 -l student    3.136.108.147

14e51641

(base) khazelton@xps:~$ ssh -L8443:localhost:8443 -L10443:localhost:443 -L4443:localhost:4443  -L15672:localhost:15672 -L10389:localhost:389 -l student    3.136.108.147
The authenticity of host '3.136.108.147 (3.136.108.147)' can't be established.
ECDSA key fingerprint is SHA256:sR7c2INK5s4odDn4AJT21Pm4YQEo+MZxu471OeYLsdY.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '3.136.108.147' (ECDSA) to the list of known hosts.
student@3.136.108.147's password:
bind: Address already in use
Last failed login: Tue Nov  5 13:21:38 UTC 2019 from 68.183.48.173 on ssh:notty
There were 57 failed login attempts since the last successful login.

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
[student@ip-172-31-16-80 ~]$
```
see midPoint Training Prerequisites p. 7 Environment Cheat Sheet

build, docker-compose up, browse to midPoint and Grouper

p. 5, "We have just completed the training environment initialization so that it can be used in further labs."

*LAB 1-2, p. 6*

*Module 2: midPoint Introduction*
*LAB 2-1: Inspecting midPoint GUI, p. 7*

*Module 3: Integrating midPoint with Grouper*
*LAB 3-1: Initial Group Synchronization with Grouper*

*LAB 3-2: Initial Group Membership Synchronization with Grouper, p. 16*

- - -
_2019-02-14 12:00 CO State Getting Started with midPoint_container_

- - -
_2019-02-13 10:00 mP training meeting_

https://docs.google.com/document/d/1zaXIwK_FW_7Fpv5_-EE6gXOvFXwCyOtDRXychw7HMTM/edit?usp=sharing <= mP 101 exercises as potential use cases

  use cases from mP training

- - -
_2019-02-14 12:00 mP training meeting_

JeffR & RandyM & gregV

https://github.internet2.edu/khazelton/tiapi/blob/master/midPointInstallTips.adoc

ssh to VM

```
sudo docker exec -it {container_id} /bin/bash
bash-4.2# wget --no-check-certificate https://yourHost.edu:4443/grouper
```
- - -
_2019-01-30 09:21 mP training meeting, https://internet2.app.box.com/notes/392303589694_

ChrisHu, PaulC, ErinM, EthanK, Keith

https://github.com/Internet2/comanage-registry-docker  <= to bring up full COmanage environment +
https://drive.google.com/open?id=1mtnvrx4I5W3nUpGmc5t5NIn7hvKDZrQo <= @m gDrive folder from midPoint training +
https://internet2.box.com/s/eavl96st6gd1y81fapnyx0pw13odeu93	<= Box Link to developed training

] b'storm .edu exercises

next: Erin to schedule us w Igor to review training options

---
Just a reminder that we have some action items due for tomorrow.

Everyone should review the midpoint training that’s already been developed and update the Google Sheet, on the Module Review, with

Keep / Do More / Do Less / etc.

Once we have this sketched out, we can meet with Igor to talk about next steps on working toward an SOW for training development.

Also, everyone should please continue to think about what gaps exist for the EDU use cases and document those on the EDU Gaps tab.

That’s our agenda, although I’ll take notes over here.

Talk to you all Wednesday at 11:00 ET.   --Erin

- - -
_2018-04-06 11:42_
https://stackoverflow.com/questions/30172605/how-to-get-into-a-docker-container/33060711#33060711

- problem:

From here: https://github.com/moby/moby/issues/22507

I ran:

ps axf | grep docker | grep -v grep | awk '{print "kill -9 " $1}' | sudo sh

sudo ln -s /usr/libexec/docker/docker-runc-current /usr/bin/docker-runc

- - -
_2018-02-28 20:42   recap, key items & files_

*midPoint 3.7 and dependencies as Docker containers*

~/opt/mid101trainingWeekVersion
```
mid101trainingWeekVersion
├── docker-compose.yaml      <= used by docker-compose
├── mp-openldap
│   ├── Dockerfile           <= dockerfile for openldap
│   └── bootstrap
│       └── ldif
│           ├── 03-memberOf.ldif
│           ├── 03-sssvlv.ldif
│           ├── 100-example.ldif
│           └── 110-example-idmadmin-aci.ldif
├── mp-postgres
│   ├── 10-create-midpoint.sql
│   ├── 20-postgres-3.7-all.sql
│   └── Dockerfile           <= dockerfile for postgres
├── mp-training
│   ├── Dockerfile           <= dockerfile for midPoint
│   ├── config-postgresql.xml
│   ├── custom_connectors
│   │   ├── connector-csv-2.1.99.jar
│   │   └── scriptedsql-connector-1.1.2.0.em3.jar
│   ├── export.xml
│   ├── mid101-flatfiles
│   │   ├── csv-1-app-1.csv
│   │   ├── csv-1-app-1.csv.dist
│   │   ├── csv-2-app-2.csv
│   │   ├── csv-3-ldap.csv
│   │   └── source.csv
│   ├── mid101-flatfiles.zip
│   ├── midpoint-3.7.1-SNAPSHOT-dist.tar.gz
│   └── midpoint-entrypoint.sh
├── source.csv
└── source.csv.new

https://training.evolveum.com/MID-101.2018.A.docker/   <=  mP training materials

cp -R mPtrainingMaster/. midPointWork-01          <= full clone of master

~/opt/midPointWork-01  <= working copy 01

tree ~/opt/midPointWork-01

/Users/khazelton/opt/midPointWork-01
├── LABS-MID101.2018.A-docker.pdf
├── README-MID101.txt
├── mid101-docker-labs
│   ├── README.txt
│   ├── custom_connectors
│   │   ├── connector-csv-2.1.99.jar
│   │   └── scriptedsql-connector-1.1.2.0.em3.jar
│   ├── guide
│   │   └── LABS-MID101.2018.A-docker.pdf
│   ├── objects
│   │   ├── lookupTables
│   │   │   └── lookup-employee-type.xml
│   │   ├── misc
│   │   │   ├── sysconfig-deployment.txt
│   │   │   ├── sysconfig-notifications-SMTP.txt
│   │   │   └── sysconfig-notifications.txt
│   │   ├── objectTemplates
│   │   │   ├── object-template-example-org.xml
│   │   │   ├── object-template-example-user-orgstruct.xml
│   │   │   ├── object-template-example-user(base) khazelton@xps:~$ ssh -L8443:localhost:8443 -L10443:localhost:443 -L4443:localhost:4443  -L15672:localhost:15672 -L10389:localhost:389 -l student    3.136.108.147
The authenticity of host '3.136.108.147 (3.136.108.147)' can't be established.
ECDSA key fingerprint is SHA256:sR7c2INK5s4odDn4AJT21Pm4YQEo+MZxu471OeYLsdY.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '3.136.108.147' (ECDSA) to the list of known hosts.
student@3.136.108.147's password:
bind: Address already in use
Last failed login: Tue Nov  5 13:21:38 UTC 2019 from 68.183.48.173 on ssh:notty
There were 57 failed login attempts since the last successful login.

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
[student@ip-172-31-16-80 ~]$
-simple.xml
│   │   │   └── object-template-example-user.xml
│   │   ├── organizations
│   │   │   ├── org-example-root.xml
│   │   │   ├── org-example.xml
│   │   │   └── org-secret-ops.xml
│   │   ├── resources
│   │   │   ├── HOWTO-openldap-slapdconf-overlay.txt
│   │   │   ├── localhost-csvfile-1-simulated-app-1.xml
│   │   │   ├── localhost-csvfile-2-simulated-app-2.xml
│   │   │   ├── localhost-csvfile-3-ldap.xml
│   │   │   ├── localhost-hr-noextension.xml
│   │   │   ├── localhost-hr.xml
│   │   │   └── openldap-localhost-medium.xml
│   │   ├── rest
│   │   │   ├── 01-search-user-X000389.sh
│   │   │   ├── 02-change-user-X000389.sh
│   │   │   ├── 03-test-csv1.sh
│   │   │   ├── modification-change-givenName.xml
│   │   │   └── query-X000389.xml
│   │   ├── roles
│   │   │   ├── role-addressbook-manager.xml
│   │   │   ├── role-basicuser.xml
│   │   │   ├── role-csv1-tester.xml
│   │   │   ├── role-csv3-admin.xml
│   │   │   ├── role-employee.xml
│   │   │   ├── role-incognito.xml
│   │   │   ├── role-ldapgroup.xml
│   │   │   ├── role-meta-ldapgroup.xml
│   │   │   ├── role-secret-i.xml
│   │   │   ├── role-secret-ii.xml
│   │   │   ├── role-terraforming.xml
│   │   │   └── role-top-secret-i.xml
│   │   ├── securityPolicies
│   │   │   ├── example-security-policy-administrators.xml
│   │   │   ├── example-security-policy.xml
│   │   │   ├── example-simpler-security-policy.xml
│   │   │   └── example-stronger-security-policy.xml
│   │   ├── tasks
│   │   │   ├── task-bulk-print-employees.xml
│   │   │   └── task-bulk-set-description-static.xml
│   │   └── valuePolicies
│   │       ├── example-password-policy.xml
│   │       ├── example-simpler-password-policy.xml
│   │       └── numeric-pin-first-nonzero-policy.xml
│   └── schema
│       └── extension-example.xsd
├── mid101-docker-labs.zip
├── mid101-flatfiles
│   ├── csv-1-app-1.csv
│   ├── csv-2-app-2.csv
│   ├── csv-3-ldap.csv
│   └── source.csv
├── mid101-flatfiles.zip
└── midpoint-deployment-fundamentals-mid101-slides.pdf

16 directories, 58 files

KeithsOfficeMBP:mid101 khazelton$ cd ~/opt/mPtrainingMaster  <=  oMbP pristine copies
KeithsOfficeMBP:mPtrainingMaster khazelton$ tree
.
├── LABS-MID101.2018.A-docker.pdf
├── MidPoint\ Training\ Centos7.ova.crdownload     <= removed from the midpoint master
├── README-MID101.txt
├── mid101-docker-labs
│   ├── README.txt
│   ├── custom_connectors
│   │   ├── connector-csv-2.1.99.jar
│   │   └── scriptedsql-connector-1.1.2.0.em3.jar
│   ├── guide
│   │   └── LABS-MID101.2018.A-docker.pdf
│   ├── objects
│   │   ├── lookupTables
│   │   │   └── lookup-employee-type.xml
│   │   ├── misc
│   │   │   ├── sysconfig-deployment.txt
│   │   │   ├── sysconfig-notifications-SMTP.txt
│   │   │   └── sysconfig-notifications.txt
│   │   ├── objectTemplates
│   │   │   ├── object-template-example-org.xml
│   │   │   ├── object-template-example-user-orgstruct.xml
│   │   │   ├── object-template-example-user-simple.xml
│   │   │   └── object-template-example-user.xml
│   │   ├── organizations
│   │   │   ├── org-example-root.xml
│   │   │   ├── org-example.xml
│   │   │   └── org-secret-ops.xml
│   │   ├── resources
│   │   │   ├── HOWTO-openldap-slapdconf-overlay.txt
│   │   │   ├── localhost-csvfile-1-simulated-app-1.xml
│   │   │   ├── localhost-csvfile-2-simulated-app-2.xml
│   │   │   ├── localhost-csvfile-3-ldap.xml
│   │   │   ├── localhost-hr-noextension.xml
│   │   │   ├── localhost-hr.xml
│   │   │   └── openldap-localhost-medium.xml
│   │   ├── rest
│   │   │   ├── 01-search-user-X000389.sh
│   │   │   ├── 02-change-user-X000389.sh
│   │   │   ├── 03-test-csv1.sh
│   │   │   ├── modification-change-givenName.xml
│   │   │   └── query-X000389.xml
│   │   ├── roles
│   │   │   ├── role-addressbook-manager.xml
│   │   │   ├── role-basicuser.xml
│   │   │   ├── role-csv1-tester.xml
│   │   │   ├── role-csv3-admin.xml
│   │   │   ├── role-employee.xml
│   │   │   ├── role-incognito.xml
│   │   │   ├── role-ldapgroup.xml
│   │   │   ├── role-meta-ldapgroup.xml
│   │   │   ├── role-secret-i.xml
│   │   │   ├── role-secret-ii.xml
│   │   │   ├── role-terraforming.xml
│   │   │   └── role-top-secret-i.xml
│   │   ├── securityPolicies
│   │   │   ├── example-security-policy-administrators.xml
│   │   │   ├── example-security-policy.xml
│   │   │   ├── example-simpler-security-policy.xml
│   │   │   └── example-stronger-security-policy.xml
│   │   ├── tasks
│   │   │   ├── task-bulk-print-employees.xml
│   │   │   └── task-bulk-set-description-static.xml
│   │   └── valuePolicies
│   │       ├── example-password-policy.xml
│   │       ├── example-simpler-password-policy.xml
│   │       └── numeric-pin-first-nonzero-policy.xml
│   └── schema
│       └── extension-example.xsd
├── mid101-docker-labs.zip
├── mid101-flatfiles
│   ├── csv-1-app-1.csv
│   ├── csv-2-app-2.csv
│   ├── csv-3-ldap.csv
│   └── source.csv
├── mid101-flatfiles.zip
└── midpoint-deployment-fundamentals-mid101-slides.pdf       <= training 'textbook' slides

16 directories, 59 files


/Users/khazelton/Downloads/mid101-docker-labs   <=  Material I actually used during the training

KeithsOfficeMBP:mid101 khazelton$ tree /Users/khazelton/Downloads/mid101-docker-labs
/Users/khazelton/Downloads/mid101-docker-labs
├── README.txt
├── custom_connectors
│   ├── connector-csv-2.1.99.jar
│   └── scriptedsql-connector-1.1.2.0.em3.jar
├── guide
│   └── LABS-MID101.2018.A-docker.pdf     <= lab book with exercises
├── objects
│   ├── lookupTables
│   │   └── lookup-employee-type.xml
│   ├── misc
│   │   ├── sysconfig-deployment.txt
│   │   ├── sysconfig-notifications-SMTP.txt
│   │   └── sysconfig-notifications.txt
│   ├── objectTemplates
│   │   ├── object-template-example-org.xml
│   │   ├── object-template-example-user-orgstruct.xml
│   │   ├── object-template-example-user-simple.xml
│   │   └── object-template-example-user.xml
│   ├── organizations
│   │   ├── org-example-root.xml
│   │   ├── org-example.xml
│   │   └── org-secret-ops.xml
│   ├── resources
│   │   ├── HOWTO-openldap-slapdconf-overlay.txt
│   │   ├── localhost-csvfile-1-simulated-app-1.xml
│   │   ├── localhost-csvfile-2-simulated-app-2.xml
│   │   ├── localhost-csvfile-3-ldap.xml
│   │   ├── localhost-hr-noextension.xml
│   │   ├── localhost-hr.xml
│   │   └── openldap-localhost-medium.xml
│   ├── rest
│   │   ├── 01-search-user-X000389.sh
│   │   ├── 02-change-user-X000389.sh
│   │   ├── 03-test-csv1.sh
│   │   ├── modification-change-givenName.xml
│   │   └── query-X000389.xml
│   ├── roles
│   │   ├── role-addressbook-manager.xml
│   │   ├── role-basicuser.xml
│   │   ├── role-csv1-tester.xml
│   │   ├── role-csv3-admin.xml
│   │   ├── role-employee.xml
│   │   ├── role-incognito.xml
│   │   ├── role-ldapgroup.xml
│   │   ├── role-meta-ldapgroup.xml
│   │   ├── role-secret-i.xml
│   │   ├── role-secret-ii.xml
│   │   ├── role-terraforming.xml
│   │   └── role-top-secret-i.xml
│   ├── securityPolicies
│   │   ├── example-security-policy-administrators.xml
│   │   ├── example-security-policy.xml
│   │   ├── example-simpler-security-policy.xml
│   │   └── example-stronger-security-policy.xml
│   ├── tasks
│   │   ├── task-bulk-print-employees.xml
│   │   └── task-bulk-set-description-static.xml
│   └── valuePolicies
│       ├── example-password-policy.xml
│       ├── example-simpler-password-policy.xml
│       └── numeric-pin-first-nonzero-policy.xml
└── schema
    └── extension-example.xsd
```

- - -
_2018-02-28 09:20   day 5, am session_

*15: Backup and Restore*

sudo docker exec -it mp-training /usr/bin/java -jar /opt/training/midpoint/lib/ninja.jar -m /opt/training/midpoint/var export -O /opt/training/midpoint-labs/export.xml

https://wiki.evolveum.com/display/midPoint/Ninja

*16: Connectors*

var/log/midpoint.log

system config object controls logging AFTER system startup;  before: ../midpoint/log
- if you want to change pre-startup log, see
  WIKI Initial Logging Setup HOWTO

Loggers
- Root (default applies to all logs unless otherwise specificed), All, Component-specific, custom logger, Audit logger (checkbox: will also go to midpoint.log)

Log levels
- definable for each logger except Audit log
- OFF < ERROR < WARN < INFO < DEBUG < TRACE (ALL)
- e.g. DEBUG for provisioning, OFF for Root:  Only provisioning messages

Appender
- destination of log messages
- file, console, syslog, etc.
- logs can set appender per logge

WIKI: Useful Loggers
WIKI: Troubleshooting Connectors

<mapping>
<trace>true</trace>

check midpoint.log for any/all startup problems; including connector loading

----------
17: Logging and tracing:

<mP>/

WIKI: OrgSync Story Test

could use metarole to create groups for each org unit

useful on initial load and on live sync

- - -
_2018-02-27 16:41  day 4, pm session zoom 444-392-608  sudo docker exec -u midpoint -it adfb99b7a68b /bin/bash_

gotchas:

ASSIGNING resource via inducement from role (eg, create OpenLDAP account for end users)
- add openLdap as inducement from end user role BY CHANGING TYPE in select object window top left dropdown to RESOURCE from ROLE

- similarly to ASSIGN user to org, select type: ORG from the select object Dropdown

backup:  DB backup, ninja (see wiki)

- - -
_2018-02-27 08:38  day 4, am session zoom 444-392-608  sudo docker exec -u midpoint -it adfb99b7a68b /bin/bash_

Notifications - mail,file,SMS:
- https://wiki.evolveum.com/display/midPoint/Configuring+notifications#Configuringnotifications-"SMS"transport

https://wiki.evolveum.com/display/midPoint/REST+API  <== ++

Deployment information: configure look + feel of mP

- skin: admin LTE default;

Another node is just bringing up another mP connecting to the same database

mP repo is single point of failure; but you can use clustered dB

mP system is not 'critical' and if configured properly it will come back up gracefully.

node-sticky tasks howto in wiki, new in 3.7
- https://wiki.evolveum.com/display/midPoint/Node-sticky+tasks+HOWTO

----------
KeithsOfficeMBP:mid101 khazelton$ docker ps

CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                            NAMES
adfb99b7a68b        ubuntu-mid101:2018.A.docker     "/midpoint-entrypoin…"   20 hours ago        Up 12 hours         0.0.0.0:18080->8080/tcp                          mp-training
b6adaba913a3        postgres-mid101:2018.A.docker   "docker-entrypoint.s…"   20 hours ago        Up 12 hours         0.0.0.0:15432->5432/tcp                          mid101_postgres_1
325b1264cfb7        openldap-mid101:2018.A.docker   "/container/tool/run"    20 hours ago        Up 12 hours         0.0.0.0:10389->389/tcp, 0.0.0.0:10636->636/tcp   mid101_openldap_1
86f716fe0cc8        registry:2.5.0                  "/entrypoint.sh /etc…"   7 months ago        Up 12 hours         0.0.0.0:5000->5000/tcp                           registry

KeithsOfficeMBP:mid101 khazelton$ sudo docker exec -u midpoint -it adfb99b7a68b /bin/bash
Password:
midpoint@mp-training:/$ ls -la
total 76
drwxr-xr-x   1 root root 4096 Feb 26 18:43 .
drwxr-xr-x   1 root root 4096 Feb 26 18:43 ..
-rwxr-xr-x   1 root root    0 Feb 26 18:43 .dockerenv
drwxr-xr-x   1 root root 4096 Feb 18 19:56 bin
drwxr-xr-x   2 root root 4096 Apr 12  2016 boot
drwxr-xr-x   5 root root  360 Feb 27 03:05 dev
drwxr-xr-x   1 root root 4096 Feb 26 18:43 etc
drwxr-xr-x   1 root root 4096 Feb 18 19:56 home
drwxr-xr-x   1 root root 4096 Sep 13  2015 lib
drwxr-xr-x   2 root root 4096 Jan 23 22:49 lib64
drwxr-xr-x   2 root root 4096 Jan 23 22:49 media
-rwxr-xr-x   1 root root  810 Feb 18 19:33 midpoint-entrypoint.sh
drwxr-xr-x   2 root root 4096 Jan 23 22:49 mnt
drwxr-xr-x   1 root root 4096 Feb 18 19:56 opt
dr-xr-xr-x 207 root root    0 Feb 27 03:05 proc
drwx------   2 root root 4096 Jan 23 22:49 root
drwxr-xr-x   1 root root 4096 Feb 18 19:56 run
drwxr-xr-x   1 root root 4096 Jan 25 18:23 sbin
drwxr-xr-x   2 root root 4096 Jan 23 22:49 srv
dr-xr-xr-x  13 root root    0 Feb 27 03:05 sys
drwxrwxrwt   1 root root 4096 Feb 27 03:43 tmp
drwxr-xr-x   1 root root 4096 Jan 23 22:49 usr
drwxr-xr-x   1 root root 4096 Jan 23 22:49 var

- - -
_2018-02-26 12:33 day 3, pm session 444-392-608_

If you don't want to add an editor just to make a few small changes (e.g., change tomcat config), you can just

docker cp <container>:/path/to/file.ext .

which copies it to your local machine (to your current directory). Then edit the file locally using your favorite editor, and then do a

docker cp file.ext <container>:/path/to/file.ext

to replace the old file.

= e.g. =

KeithsOfficeMBP:mid101 khazelton$ docker cp adfb99b7a68b:/opt/training/midpoint-labs/flatfiles/source.csv .
KeithsOfficeMBP:mid101 khazelton$ ls -la source.csv
-rw-rw-r--  1 khazelton  staff  1554 Nov 27 07:39 source.csv
KeithsOfficeMBP:mid101 khazelton$ bbedit source.csv
KeithsOfficeMBP:mid101 khazelton$ docker cp source.csv adfb99b7a68b:/opt/training/midpoint-labs/flatfiles/source.csv

docker cp adfb99b7a68b:/opt/training/midpoint-labs/flatfiles/source.csv .

bbedit source.csv

docker cp source.csv adfb99b7a68b:/opt/training/midpoint-labs/flatfiles/source.csv

= show notifications log after reconfiguration in lab 11-1 =

midpoint@mp-training:/opt/training/midpoint-labs$ ls -la
total 24
drwxr-xr-x 4 midpoint midpoint 4096 Feb 27 16:07 .
drwxr-xr-x 4 midpoint midpoint 4096 Feb 18 20:07 ..
-rw-rw-r-- 1 midpoint midpoint 4763 Feb 27 16:07 example-mail-notifications.log
drwxr-xr-x 2 midpoint midpoint 4096 Feb 27 16:08 flatfiles
drwxr-xr-x 2 midpoint midpoint 4096 Feb 18 19:56 original

.logoint@mp-training:/opt/training/midpoint-labs$ cat example-mail-notifications

============================================
Tue Feb 27 16:07:46 UTC 2018
Message{to='[idm@example.com]', cc='[]', bcc='[]', subject='[IDM] SUCCESS: account ADD operation succeeded for X000997', contentType='null', body='Notification about account-related operation

User: Chick Norris (X000997, oid 7c3755ce-4c82-42ba-b750-fab6ebf8f833)
Notification created on: Tue Feb 27 16:07:46 UTC 2018

Resource: CSV-1 (Simulated App 1) (oid 10000000-9999-9999-0000-a000ff000002)

An account has been successfully created on the resource with attributes:
 - Login: cnorris
 - Last name: NORRIS
 - Groups:
   - All Employees
   - Essential Documents
 - Employee Number: 000997
 - Department: Java Development
 - First name: Chick
 - dis: false
 - Password:
    - Value: (protected string)
 - Administrative status: ENABLED



Requester: Keith Hazelton (khazelton)
Channel: null

'}

============================================
Tue Feb 27 16:07:46 UTC 2018
Message{to='[administrator@example.com]', cc='[]', bcc='[]', subject='[IDM] New account created by IDM for user: X000997', contentType='null', body='Password for account on CSV-1 (Simulated App 1) is: m6oC9'}

============================================
Tue Feb 27 16:07:47 UTC 2018
Message{to='[idm@example.com]', cc='[]', bcc='[]', subject='[IDM] SUCCESS: account ADD operation succeeded for X000997', contentType='null', body='Notification about account-related operation

User: Chick Norris (X000997, oid 7c3755ce-4c82-42ba-b750-fab6ebf8f833)
Notification created on: Tue Feb 27 16:07:47 UTC 2018

Resource: CSV-3 (Simulated LDAP) (oid 10000000-9999-9999-0000-a000ff000004)

An account has been successfully created on the resource with attributes:
 - Distinguished Name: cn=Chick Norris,ou=ExAmPLE,dc=example,dc=com
 - disabled: false
 - Mail: chick.norris@example.com
 - Last name: Norris
 - First name: Chick
 - Employee Number: 000997
 - Password:
    - Value: (protected string)
 - Administrative status: ENABLED



Requester: Keith Hazelton (khazelton)
Channel: null

'}

============================================
Tue Feb 27 16:07:47 UTC 2018
Message{to='[administrator@example.com]', cc='[]', bcc='[]', subject='[IDM] New account created by IDM for user: X000997', contentType='null', body='Password for account on CSV-3 (Simulated LDAP) is: m6oC9'}

============================================
Tue Feb 27 16:07:47 UTC 2018
Message{to='[idm@example.com]', cc='[]', bcc='[]', subject='[IDM] SUCCESS: account ADD operation succeeded for X000997', contentType='null', body='Notification about account-related operation

User: Chick Norris (X000997, oid 7c3755ce-4c82-42ba-b750-fab6ebf8f833)
Notification created on: Tue Feb 27 16:07:47 UTC 2018

Resource: CSV-2 (Simulated App 2) (oid 10000000-9999-9999-0000-a000ff000003)

An account has been successfully created on the resource with attributes:
 - Login: cnorris
 - disabled: false
 - Security Card PIN: 9514
 - Last name: Norris
 - First name: Chick
 - Department: Java Development
 - Employee Number: 000997
 - Password:
    - Value: (protected string)
 - Administrative status: ENABLED



Requester: Keith Hazelton (khazelton)
Channel: null

'}

============================================
Tue Feb 27 16:07:47 UTC 2018
Message{to='[administrator@example.com]', cc='[]', bcc='[]', subject='[IDM] New account created by IDM for user: X000997', contentType='null', body='Password for account on CSV-2 (Simulated App 2) is: m6oC9'}

============================================
Tue Feb 27 16:07:48 UTC 2018
Message{to='[idm@example.com]', cc='[]', bcc='[]', subject='[IDM] SUCCESS: User ADD operation succeeded for X000997', contentType='null', body='Notification about user-related operation (status: SUCCESS)

User: Chick Norris (X000997, oid 7c3755ce-4c82-42ba-b750-fab6ebf8f833)
Notification created on: Tue Feb 27 16:07:48 UTC 2018

The user record was created with the following data:
 - Name: X000997
 - Full name: Chick Norris
 - Given name: Chick
 - Family name: Norris
 - Title: Application Developer
 - Email Address: chick.norris@example.com
 - Employee Number: 000997
 - Employee Type: EMP
 - Cost Center: 0210
 - Organizational Unit: Java Development
 - Extension:
    - Organizational Path: Software Division:Java Development
    - Is Manager: false
    - Employee Status: 1
 - Credentials:
    - Password:
       - Value: (protected string)
 - Activation:
    - Administrative status: ENABLED
    - Valid from: Jul 15, 2010 8:20:56 AM
 - Assignment #1:
    - Target: ACT (org) [default]
 - Assignment #2:
    - Target: 0210 (org) [default]
 - Assignment #3:
    - Target: Employee (role) [default]

Requester: Keith Hazelton (khazelton)
Channel: http://midpoint.evolveum.com/xml/ns/public/provisioning/channels-3#liveSync

'}





full text search eg description

see Full text search HOWTO

cp source.csv adfb99b7a68b:/opt/training/midpoint-labs/flatfiles/source.csv

look for 'role autoassign' in wiki

= System configuration object:  Of major importance =

this module 11 focuses on Notification (to users)


=== BREAK ===

module 12: Authorizations

authZ: 2 flavors:  Request, Execute

AuthZ Config, Troubleshooting AuthZ:  see wiki

Admin GUI config authZ

= Schema xsd =

https://github.com/Evolveum/midpoint/blob/master/infra/schema/src/main/resources/xml/ns/public/common/common-core-3.xsd


ldapsearch -x -h localhost -p 10389 -D cn=idm,ou=administrators,dc=example,dc=com -w secret -b dc=example,dc=com objectClass=\*

ldapsearch -x -h localhost -p 10389 -D cn=idm,ou=administrators,dc=example,dc=com -w secret -b dc=example,dc=com uid=x000005 \* memberof

# extended LDIF
#
# LDAPv3
# base <dc=example,dc=com> with scope subtree
# filter: uid=x000005
# requesting: * memberof
#

# X000005, people, example.com
dn: uid=X000005,ou=people,dc=example,dc=com
uid: X000005
employeeType: EMP
givenName: Eve
description: Created by midPoint
cn: Eve Morthanic
sn: Morthanic
objectClass: inetOrgPerson
userPassword:: e1NTSEF9SXpTdGxnaHM5WUpCempYZmk0c0t2NldVNkgwdmo0cnNWM0E5TFE9PQ=
 =
memberOf: cn=TerraForming,ou=groups,dc=example,dc=com

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1

ldapsearch -x -h localhost -p 10389 -D cn=idm,ou=administrators,dc=example,dc=com -w secret -b dc=example,dc=com cn=alien-holding-facility-group

# extended LDIF
#
# LDAPv3
# base <dc=example,dc=com> with scope subtree
# filter: cn=alien-holding-facility-group
# requesting: ALL
#

# alien-holding-facility-group, groups, example.com
dn: cn=alien-holding-facility-group,ou=groups,dc=example,dc=com
member: cn=dummy,o=whatever
cn: alien-holding-facility-group
objectClass: groupOfNames

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
KeithsOfficeMBP:mid101 khazelton$

----- LUNCH -----

metaroles can give users accounts (order 2 inducement) in a role that is assigned to them

<!-- This is a meta-role. A Role indented to be assigned to other roles.
     I really mean assigned, not included or induced. -->

<role oid="1568ec1e-36cc-11e6-a052-3c970e44b9e2"
        xmlns="http://midpoint.evolveum.com/xml/ns/public/common/common-3"
        xmlns:c="http://midpoint.evolveum.com/xml/ns/public/common/common-3"
        xmlns:t="http://prism.evolveum.com/xml/ns/public/types-3"
        xmlns:ri="http://midpoint.evolveum.com/xml/ns/public/resource/instance-3">
    <name>LDAP Group Metarole</name>
    <description>If assigning this metarole, role's identifier is group name.</description>

    <inducement>
    	<description>LDAPGROUP-I</description>
    	<construction>
    		<description>LDAPGROUP-I</description>
    		<resourceRef oid="d0811790-1d80-11e4-86b2-3c970e467874" type="c:ResourceType"/>
    		<kind>entitlement</kind>
            <intent>ldapGroup</intent>
    	</construction>
    </inducement>

    <inducement>
    	<description>LDAPGROUP-I2</description>
    	<construction>
    		<description>LDAPGROUP-I2</description>
    		<resourceRef oid="d0811790-1d80-11e4-86b2-3c970e467874" type="c:ResourceType"/>
    		<kind>account</kind>
    		<intent>default</intent>
    		<association>
			<ref>ri:ldapGroup</ref>
			<outbound>
				<strength>strong</strength>
				<expression>
					<associationFromLink>
						<projectionDiscriminator>
							<kind>entitlement</kind>
							<intent>ldapGroup</intent>
						</projectionDiscriminator>
					</associationFromLink>
				</expression>
			</outbound>
		</association>
    	</construction>
    	<order>2</order>
    </inducement>

	<inducement>
		<focusMappings><!-- Generate role description (weak) -->
			<mapping>
				<name>role description</name>
				<strength>weak</strength>
				<source>
					<path>$focus/identifier</path>
				</source>
				<expression>
					<script>
						<code>return 'LDAP Group named: ' + basic.stringify(identifier)</code>
					</script>
				</expression>
				<target>
					<path>$focus/description</path>
				</target>
			</mapping>
		</focusMappings>
	</inducement>


</role>

check expression in pwd policy



_____________________
h6. 2018-02-26 09:00  day 3, week 2   444-392-608
Synchronization is a multi-faceted

Provisioning synchronization

Live synchronization: (near real time, not all systems support this, may miss some changes)
LiveSync (best if you can search for changes)
- Changelog: LiveSync task: Look for changes, sync changes, move pointer to next unprocessed diff; most dir systems, but not OpenLDAP yet
- Timestamp: find oldest processed time; sync based on next one; not for deletes (done by reconciliation)

Reconciliation: scheduled batch check of consistency, all objects processed
- list all resource objects, sync each
- detect shadows that have no corresponding resource object
- push unfinished operations (cached data from Shadow)
- Full vs. incremental (Open JIRA issues, MID-1346)

Import from resource: (pretend accounts were just created)
- iterate over all resource obj
-

Recomputation task: Not resource-specific
- recompute focal objects (users, org, roles, ...)
- if a new mapping rule has been created, this will propagate results across the focal objects

Discovery: Opportunistic reaction to a change discovered during an unrelated operation (e.g. Already Exists)

Configuration of synchronization
- what to do when changes are detected
- start manually or set up a scheduled task (that's when sync happens)

Conceptual flow of Synchronization

- ∂ detected
- kind/intent determined
- correlation/confirmation expressions evaluated
- determine SITUATION
- apply REACTION

- focus type defaults to User; Groups, Orgs, Services, need to set focus accordingly

sync conditions:
- conditions should be mutually exclusive (disjoint)

See wiki entry on Updated Query API

Correlation expressions find, hopefully one, match between User and shadow attributes

for recompute, see query playground and play with examples provided

confirmation expression
- 2nd optional step executed for each candidate user found by the correlation expression
- only useful when there are more than one 'owner' / 'match'
- rarely used

can use change owner in GUI to assign

sync SITUATIONS AND REACTIONS

SITUATIONS: (account and user) linked, unlinked, unmatched, collision, deleted, disputed

unlinked:
deleteShadow (and real account, should replace Shadow with Projection in command name)
inactivateShadow (and real account)

unmatched: account on resource with no known owner; default: mark as unmatched in account lists
collision: rare: account with 2 or more mP users; i.e. service account in wiki (way to do shared accounts)
inactivate Focus (inactivate the Focus in repo)
disputed: correlation rule returns two or more owners

----- BREAK -----

TASKS

Synchronization Tasks
- Reconciliation: batch, one-time, scheduled
- LiveSync: resource change processing, scheduled
- Import from res.
- Recompute

Dry run option for sync: evaluate situations, skip reactions
Task owner: default is Administrator

Task mgmt:

suspend / resume / run now
  - resume does not always mean 'continue', it means rerun from beginning
  - Nodes: which node in cluster runs which task (not covered in mP101) 'node-sticky tasks'
  - cron
  - tightly bound (small scheduling interval, e.g. less than 30 seconds)
  - don't start before/after

resilient tasks, non-resilient tasks (node reboot situation)

checking results:
- server tasks / list tasks <click>: progress info and statistics
- reconciliation report

default system tasks
- cleanup 1/24hr
- trigger scanner 1/5 min
  - evaluate triggers attached to mP objects
  - time-dependent mappings: e.g. delete account 30 days after disabled
- validity scanner 1/15 min recompute effective status and assignments; pushes this value to the accounts

----- Lab 7-1 -----

target completion: 11:25


_____________________
h6. 2018-02-20 09:33  mP Training Day Two

<script xmlns:org="http://midpoint.evolveum.com/xml/ns/public/common/org-3">
<code>

String[] tmpOuPath = []

tmpOuPathDn = ''

for (i = 0; i &lt; tmpOuPath.size(); i++) {
	tmpOuPathDn = ',ou=' + tmpOuPath[i] + tmpOuPathDn
}

'cn=' + givenName + ' ' + familyName + iterationToken + tmpOuPathDn + ',ou=ExAmPLE,dc=example,dc=com'

</code>
</script>

<relativity>absolute means map all values of a multi-value attr. every time any value changes

expressions can only use props in the source plus the built-in expression var's: error: property not found

buit-in vars incl: input, focus, projection, resource properties, operation, actor,
  config, legal, assigned, focusExists, iteration, iterationToken

operations can evaluate at 1st execution time (add, modify, delete)

Mapping options

Authoritative: remove values (def=true):
  provisioning op: not used if target already has a value; not used if user has requested any other change;   used to set default values
  reconciliation op: Only if target has no values


Exclusive 1 mapping for a target property
Channel constraint: <channel> / <exceptChannel> can be used to do only on import; slide 154

Strength:
weak:  used to set default values if none present
normal: (def) applied unless there is a more specific rule;
strong: (always applied, even in reconciliation) used to enforce particular values; strongest with <tolerant>false; will remove things in the target

mid-2070 is gen doc from resource config file

xsd: in distro

midpoint@mp-training:/opt/training/midpoint/doc/schema/xml/ns/public$ ls -la
total 108
drwxrwxr-x 9 midpoint midpoint  4096 Feb 13 14:14 .
drwxrwxr-x 3 midpoint midpoint  4096 Feb 13 14:14 ..
-rw-rw-r-- 1 midpoint midpoint 19665 Feb 13 14:14 annotation-3.xsd
drwxrwxr-x 2 midpoint midpoint  4096 Feb 18 21:42 common
drwxrwxr-x 3 midpoint midpoint  4096 Feb 13 14:14 connector
drwxrwxr-x 2 midpoint midpoint  4096 Feb 18 21:42 gui
drwxrwxr-x 3 midpoint midpoint  4096 Feb 18 21:42 model
-rw-rw-r-- 1 midpoint midpoint 22635 Feb 13 14:14 query-3.xsd
drwxrwxr-x 2 midpoint midpoint  4096 Feb 18 21:42 report
drwxrwxr-x 2 midpoint midpoint  4096 Feb 18 21:42 resource
drwxrwxr-x 2 midpoint midpoint  4096 Feb 18 21:42 task
-rw-rw-r-- 1 midpoint midpoint 27662 Feb 13 14:14 types-3.xsd

----------
module 5

users, accounts, projections
and now
assignments and roles

linked account vs
assignments

what the state SHOULD be; midPoint is an engine to make the state match what it should be

account assignments
  user==>account

role assignments
  create role, assign to user
  can leverage mappings/expressions

orgStructure assignments
  ou membership

use of roles is a best practice;

RBAC enhanced w logic expressions
"Role: Defines a set of access rights for users assigned to the role"

user   ==>       role     ==>   |resource account
    is assigned /    \  induces |role

slides 187...

implied accounts (the induced) accounts for a given role

adminss can request roles (assignments)
end users and admins can request a shopping cart of roles
  -
  - see wiki for Role Catalog

assignmentEnforcementPolicy (global sys config)
 - relative
 - full (?!)  no projected/linked accounts allowed
 2 not used:
 - positive
 - none

 See Wiki: Personas  https://wiki.evolveum.com/display/midPoint/Personas
_____________________
h6. 2018-02-19 09:00  mP Training Day One

Ivan Noris intro

09:00 - Noon: breaks once an hour;
Noon - 13:00: lunch
13:00 - 17:00 more frequent breaks after lunch


Carl Waldbieser, Lafayette: Onboarding is area we want to use midPoint
Dusty, GA Tech: mP Noob; legacy onboarding/provisioning looking to replace
Jeff Clough, GA Tech: looking to replace home-grown app with something like mP; python/postgres/banner/PS since 2005
Jason, UMBC: mP for couple months; want all TIER components
ToddH, UMBC: work w Jason
Randy, CSU: idMgmt since 2000, home grown; integration w SIS, & HR; all userIds issued via Student info system; mP as more complete & advanced solution
Jeff, CSU:
RashedK: Westchester U: mP for IdM to replace patchwork local systems; Grouper & Shib too
SilasK, CO SoMines: looking @ mP as part of CSP
TaylorGrowden, Exclamations.com: partners w Evolveum
KeithH, UW-Msn
JohnK, UC Merced:


12 trainees, 7 campuses, 1 commercial partner. IvanN as instructor:

IN: Like you, Most in HE globally are using homegrown solutions w scripting-based integrations

IAM intro...

2003: 1st iteration of IAM for Slovakian bank (pre-mP); for them, automated user DE-provisioning was the killer feature

mP big pic: https://wiki.evolveum.com; integration is via identity connector plugins on the mP black box, NOT on the external systems
  - Sun Identity Mgr had the same model of plugins on the IAM side
  - vs IBM et al., 'agents' on each connected system; typically requires a restart
  - "our next restart is planned for 5 years from now"

Abstract arch of mP; note interfaces between modules: IDM model is central (policy, decisions, mappings, roles, all biz logic)
  - model connected to (Repo, SQL, LDAP) and to (prov engines-->ConnId-->Resources)
  - UI can be swapped to fit biz cases; interact with IDM model via APIs;
  - workflows can also be layered over same IDM Model APIs
Everything above IDM model can be swapped in/out; IDM Model

User is a 'focal' object supported by mP
  - other focal objects: Organizations, Roles, Services,
  - Account is one of the 'projections' supported by mP

'relative' vs 'absolute' changes: traditional provisioning is 'Absolute' (ACID model)
  - Absoiute: local changes may be overwritten even if there are no real collisions (e.g. multiple pending approvals) SunIdM had this flaw in 2003
  - Relative: mP applies deltas (// to LDAP); no locking necessary; risk to local changes is low; can cache and retry

Simplest mP installation:
  - Java 8
  - RDBMS (Postgres, MariaDB/MySQL, Oracle, SQL Server,.)
  - prep the database (or use embedded H2)
  - download and unzip mP distro archive to ../<mP>
  - start mP w embedded Tomcat
    - <mP>/bin/start.sh
    - Auto initial object import (if not already there)

  - extraction from archive 'installs' mP
    - e.g. /opt/mP/
       or  /opt/training/mP
             ./bin
             ./doc
             ./lib
             ./var
               config.xml/
               keystore.jceks/
               schema/
               icf-connectors/
               localization/
               log/
               logback.xml

  - $midpoint.home/application.yml can override default settings

  - see Evolveum wiki for more

Docker version for Labs: mp-mother (localhost, 192.168.56.101)

mP/mP
http://localhost:18080
reach postgres container on port 15432
reach openldap container on port 10389
http://  :18080
  /opt/training is the Docker volume

eclipse+mP plugin as our mP IDE

Module One Summary

mP Ontology:

Target Systems
Resources
Connectors
Users
Accounts

----------
Module Two: Managing your Customizations

- Best to keep all your Customizations under version control and import them into midPoint.

- can use search results as input to creation of some bulk operations

diff between local and mP deployment
macro expansions at upload time
create, read, modify mP objects

Fixed vs Dynamic OIDs
- mP generates OID automatically when importing objects (UUID)
- you can generate your custom OID and assign it to an object at import time
  - gives you a way to refer to a given, known object with the same OID across deployments
  - must be UUID format/structure

Comments
  <!--   comment block   -->
    - these are stripped before being persisted in repo
  use <description? field which many objects have, those will be preserved in the repo

Passwords
  - encrypted in repo
  - you CAN store clear text password in XML config files
  - on Export, clear text value will not appear

Overlay Project
  customization of source code and default config
  - strt with binary distro: midpoint.war
  - add customized files
  - Repackage
  - contains ONLY the customized files
    - HTML, Images..
    - Initial objects, roles, schemas,...
    - custom initial midPoint home directory
  - see HowTo in the wiki.

midpoint@mp-training:/$ ls -la /opt/training/midpoint-labs/flatfiles

total 24
drwxr-xr-x 2 midpoint midpoint 4096 Feb 18 19:56 .
drwxr-xr-x 4 midpoint midpoint 4096 Feb 18 19:56 ..
-rw-rw-r-- 1 midpoint midpoint  302 Apr 18  2017 csv-1-app-1.csv
-rw-rw-r-- 1 midpoint midpoint   84 Apr 18  2017 csv-2-app-2.csv
-rw-rw-r-- 1 midpoint midpoint  547 Apr 18  2017 csv-3-ldap.csv
-rw-rw-r-- 1 midpoint midpoint 1554 Nov 27 13:39 source.csv

https://wiki.evolveum.com/display/midPoint/Solving+Certificate+Problems  <== for issues installing midpoint dev tools plugin

----------
LUNCH
----------

Module 3

http://github.com/Evolveum/

Create new resource
  - is there a connector?
  - is it bundled w mP? (LDAP, CSV, DBTable in mP 3.7)
    - OrSeparate download
  - custom connector dev.
    -
    - CRUD
    - Test Connection
    -....
    - Search

If you have the connector jar,

- copy to $midpoint.home/icf-connectors
- restart mP nodes

create technical account on target system
  - limit privs to CRUD on accounts
  - Visible in target system logs
log into tech account from mP host to test access to Resource
  - LDAP browser, TOAD, etc.

Create resource

Resource wizard
or
Public samples

See slide 82: https://github.com/Evolveum/midpoint/samples/resources
- Copy/Xform/Reuse
- Better control of your XML




_____________________
h6. 2018-02-18 14:44  working mP Training from oMbP

KeithsOfficeMBP:mid101 khazelton$ sudo docker container ls
Password:
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                                            NAMES
dd98d70f7eeb        ubuntu-mid101:2018.A.docker     "/midpoint-entrypoin…"   36 minutes ago      Up 3 minutes        0.0.0.0:18080->8080/tcp                          mp-training
3c75a81d03aa        postgres-mid101:2018.A.docker   "docker-entrypoint.s…"   36 minutes ago      Up 3 minutes        0.0.0.0:15432->5432/tcp                          mid101_postgres_1
6e41e72364cb        openldap-mid101:2018.A.docker   "/container/tool/run"    36 minutes ago      Up 3 minutes        0.0.0.0:10389->389/tcp, 0.0.0.0:10636->636/tcp   mid101_openldap_1
86f716fe0cc8        registry:2.5.0                  "/entrypoint.sh /etc…"   7 months ago        Up 3 minutes        0.0.0.0:5000->5000/tcp                           registry

KeithsOfficeMBP:mid101 khazelton$ pwd
/Users/khazelton/mid101

KeithsOfficeMBP:mid101 khazelton$ ls -la
total 8
drwxr-xr-x    6 khazelton  staff   204 Feb 18 13:38 .
drwxr-xr-x@ 204 khazelton  staff  6936 Feb 18 14:39 ..
-rw-r--r--    1 khazelton  staff  2195 Feb 18 13:20 docker-compose.yaml
drwxrwxr-x    4 khazelton  staff   136 Feb 18 13:27 mp-openldap
drwxrwxr-x    5 khazelton  staff   170 Feb 18 13:31 mp-postgres
drwxrwxr-x   10 khazelton  staff   340 Feb 18 13:33 mp-training

http://localhost:18080

[mP admin GUI] k窟

- ssh into the docker container
sudo docker exec -u midpoint -it dd98d70f7eeb /bin/bash

midpoint@mp-training:/$ cat opt/training/midpoint/bin/start.sh

#!/bin/sh
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Parts of this file Copyright (c) 2017 Evolveum
#

# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

PRGDIR=`dirname "$PRG"`
EXECUTABLE=midpoint.sh

  if [ ! -x "$PRGDIR"/"$EXECUTABLE" ]; then
    echo "Cannot find $PRGDIR/$EXECUTABLE"
    echo "The file is absent or does not have execute permission"
    echo "This file is needed to run this program"
    exit 1
  fi


exec "$PRGDIR"/"$EXECUTABLE" start "$@"

----------
KeithsOfficeMBP:mid101 khazelton$ sudo docker exec -u midpoint -it dd98d70f7eeb /bin/bash

midpoint@mp-training:/$ ls -la
total 76
drwxr-xr-x   1 root root 4096 Feb 18 20:07 .
drwxr-xr-x   1 root root 4096 Feb 18 20:07 ..
-rwxr-xr-x   1 root root    0 Feb 18 20:07 .dockerenv
drwxr-xr-x   1 root root 4096 Feb 18 19:56 bin
drwxr-xr-x   2 root root 4096 Apr 12  2016 boot
drwxr-xr-x   5 root root  360 Feb 18 20:40 dev
drwxr-xr-x   1 root root 4096 Feb 18 20:07 etc
drwxr-xr-x   1 root root 4096 Feb 18 19:56 home
drwxr-xr-x   1 root root 4096 Sep 13  2015 lib
drwxr-xr-x   2 root root 4096 Jan 23 22:49 lib64
drwxr-xr-x   2 root root 4096 Jan 23 22:49 media
-rwxr-xr-x   1 root root  810 Feb 18 19:33 midpoint-entrypoint.sh
drwxr-xr-x   2 root root 4096 Jan 23 22:49 mnt
drwxr-xr-x   1 root root 4096 Feb 18 19:56 opt
dr-xr-xr-x 207 root root    0 Feb 18 20:40 proc
drwx------   2 root root 4096 Jan 23 22:49 root
drwxr-xr-x   1 root root 4096 Feb 18 19:56 run
drwxr-xr-x   1 root root 4096 Jan 25 18:23 sbin
drwxr-xr-x   2 root root 4096 Jan 23 22:49 srv
dr-xr-xr-x  13 root root    0 Feb 18 20:40 sys
drwxrwxrwt   1 root root 4096 Feb 18 20:41 tmp
drwxr-xr-x   1 root root 4096 Jan 23 22:49 usr
drwxr-xr-x   1 root root 4096 Jan 23 22:49 var

Inside container:

midpoint@mp-training:/$ ls -la /opt/training/midpoint/var/log

total 64
drwxrwxr-x  2 midpoint midpoint  4096 Feb 18 20:07 .
drwxr-xr-x 11 midpoint midpoint  4096 Feb 18 20:08 ..
-rw-rw-r--  1 midpoint midpoint     0 Feb 18 20:07 midpoint-profile.log
-rw-rw-r--  1 midpoint midpoint 49704 Feb 18 21:17 midpoint.log
midpoint@mp-training:/$

midpoint.log

...
2018-02-18 20:41:42,972 [] [main] INFO (com.evolveum.midpoint.web.boot.MidPointSpringApplication): Started MidPointSpringApplication in 63.827 seconds (JVM running for 67.236)
...

_____________________
h6. 2018-02-16 17:24  midPoint Training

From Todd (UMBC) to Everyone: (10:06 AM)
for VirtualBox 5.2, to install the host-only network, I did the following:
https://luppeng.wordpress.com/2017/07/17/enabling-virtualbox-host-only-adapter-on-mac-os-x/
Launch VirtualBox and click on “File > Host Network Manager” on the Menu Bar (Or press “Command” + “W” )
    Click on the “Create” button in the Host Network Manager window
    This will create a host-only network called “vboxnet0”
    Select if you want this Host-only network to have DHCP Server enabled
    Close the Host Network Manager Window

From jason.griego@umbc.edu to Everyone: (10:14 AM)
Looks like getting back to the VirtualBox Host Settings is through Global Tools -> Host Network Manager

From Ivan Noris (Evolveum s.r.o.) to Everyone: (10:15 AM)
Is anyone using Virtualbox 5.1.x ?

From Todd (UMBC) to Everyone: (10:15 AM)
UMBC is at 5.2.6 (Todd / Jason)

From Silas Korb to Everyone: (10:16 AM)
yep I'm at 2+ hours
What if you don't have box or internet2 credentials...

From Me to Everyone: (10:17 AM)
https://internet2.box.com/s/fwogbk7xi599x7ctaa7geajdz2d15qbf

From Matthew Brookover to Everyone: (10:19 AM)
With MacOS, virtual box 5.2, Todd’s suggestion to use FIle-> host network manager worked.  I am logged in as midpoint@mp-mother!

From Todd (UMBC) to Everyone: (10:20 AM)
excellent

Matthew: yep that's good
To check midpoint is running:
go to http://192.168.56.101:18080
This is midPoint GUI (docker container accessed through virtualbox)

From Paul to Everyone: (10:22 AM)
does midpoint auto-start when the VM does?

From Todd (UMBC) to Everyone: (10:22 AM)
It did for me

Paul: yes

From Me to Everyone: (10:25 AM)
just resent your invitation Jeff for our Slack

From Silas Korb to Me: (Privately) (10:26 AM)
Bill I signed up for box, but when I use your link it says that shared file or folder has been removed or is unavailable to me
looks like I've only got about 20min left on the download from evolveum though

From Todd (UMBC) to Everyone: (10:27 AM)
Successful here (to see midPoint via browser)

From Matthew Brookover to Everyone: (10:28 AM)
I was able to get the midPoint login screen at http://192.168.56.101:18080 — took a while for it to paint — my mac book is old and slow :-)

From Paul to Everyone: (10:30 AM)
slow, but I'm in

From Ivan Noris (Evolveum s.r.o.) to Everyone: (10:32 AM)

midPoint GUI: localhost:18080
User: administrator; Password: 5ecr3t

openLDAP:
DN: cn=admin,dc=example,dc=com
pass: secret

From Todd (UMBC) to Everyone: (10:37 AM)
yes

From jason.griego@umbc.edu to Everyone: (10:37 AM)
I have midpoint fully running on mac

From Martin Heck to Everyone: (10:37 AM)
I've got it imported, and booting up now

From Matthew Brookover to Everyone: (10:37 AM)
I got the materials from the evolveum site.
I am logged in as administrator on the web interface.

From Todd (UMBC) to Everyone: (10:38 AM)
seems common that people are successful using the evolveum site.  Not sure anyone has been successful downloading from Box

From sguha to Everyone: (10:39 AM)
MD5 checksum from Box
5f0bea94829b4758112959b29c8f6b95

From Matthew Brookover to Everyone: (10:39 AM)
On a Mac:
[mbrookov@myrddin midPoint-Class]$ md5 MidPoint\ Training\ Centos7.ova
MD5 (MidPoint Training Centos7.ova) = 5f0bea94829b4758112959b29c8f6b95
[mbrookov@myrddin midPoint-Class]$

From sguha to Everyone: (10:39 AM)
yes


From Paul to Everyone: (10:39 AM)
I dloaded from Evolveum as well and was successful

From Dean (Rice) to Everyone: (10:42 AM)
I was able to start the virtual machine: Mac OS 10.13.2, Virtual Box 5.2.6, using the ova from Evolveum.  No problems.

From jason.griego@umbc.edu to Everyone: (10:47 AM)
Successful, exact same setup as Dean.

From Me to Everyone: (10:54 AM)
I am uploading the image to a new server and once it is uploaded you should receive an email

From Matthew Brookover to Everyone: (10:56 AM)
I have MacOS 10.13.3, virtual box 5.2.6 turned off USB and every thing seems to be working.

From Ivan Noris (Evolveum s.r.o.) to Everyone: (10:57 AM)
the OVA file format seems to be ordinary TAR... but again on windows it's probably not expectable to test the archive...

From sguha to Everyone: (10:57 AM)
The download from Box has an ovf extension. The other one has an ova extension.

From Ivan Noris (Evolveum s.r.o.) to Everyone: (11:00 AM)
actually .ova contains also the .ovf file

From sguha to Everyone: (11:02 AM)
Seems to be working if you change the extension to ova

From Paul to Everyone: (11:02 AM)
seems like pulling some containers from a repo and doing a 'docker-compose up' might've been a little easier than wrestling with VirtualBox VMs  (a thought for next time)   :)

From Silas Korb to Everyone: (11:08 AM)
mine's up and I'm into midpoint

From Todd (UMBC) to Everyone: (11:17 AM)
Set up the host based network: https://luppeng.wordpress.com/2017/07/17/enabling-virtualbox-host-only-adapter-on-mac-os-x/

From Ivan Noris (Evolveum s.r.o.) to Everyone: (11:24 AM)
ssh midpoint@192.168.56.101
sudo docker container ls

From Silas Korb to Everyone: (11:26 AM)
so today is just to get the VM up and running, correct?
oh perfect, I'll see you Monday then!

From Martin Heck to Everyone: (11:27 AM)
Thank you! I'm good to go as well.

From Ivan Noris (Evolveum s.r.o.) to Everyone: (11:28 AM)
ivan.noris@evolveum.com

From John Kamminga to Everyone: (11:35 AM)
ok, i'm good. see you on monday! happy friday

From Dusty Edenfield to Everyone: (11:36 AM)
Georgia Tech is good.  See you on Monday.

Best regards
--
Bill Kaufman
Senior PM – Integration & Architecture
Internet2
O - (734) 352-7086 | M - (734) 323-8623

cd /var/lib/docker/volumes/mid101_midpoint-volume/_data/midpoint/var/log | less midpoint.log
