=== tiMPenvLaunch.adoc

- - -
_2019-01-17 12:04 bare CentOS to mP Complex demo_

install docker and docker-compose per https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-compose-on-centos-7

captured copy of disk at this stage: Linode co-op.tech CentOS 7 2017-01-17

```
$ sudo firewall-cmd --zone=public --add-port=15672/tcp  <= open RabbitMQ admin port

$ sudo firewall-cmd --zone=public --list-services
ssh dhcpv6-client http

$ sudo firewall-cmd --zone=public --list-ports
58263/tcp 15672/tcp

$ service firewalld restart

```
- - -

Edit IdP and SP metadata to change endpoints from localhost to actual host dns name

vim ${MIPOINT_HOME}/demo/grouper/configs-and-secrets/*grouper*/shibboleth/idp-metadata.xml +
:%s/localhost/${HOST_DNS_NAME}/g +

vim ${MIPOINT_HOME}/demo/grouper/configs-and-secrets/*midpoint*/shibboleth/idp-metadata.xml +
:%s/localhost/${HOST_DNS_NAME}/g +

vim ${MIPOINT_HOME}/demo/grouper/idp/shibboleth-idp/metadata +
:%s/localhost/${HOST_DNS_NAME}/g

vim ${MIPOINT_HOME}/demo/grouper/idp/midpoint-sp.xml

vim ${MIPOINT_HOME}/demo/grouper/idp/mlgrouper-sp.x

```
cd opt/midPoint_container/demo/complex/configs-and-secrets/grouper/shibboleth
vim idp-metadata.xml
:%s/localhost/co-op.tech/g

cd opt/midPoint_container/demo/complex/configs-and-secrets/midpoint/shibboleth
vim idp-metadata.xml

cd opt/midPoint_container/demo/complex/idp/shibboleth-idp/metadata
vim idp-metadata.xml

```

install complex demo per https://spaces.at.internet2.edu/display/MID/Complex+midPoint+integration+demo

```
$ cd /home/khazelton/opt
$ git clone --branch v1.1 https://github.internet2.edu/TIER/midPoint_container.git
$ cd midPoint_container
$ ./build.sh
$ cd demo/complex
$ docker-compose up

```

- - -
_2019-01-16 13:51 from bare CentOS 7 Linode (co-op.tech) to running complex demo_

create khazelton and scott as wheel group members

copy over their respective public keys to /home/{UID}.ssh directory with 644 permissions
```
scp .ssh/kh_rsa.pub root@co-op.tech:
```

configure ssh to accept cert-only authN, change port to 58263

- - -
_2019-01-16 13:50 references and links_

https://www.tecmint.com/18-tar-command-examples-in-linux/
