=== tiPack.adoc  http://bit.ly/1XNvSmC    JimJ: 434-825-1415
http://bit.ly/1XNvSmC <= notes +
https://spaces.at.internet2.edu/display/ITAP/InCommon+Trusted+Access+Platform+Release <= TAP Release/Download page

- - -
_2020-07-03 08:50 chat w TomJ, JillG_

https://teams.microsoft.com/l/meetup-join/19%3ameeting_YjNkNGVhNzMtMjlkNi00NjEyLTlkN2UtY2E5ODk2NmYzMGE4%40thread.v2/0?context=%7b%22Tid%22%3a%222ca68321-0eda-4908-88b2-424a8cb4b0f9%22%2c%22Oid%22%3a%2293280aab-dec5-40e7-8947-619f51094252%22%7d

Feedback loop between the Software Integration group +
and the community (via CACTI) +
with regard to Trusted Access Platform packaging +

- - -
_2018-06-19 15:25_

https://docs.google.com/document/d/17-0O3Tvty9PONL6wu4PiC6ZWramdyntXmOsq1UpD2tE/edit  <== latest shib IdP container H/T Paul Caskey

- - -
_2018-06-04 15:00  TIER-Packaging WG call_

We will hold a TIER Packaging call this afternoon at 4:00 eastern.
Logistics:  Zoom Meeting Id: 734 323 8623
                  https://internet2.zoom.us/j/7343238623?pwd=xX4V7ZJlCzg

We have several agenda topics for today.  Some are focused around decisions we made earlier in the project and if we can/should make changes while others relate more directly to midPoint and other components.

1) The use of Oracle JAVA for all components
2) The use of supervisord for multi-process components; progress on supervisord and logging
3) midPoint – priorities for Shibboleth and messaging; other discussion on plans for the container build
4) Grouper – status of containers; production, JAVA (see above)?
5) catch up on other action items/topics

The full agenda will be on-line later this morning
https://docs.google.com/document/d/1_jfdZpzCLxV2WTgCjMY3FZMuGGV67QvkLzkEtwLayGM/edit

- - -
_2018-06-01 08:39  Evolveum mP container  https://docs.google.com/document/d/1PQuMamR_-Nrzq9OMjCJ19Fw1hcdTim1W3mcIUt0z9oxs/edit#heading=h.q5k3ybfi9v3d

From William Kaufman to Everyone: (08:00)
notes https://docs.google.com/document/d/1PQuMamR-Nrzq9OMjCJ19Fw1hcdTim1W3mcIUt0z9oxs/edit?usp=sharing

From Jim Jokl to Everyone: (08:26)
https://spaces.internet2.edu/display/TPWG/TIER+midPoint+-+Docker+Reference+Implementation

powershell scripting connector

outbound messaging connector: Inbound interface for messaging same as SOAP and REST

- - -
_2018-01-22 15:04  midPoint packaging_

The focus for today’s call is continued discussion on midPoint packaging requirements.

Action Items

- Ethan will add information on evolveum mailing list to TIER slack channel [AI]
	https://wiki.evolveum.com/display/midPoint/Mailing+Lists
- Ethan will check on midPoint upgrade process [AI]  - See minutes for detailed questions (database/code mismatch,
	handling upgrades, URL, etc.)

- TIER midPoint Docker Deployment - Large Production

- midPoint and user self service?

  - Ethan - have not really worked in this area
  - Shibboleth SP as part of build (put midPoint behind an SP)?  Ethan - should not be real hard to put this together.
    It may be as easy as placing the EPPN in REMOTE_USER.  Ethan will try to prototype.
  - Can we externalize user self service? https://wiki.evolveum.com/display/midPoint/Self+Services

midPoint and Training

- What should we request of evolveum re: the upcoming TIER midPoint training scheduled for the end of February
  - asks what they plan to bring container-wise
  - which version

- What do we already know midPoint is providing

- Their usual training topics

- Evolveum will provide a TIER Docker image for each Major version

Docker compose that will create a swarm for each of the 4 major components

] test the WS apis

any in-person trainees?
ivan is trainer?
openness to a full final day on connectors

- - -
_2017-12-18 16:04  Packaging archives_

virtualBox instructions:
https://spaces.internet2.edu/display/TPD/Shibboleth-IdP+Virtual+Machine+Documentation

https://docs.google.com/document/d/1atr9X0HhXlH9rIilcmjo14p8TeROX9SFIDFYfp-fZ88/edit#heading=h.ffb4lovkg5ua  <==levell status

https://docs.google.com/document/d/1R_DtHCo9mSkDBMEMMQHYn12fEzi14XgvUfUQeX0uIFE/edit# <== TIER phase 2 weekly project cadence scribing doc

- - -
_2017-12-18 15:16  Packaging call: midPoint_

minimal package for midPoint:

mP, OpenLDAP, mySQL, RabbitMQ

https://spaces.internet2.edu/display/TPWG/TIER+midPoint+Docker+Deployment+-+Large+Production

https://github.internet2.edu/docker/grouper_noVM/tree/multi-purpose-grouper-image  <== Versatile Grouper Container latest

- - -
_2017-12-04 15:16  Packaging call_

https://github.com/containous/traefik

Træfik (pronounced like traffic) is a modern HTTP reverse proxy and load balancer made to deploy microservices with ease. It supports several backends (Docker, Swarm mode, Kubernetes, Marathon, Consul, Etcd, Rancher, Amazon ECS, and a lot more) to manage its configuration automatically and dynamically.

https://www.katacoda.com/courses/traefik/deploy-load-balancer  <== starter demo

- - -
_2017-08-07 13:16  Packaging call_

https://github.com/Internet2/comanage-registry-docker  <== as a model for midPoint docker appliance

- - -
_2016-12-28 18:06 references and links_

https://blog.bitsrc.io/monorepo-architecture-simplified-with-bit-and-npm-b1354be62870  <== easy monorepos
https://testbed.tier.internet2.edu/secure/
https://spaces.internet2.edu/display/TPD/Shibboleth-IdP+Virtual+Machine+Documentation
  - virtualBox instructions:
https://docs.google.com/document/d/1R_DtHCo9mSkDBMEMMQHYn12fEzi14XgvUfUQeX0uIFE/edit#
  -  TIER phase 2 weekly project cadence scribing doc
https://opensource.com/tags/containers

_____________________
h6. 2016-12-12 17:30  levvel.io on DevOps for TIER

https://github.internet2.edu/docker

Bill Kaufman
BK
https://docs.google.com/document/d/1GLvCHgBBfWVTKsqnziIm3jzDuBQu421n7V9fp20snQ0/edit?usp=sharing
https://docs.google.com/document/d/1OSnASvMxbCm3GXXkJd46zGzphk4fv-tpak7RK-czCy8/edit
Jim Van Fleet
JF
Yup, questions can go here!
If people want to share I2 GitHub usernames in here, I can make sure they have access as well as we go.
Christopher Hubing
CH
bill can you record this?
Bill Kaufman
BK
got it
Christopher Hubing
CH
thx!
Nick Roy
NR
There seems to be feedback on someone's mic.
Guest 1
G1
Bill what are the GitHub repository URLs?
Christopher Hubing
CH
https://github.internet2.edu/orgs/docker/dashboard
Bill Kaufman
BK
They are within the Internet2 GitHub which requires manual account provisioning
Guest 1
G1
I don't believe I have an account on the I2 Enterprise GitHub. Should I have one?
Nick Roy
NR
@Jim, I'm nroy@internet2.edu in I2 GitHub
Bill Kaufman
BK
I see you as a guest - who is this?
Jim Van Fleet
JF
https://jenkins.testbed.tier.internet2.edu/
Guest 1
G1
This is Scott Koranda. I don't believe I have an account on the I2 Enterprise GitHub. Should I have one?
Chris Hyzer
CH
Chris Hyzer just emailed techsupport@internet2.edu to request an I2 github account... hope thats the right procedure
Nick Roy
NR
Please add me to access to this repo.
Bill Kaufman
BK
Yes Chris
I will submit one for you Scott
Chris Hyzer
CH
Bill can you submit one for me too (chris hyzer)?  i2 support responded that you or Nick should submit a request.
Bill Kaufman
BK
ok
Nick Roy
NR
Thanks!
I'll volunteer
Jim Van Fleet
JF
https://jenkins.testbed.tier.internet2.edu/job/docker/job/packer-centos-7/ creates appliances
Nick Roy
NR
Should we be talking to TSG to to get a VM in their farm, for the worker?
Paul Caskey
PC
wont run on a VM, we tried
Nick Roy
NR
Bummer
Paul Caskey
PC
needs a physical box
Nick Roy
NR
Should we get some production metal for the MARC data center?
Paul Caskey
PC
yes
I've discussed with MikeL, but he may not know this as "the build worker", probably as 'the PITA physical machine Paul and Bill needed'
Jim Van Fleet
JF
----------------BUILD SUCCESS: Appliance build success. docker/packer-centos-7/comanage-production 39 (Open)[4:24]  ----------------Found comanage-appliance-centos7-ova-1481143641.tar(https://s3-us-west-1.amazonaws.com/internet2-tier-appliance-us-west-1/comanage-appliance-centos7-ova-1481143641.tar)e65b52781975c45c4f4b6a9b372bb3cb builds/comanage-appliance-centos7-ova-1481143641.tarPublishing ami-c3d88fa3 to all accounts
Bill Kaufman
BK
Jeff said he can get a box once we have the final requirements
Guest 1
G1
Is that sharing to my AWS account automated or something a human has to do at the end of the process?


Deprecating the "X-" Prefix and Similar Constructs in Application Protocols
_____________________
h6. 2016-12-09 13:38  TIER project weekly cadence
_____________________
h6. 2016-11-18 13:27  current vms for Shib IdP, Grouper, COmanage

https://spaces.internet2.edu/x/qAjcBQ  <== Shib IdP VM, R2, V5
https://spaces.internet2.edu/x/CoJFBg  <== COmanage R2
https://docs.google.com/document/d/1B8iL8Vm50BbJ4-HaoqjzXrlxa-oiDZpEhvtiQfa7y44/edit?usp=sharing  <== Grouper Appliance
  daemon doesn't auto-start

https://testbed.tier.internet2.edu/secure/download_vm/  <== where to get them when they're done

_____________________
h6. 2016-11-02 13:14  Shib IdP package testing

https://testbed.tier.internet2.edu/secure/download_vm/
https://testbed.tier.internet2.edu/secure/download_vm/TIER-ShibIdP-R2-V4.ova
https://spaces.internet2.edu/x/qAjcBQ  <== Shib IdP Virtual Machine release notes


_____________________
h6. 2016-08-22 15:00  P&C CCall

https://wiki.shibboleth.net/confluence/display/IDP30/SecurityAndNetworking  <== ScottC calls this the bible: all you need to know about crypto in Shib (if you understand crypto)

_____________________
h6. 2016-07-06 12:30  P&C ccall

Action Items
1)	TIER team to provide Shib configuration trees, one for use during local and integration testing, and another with which to seed the appliance. (Needed ASAP. Without this we will not be able to incorporate them into the design document due Tuesday Jul-12)
Regarding this engagement

The TIER team has provisioned the email address tier-pack-shibidp@internet2.edu to facilitate discussions and provide clear communication channels across teams.  Levvel staff has been added to this email group.

A build pipeline that capably delivers a variety of potential appliances (e.g. VirtualBox, VMWare, AWS AMI) is to be preferred to focusing specifically on Docker and its compatibility.

Shibboleth IDP General Information
The publishers of the Shibboleth IDP package, the Shibboleth Consortium, is a third-party group, though there is some common membership with TIER.  They release software roughly twice a year.  On occasion, there are security patches that prompt official releases.

The Shibboleth IDP releases can be acquired from Nexus, their build repository.  Official releases[1] and periodic builds[2] are both available from that repository.

TIER expectation is that, in time, it will evaluate a weekly build of the Shibboleth IDP appliance, including manual testing that supplements the automated testing our build pipeline conducts.  For now, since the appliance that contains the official release is the only one that will be distributed publicly, we will focus on that trigger and source location.

While the TIER group has taken responsibility for the appliance-based distribution of Shibboleth IDP software, TIER has the opportunity to set expectations regarding the timing of those releases.  For example, the appliance may be available one week after the official release, or one month.

The actions necessary to publish appliances and to notify interested parties of newly available appliances is to be determined at a later date.

The TIER team has found that every file in the Shibboleth IDP root directory might require changes during its operational life under an end user’s control.  This requirement is certainly active during the initial configuration period.  Certain changes may require a rebuild of the WAR file that the Shibboleth IDP service deploys.  While there is a possibility that discussions elsewhere may relax this requirement in time (e.g. by concentrating end user configuration changes into a single configuration directory), our efforts this summer will meet the requirement as stated.

The TIER group is an advocate for the Shibboleth IDP software, and may, in time, alter or amend the official releases.  They will not do so within the timeline of this engagement.

The Shibboleth IDP appliance (and the container therein) will contain a default configuration.

Shibboleth IDP Configuration

TIER will provide Levvel with two configuration trees, one for use during local and integration testing, and another with which to seed the appliance.

There is currently no plan to require additional configuration trees, nor to include an appliance containing additional configurations as a deliverable.  It’s possible that, if additional configurations are ultimately considered desirable, those configurations may be delivered as follow-on work.  One example here would be a configuration that supports only integration with Active Directory.

When available, the configuration trees will be made available on one of the testbed machines provisioned previously by I2/TIER to which Levvel principals have previously confirmed connectivity.


[1] https://build.shibboleth.net/nexus/content/repositories/releases/net/shibboleth/idp/idp-distribution/3.2.1/
[2] https://build.shibboleth.net/nexus/content/repositories/snapshots/net/shibboleth/idp/idp-distribution/


_____________________
h6. 2016/06/19/ 06:01 references and links

http://neuro.debian.net/vm.html  <== ++ nicely done vbox vm getting started page
_____________________
h6. 2016-05-23 07:40  Packaging CCall

Everyone,

The agenda for our Monday call will focus on (a) feedback on the Shibboleth container VM and (b) requirements for local campus metadata management.   If you have not yet tried the Shibboleth VM, this might be an opportunity to get started.

The link to getting started on the Shibboleth IdP VM is in our running agenda from our May 2 call:  http://bit.ly/1XNvSmC

The start of the work on requirements for campus metadata management is in our running agenda from our May 9:  http://bit.ly/1XNvSmC

Thanks, Jim
_____________________
h6. 2016-05-03 14:48  JimJ chat re Midpoint

Main concern re Midpoint: All the back chatter is around COmanage as registry;
_____________________
h6. 2016-04-18 12:41  VM Images

https://www.virtualbox.org/wiki/VirtualBox
https://testbed.tier.internet2.edu/

https://spaces.internet2.edu/display/TPD/Shibboleth-IdP+Virtual+Machine+Documentation
Look at release notes

IP for Shib  VM: 10.0.2.5; 192.168.1.233
  ==> look for eth0 entry

  Replace or remove this logo
Web Login Service - Stale Request
You may be seeing this page because you used the Back button while browsing a secure web site or application. Alternatively, you may have mistakenly bookmarked the web login form instead of the actual web site you wanted to bookmark or used a link created by somebody else who made the same mistake.

Left unchecked, this can cause errors on some browsers or result in you returning to the web site you tried to leave, so this page is presented instead.

- sent email to tier-pack

_____________________
h6. 2016-04-18 15:00  Packaging CCall

I’m expecting a short call for today.  Our agenda will focus on:
  (a) Status update on the packaging work (Docker and VMs)



  (b) Initial testing/feedback on the COmanage VM


_____________________
h6. 2016-03-28 15:00  Packaging CCall

We will hold a very brief call today to discuss status and work in progress.

- AWS build env available; Shib IdP underway
- Levvel.io contracted to help get COmanage containerized
- then Grouper
- sep containers for each component and sub-Component
Δ Default config work underway (via builds)
Δ THEN containerization
_____________________
h6. 2016-02-29 15:18 Tier Packaging

mySQL (community edition or MariaDB (open-source fork of MySQL when Oracle bought it))

IdP proxy is becoming part of the standard architecture; based on pySAML2 from sunet; they have a COmanage plugin available
_____________________
h6. 2016-02-15 14:46 Tier Packaging  http://bit.ly/1XNvSmC

[MACE-Dir] Challenge" eduPerson is rarely implemented in institutions' AD deployments
_____________________
h6. 2016-02-01 15:00  Tier packaging 012 5971# http://bit.ly/1XNvSmC

Today's Agenda is below.  If you have  time before the call, please try to
look at #2 below.

1.Quick review of 1-25-2016 meeting notes

2.Packaging Proposal Discussion - see: https://spaces.internet2.edu/x/6QqVBQ

ScottyL: Likes CoreOS
puppet creates VMs
packer drives puppet
it's all automatewd, could rebuild every single day

clear distinction between VMs and appliances;
take out the package manager on the appliances; ChPh: devils in the details.


3.Shibboleth default configuration and ease of use - see survey: https://spaces.internet2.edu/x/CwuVBQ
_________
h6. 2016-01-25 15:00  Tier packaging 012 5971# http://bit.ly/1XNvSmC
_____________________
h6. 2015-12-21 15:00  Tier packaging 012 5971# http://bit.ly/1XNvSmC
_____________________
h6. 2015-12-14 15:00  Tier packaging 012 5971#
_____________________
h6. 2015-11-23 15:00  Tier packaging 012 5971#

Recall that our initial WG focus is to determine the set of questions we need answered before we can move forward.

In preparation for today’s call, please try to look at, add to, comment on, and/or edit the work that the section volunteers have started for the three components and the Core Packaging work.  The Component Sections focus on the components themselves, default configurations, dependencies, tool needs, etc., and not (to the extent possible) the execution environment.  The Core Packaging section is being used to capture the data that we need to know to determine appropriate execution environment(s).

https://docs.google.com/document/d/1_jfdZpzCLxV2WTgCjMY3FZMuGGV67QvkLzkEtwLayGM/edit

Please also think about the Audience question for each of the four topic areas.  Deliverable #1 is to document an appropriately diverse set of places/schools/etc. for the survey/outreach that we are developing now.

Thanks, Jim

http://12factor.net/  <== 12 factor app
