<<<<<<< HEAD:_TI/tiProv.adoc
=== tiProv.adoc ISL https://todos.internet2.edu/secure/RapidBoard.jspa?rapidView=147&view=detail
- - -
_2020-09-22 13:38 Sympa Provisioning and Connector_

https://todos.internet2.edu/browse/ISL-22  Sympa Connector for midPoint

EthanK: Grouper flow from collab stem to org to resource

Create Sympa templates, in creating lists, indicate the template of choice and populate three LDAP groups: All, Owners, ListName (maybe Moderators) folder is list name, all and owner are groups within the list folder
See Albert's proposal:

Sympa
  InCommon
    inctrust-si
  Internet2
    fddd

Connector needs only *create* and *close* operations

Collab resources managed in Grouper

Two resources since we have two domains I2 and InC so SOAP URL paths will differ

- - -
_2020-07-02 12:24
=======
=== tiProv.adoc
- - -
_2020-07-02 12:24 
>>>>>>> 8f5f089acf5147b87443c805af8f3cf8ad7eba1e:_TI/tiProv.utf
- - -
_2020-05-29 15:56 provisioning capability_

] serverless (see aws.adoc) + message-updated driver for a full NRT cache of SoR

- - -
_2019-01-28 12:20 mP / Grpr / LDAP_

Turn off admin privs in mP to prevent mP-side changes to roles, orgs

- - -
_2017-12-05 15:28  diagrams in Lucidchart: Keith/TomJ_

https://www.lucidchart.com/documents/edit/a7596396-5885-4048-b43f-9c9d66166e84/0?shared=true&

- - -
_2017-07-28 16:27  SCIM to Slack_

https://api.slack.com/apps
https://api.slack.com/apps/A6F7CQRGB  <== scim-prot

App Credentials
These credentials allow your app to access the Slack API. They are secret. Please don't share your app credentials with anyone, include them in public code repositories, or store them in insecure ways.

Client ID
7112101013.219250841555

Client Secret
e6b7902f00f7f8550cc0d9fd9c4f7417

You'll need to send this secret along with your client ID when making your oauth.access request.

Verification Token
Gh7lUpGNsUwsu504xSzRMk8g

For interactive messages and events, use this token to verify that requests are actually coming from Slack. Slash commands and interactive messages will both use this verification token.
Display Information

This information will be shown in the Slack App Directory and in the Slack App
For more information, view our App Detail Guidelines.

App name
scim-prot

Short description
Exercises the SCIM API to manage Slack users and groups

Background color
#777777


https://api.slack.com/scim/v1/ServiceProviderConfigs

{
  "authenticationSchemes": [
    {
      "type": "oauthbearertoken",
      "name": "OAuth Bearer Token",
      "description": "Authentication Scheme using the OAuth Bearer Token Standard",
      "specUrl": "http:\/\/tools.ietf.org\/html\/draft-ietf-oauth-v2-bearer-01",
      "primary": true
    }
  ]
}

- - -
_2017-07-27 20:24 scim_

https://www.gartner.com/doc/3554117/scim--it-solve-saas

- - -
_2017-07-07 14:48  BillT's forward leanings_

My pleasure. :)

A common provisioning architecture with lots of supported targets continues to be a blocker to more wide spread TIER adoption. I’m hopeful we can continue to push on that.

By and large folks still need to implement their own mechanisms to get provisioning done. Grouper will get a lot more adoption if in addition to the common strategy based on the deployment guide, there was an ever growing set of connectors. For that to happened in a scalable and timely way, I think we need to enable the community of adopters to build the connectors. Which is happening right now to some extent…they just aren’t easily shared since we lack common architecture.

The Grouper project does a good job of providing many options for deployers. However, for the TIER schools, there still is a lot of opportunity to move towards a more common deployment configuration/architecture.

Imagine a world where TIER came not just with Grouper, but also with the provisioning architecture/tools and a dozen or so of the most common provisioning targets. This might enable schools to justify adopting TIER for a single cloud-based application deployment and then over time scale it to the rest of their identity infrastructure.

Carl’s (Lafayette’s) RabbitMQ/Python based system may not be the best or work for everyone…but at the very least, I think it is directionally correct, consistent with the deployment guide, and lends itself to bundling along side Grouper, perhaps in a TIER Access Governance[1] package.

Best,
Bill

[1] https://www.cso.com.au/article/610140/simple-explanation-access-governance/

----------
On Jul 6, 2017, at 8:26 PM, Ann West <awest@internet2.edu> wrote:

Thanks Bill!!

Ann
----------
From: The EDUCAUSE Security Constituent Group Listserv <SECURITY@LISTSERV.EDUCAUSE.EDU> on behalf of Bill Thompson <thompsow@LAFAYETTE.EDU>
Reply-To: The EDUCAUSE Security Constituent Group Listserv <SECURITY@LISTSERV.EDUCAUSE.EDU>
Date: Thursday, July 6, 2017 at 9:43 AM
To: "SECURITY@LISTSERV.EDUCAUSE.EDU" <SECURITY@LISTSERV.EDUCAUSE.EDU>
Subject: Re: [SECURITY] Process for handling web-based account management

Yes, I think we’ll know Grouper/TIER provisioning has succeeded when the community is actively sharing/maintaining provisioning plug-ins based on a standard architecture. There has been quite a bit of work on the Grouper messaging front lately, which gives one hope that we are getting closer to a place when enough deployments have converged to make this possible.

Carl Waldbieser has been pushing Lafayette’s provisioning code and grouper tools to GitHub here:
https://github.com/cwaldbieser/grouper_tools
https://github.com/cwaldbieser/grouper_python_provisioner

So far we have provisioners for:
* O365 (via the graph api)
* BoardEffect
* Slack
* Zimbra distribution lists
* LDAP (supports a whole host of services via ldap and saml)
* remote shell provisioner (targets systems with ssh access for authorization management)

The system makes it easy to add any remote/rest/web api based target.

We are planning on sharing more details about the system at the Internet2 Tech Exchange in October:
https://meetings.internet2.edu/2017-technology-exchange/program-guide/tutorials/#Grouper

Best,
Bill

----------
On Jul 5, 2017, at 9:26 PM, Mark Poepping <poepping@CMU.EDU> wrote:


Is anybody sharing the specific code for integrating with the various cloud-based API’s (and where)?  Seems that could be relatively generic if we’re sharing the same data model (or most of it at least) via a set of common tech (aka Grouper).
Thanks.
Mark.
----------
From: The EDUCAUSE Security Constituent Group Listserv [mailto:SECURITY@LISTSERV.EDUCAUSE.EDU] On Behalf Of Bill Thompson
Sent: Wednesday, July 05, 2017 12:34 PM
To: SECURITY@LISTSERV.EDUCAUSE.EDU
Subject: Re: [SECURITY] Process for handling web-based account management

We’ve been having some success with using Grouper to control both remote account and authorization/group management. Insitutional cohorts and account/authorization policy are defined and managed in Grouper. Remote (i.e. Cloud systems) are kept in sync via a messaging system based on RabbitMQ. The overall strategy is described in more detail in the TIER Grouper Deployment Guide https://spaces.internet2.edu/display/TI/TI.25.1.

Best,
Bill Thompson
Director Digital Infrastructure
Lafayette College

- - -
_2017-05-01 11:15  skype w BillT_

Grouper Training musings

Carl & RabbitMQ;

- - -
_2016-08-23 19:53  Grouper to manage policies, Spring Security to implement the_

Simple Attribute-Based Access Control with Spring Security - DZone Performance.pdf retrieved from

https://dzone.com/articles/simple-attribute-based-access-control-with-spring?edition=202663&utm_source=Daily%20Digest&utm_medium=email&utm_campaign=dd%202016-08-23

- - -
_2016/07/07/ 14:00 skype chat w Bill Thompson_

- Start w terminology/functional model

- Next week's CIC IdM F2F discussion about forming a Provisioning WG

BT: 1st priority: TIER-guided Grouper deployment
  - Start w Columbia Deployment Guide
  - review, update with community of
  - Group to collaborate on a starting doc for review @ tech ex; pub by year-end
  - HappyBoy arch is working @ Lafayette thanks to Carl; but does it look good for governance & policy
     - recommendations on deployment-
     - use cases, capabilities
     - self-enlightened interest (DalaiLama book) business ethics

- - -
_2016/07/07/ 12:14 references and links_

TI.25.1-TIERGrouperDeploymentGuide.pdf
20160926-hyzer--grouper-provisioning.pdf
https://spaces.at.internet2.edu/display/Grouper/Grouper+Provisioning:+PSPNG
https://www.lucidchart.com/documents/edit/a7596396-5885-4048-b43f-9c9d66166e84/0?shared=true&
https://dzone.com/articles/simple-attribute-based-access-control-with-spring?edition=202663&utm_source=Daily%20Digest&utm_medium=email&utm_campaign=dd%202016-08-23
Simple Attribute-Based Access Control with Spring Security - DZone Performance.pdf  <== Match this with Grouper-managed policies
