=== tiSchema.adoc
- - -
_2020-04-09 20:08 Internet2 enterprise github, new api-schema organization_

Keith Hazelton  15:55
So API wasn't availalble, Next best I could think of was api-schema

15:55
it's created and I'm inviting this crew

Benn Oshrin  16:01
Can we sue for ownership of API and assert trademark infringement? :slightly_smiling_face: (edited)

Keith Hazelton  16:02
It must be someone in Internet2.  Shocking
16:03
I created a Team, api-schema/dev and put everyone but BillK. @wkaufman do you have an enterprise Github account? Can't find you there
16:04
BennO, Paul, and Ethan should all have rights in this org. I made BennO co-owner and gave Bill's email as organization contact

Bill Kaufman  16:05
wkaufman

Keith Hazelton  16:05
ok
16:07
@wkaufman You're in, on the Dev team and co-owner of the api-schema org

cb32af3ce7b9d96dcda6e37fc9d96081c3bf5fef <= access key for push via https, enter as pwd when

- - -
_2019-08-01 21:08 GUID are unrestricted case sensitive strings_

oneroster-v11-final-specification#_ftn1

[1] The format of the GUID is an implementation specific decision i.e. it is NOT restricted to the 128-bit form of a Universal Unique Identifier (UUID).

- - -
_2018-08-23 18:48  improved schema processes in IAM administration_

- - -
_2019-08-01 11:52 IMS docs relevant to T&I specifications and documentation_

https://developers.imsglobal.org/oneroster-v11-final-specification ⇐ 2019 +
https://www.imsglobal.org/spec/security/v1p0/ ⇐ ! 2019 +
https://www.imsglobal.org/sites/default/files/ExtendedTranscript/etv1p0candidatefinal/ET-RESTBinding/CLRServiceGroup_RESTBind.html ⇐ 2018 +
https://developers.imsglobal.org/oneroster-v11-final-best-practice-and-implementation-guide#AppA ⇐ 2017

- - -
_2018-08-23 18:48  improved schema processes in IAM administration_

- - -
_2018-06-27 13:48  idMatch_

```
components:
  schemas: {
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
    reqired:
      - name
  }
```

- - -
_2016-01-15 06:56 references and links_

http://json-ld.org +
https://developers.google.com/structured-data/testing-tool/ +
http://stackoverflow.com/questions/29480115/json-ld-additional-properties-that-are-not-in-the-dictionary-schema-org

http://json-ld.org/ +
https://developers.google.com/structured-data/testing-tool/ +
http://stackoverflow.com/questions/29480115/json-ld-additional-properties-that-are-not-in-the-dictionary-schema-org +

- - -
_2016-01-15 07:03 selectively ignoring elements in json-ld_

http://stackoverflow.com/questions/29480115/json-ld-additional-properties-that-are-not-in-the-dictionary-schema-org

parsers usually don't mind about extra stuff they don't know. they usually ignore it. of course the right thing to do is not to clutter linked data with technical metadata which have only meaning to you. this may help you to see what google sees and what not developers.google.com/structured-data/testing-tool – Sharky Apr 7 '15 at 0:39

Bots [and parsers] will simply ignore those properties. If you don't map them to URLs (for example by setting them explicitly to null in the context), they are effectively invisible for a JSON-LD processor. See http://www.w3.org/TR/json-ld/#advanced-context-usage for more details.

Markus Lanthaler

Yes, but all the undefined properties, google testing-tool gives an errors. – S.A.N Apr 8 '15 at 13:40

Read the error. It just says that the property isn't recognized - which is to be expected given you defined it yourself. – Markus Lanthaler Apr 11 '15 at 12:52

@S.A.N you can define everything you want that is not in schema.org as schema.org/Thing or schema.org/Intangible - if you have properties for something which schema.org does not cover then you can either not add schema.org data to that property but leave the HTML there and the parser will ignore it and not give an error. – Mousey Sep 28 '15 at 22:03

- - -
_2016-01-15 06:56 extensible and elide-able schema_

```
Dimitri van Hees info@dimitrivanhees.com via listhub.w3.org
6:48 AM (6 minutes ago)

to public-schemao.
Hi,

First let me introduce myself. My name is Dimitri van Hees and I am currently working on a research for the Dutch Government about publishing geospatial information on the web. It's called the Geo4Web Testbed and is closely related to the W3C groups 'Spatial Data on The Web' and 'Data on The Web'. I am involved in Research Topic #3: Crawlable geospatial data using the ecosystem of the Web and Linked Data (http://github.com/geo4web-testbed/topic3). For this purpose we want to make use of the Schema.org geospatial classes and properties to investigate if Search Engines will crawl the geospatial information.

Here is my question. Apart from multiple other representations, I'd also like to expose a JSON-LD representation of my resources. JSON-LD is fine with multiple vocabularies and you can in fact 'ignore' properties by not defining them in the @context. This means this is my source (note that I shortened the polygon value for readability):

```
{
  "@context": {
    "geo": "http://schema.org/geo",
    "polygon": "http://schema.org/polygon"
  },
  "@type": "http://schema.org/Place",
  "ID": 1,
  "MUNICIPALITY": "Leeuwarden",
  "WATER": "NO",
  "geo": {
     "@type": "http://schema.org/GeoShape",
     "polygon": "53.24330130 ... 2536921"
   }
}
```

>From a Linked Data and JSON-LD point of view this is completely correct. The properties ID, MUNICIPALITY and WATER aren't mapped in the @context so the parsers ignore this. However, the Structured Data Testing Tool reports errors that those properties aren't known as properties of http://schema.org/Place. The same errors occur when I map those values to another (my own) vocabulary.

I was wondering if this really is an issue for Google or is this just an issue with the testing tool?

Looking forward to hear from you!

Kind regards,

Dimitri
```
- - -
