=== tiWorkPlans.adoc
https://docs.google.com/document/d/16nhw6dCDe6sbl-kzEEQY__iqu5sGfOsqx0wviJHInDk/edit#heading=h.pj4blu2jphr5[] <- *- 2023-4 agenda & scribing: PlanSeqWork -* +
https://internet2.zoom.us/j/96609597422?pwd=bXpLSEl5ZWpsZEVNc1ZtbUg3VlVyQT09#success[] <- Zoom, Tuesday 9:30 am; PlanSeqWork[] +
https://internet2.zoom.us/j/4152791650[] <- Zoom, Thurs, 16:00 - 17:30 EST; PlanSeqWork +
https://docs.google.com/document/d/1onzxKckHmjjrOD5Axp6TQEz9NG9aZ5UlwaIHCWkhp8U/edit[] <- Qtrly Adv Comm Chairs +
https://internet2.zoom.us/my/annsroom <- Zoom, PWD: 2021; QUACC +
SIWG is here partly to repr. community priorities, and to take on technical projects for which CACTI identifies the need +
https://docs.google.com/document/d/1a8cg4B-cgkg4rBA33nhHBgBwKRCjMHVlOcvj7HHj3yc/edit# <- old scribing doc[] +
https://docs.google.com/document/d/1onzxKckHmjjrOD5Axp6TQEz9NG9aZ5UlwaIHCWkhp8U/edit#heading=h.kjr77st37n90[] <- Quarterly Adv Comm Chair scribing doc +
https://docs.google.com/spreadsheets/d/1Be-haluuxgpNaMQ9uL7Ft9Lj71LPsl2kZOzFNIIvYQM/edit#gid=1953682322[] <- TAP Initiatives and Epics .ods; 2020/07 +
https://drive.google.com/drive/u/4/folders/1FiXCC07TmXm0FABO8O6rATxN-4M6mES9[] <- csp wb +
https://todos.internet2.edu/browse/TAP-115?src=confmacro[] <- +
https://docs.google.com/document/d/1DAtAXyxmWqT0ZFZAAKuUQafYF_aTefC_GvMsmrvy3SQ/edit?usp=sharing[] <- My TI Project Radar worksheet with entry template +
https://internet2-bunch.monday.com/boards/2516784927[] <- @i2 丟掉-! Monday work planning tool for TAP +
https://internet2.monday.com/boards/3979353304[] <- Partner contracts +
*- July 29: SZ in UP woods -*

- - -
_2024-09-05 14:06 arch plan, seq, work_

all-staff / Ann Arbor gather requirements across all 4 exercises, put into box

end the week w plans to build out the solutions



- - -
_2024-08-02 13:00:00 4rly adv. comm. chairs meeting_

https://docs.google.com/document/d/1nyC85JNcWS1hsnYAPPR3xJIuzUHPZZX3xELXF8tUZWM/edit?pli=1[] 2G24 Report from Futures II program; Using Monday.com and will have a public-facing status board  (Romy, Ann)

https://docs.google.com/presentation/d/1lMXcGDFfIEsUdqQgiAqpZiAyAbtdAH04/edit#slide=id.p1[] <- Charting the Course-April2024

https://docs.google.com/document/d/1uUlpJJFz_oqof8Fd1UEJF0ePICXGObO2NOiWyWJSCs8/edit[] <- Quart Chairs InCommon Manifesto - Aug 2, 2024

- - -
_2024-07-16 15:11 plan, seq, work_

Regrets: 

. Upcoming CA Calls - Ananya July 29, and Chris August 12, then back to normal rotation
. COmanage / Functionality gap-fit. (Ananya)
. Want to prompt Catalysts to take the bit and contribute more (may need to work with James C to source this in the Catalysts’ own meetings)
. Security notifications and response across the components
. “Recipe Book” of how-tos and slack channel preservation of selected items: Where should they be published?  (Keith)

Ananya: COmanage or what? Review of Essential COmanage functionality: 
https://docs.google.com/document/d/1_1mWu60Hbxj5sE9Lqiir1xqgukjPe3EWF5J6Gx-Z5aE/edit[] +

PaulC: account linking in V4 with Janos?
Nicole: It's not critical, we have a tactic to get by.
BillKK; May have new use cases for account linking. 3k slack users, many don't have IdP, and are unknown to us.
Ananya: we have no idea if what is promised will be delivered; SMU is using a COmanage Milestone Release 14; 3-6 months to deliver next MR
Account linking can be done today if midPoint is left out of this loop
SZ: We still need to finish Essential COmanage Functionality. Agreed.
FM has account linking built in: 1 to 1 only
SZ: Newer catalysts: csw, distillery


* multi-valued UID doesn't get exported by COmanage; Benn: COm v4 sata model is flawed.

- - -
_2024-07-11 15:00 plan, seq, work_

GradyB: Sharing w his teams that he's interviewing...so...
IJ leaving I2 Aug 9

all I2 enhancements have come from Alfa Jango; SZ: COm v5 enrollment mgmt is vaporware

NEED self-service / enrollment / Friendly UI / credential assignment

Do we need COmanage? what is the full suite of 
requirements we need to fill w/out COmanage: SZ, Nicloe, Ananya
pro COmanagee: V5 is registry only           PaulC, Ananya

Ananya: We lean heavily COmanage UI, results of 2 1/2 years



- - -
_2024-05-30 15:02 plan, seq, work_

*- points that got homed on last day of AA F2F -*

- BillK: How to do better facilitating of Zoom meetings (AI)
- SZ: Investigation Approvals are a valid Project Objective
- https://distillery.com/[] <- near shore SDC

- - -
_2024-06-27 15:10 plan, seq, work_

New challenge: AI links popping up in our services willy-nilly


- - -
_2024-05-07 08:30  plan, seq, work_

okta wise-up: check with SZ on framing. He doesn't understand HE FUD. 

] ping compArch about hidden jewels of dagramming and modeling

- - -
_2024-05-02 15:20 TechEx: how can you all do things the way i2 does_

talend, ....  open source data munging; AWS glue patter. Mulsdoft and Informatica (now Saleforce)
Dave Shafer Apache Spark underneath; 

Blueprint discussions at F2F ^ CompArch week *must include data movement*

- - -
_2024-04-23 10:00 plan, seq, work_

Hyzer ABAC next plan, seq...

SZ: With M$, The game is not success, but exposing truth, and silence is acquiescence, Corey said 4 important things: 
1) He acts as a lobbyist within M$, 
2) It's all numbers driven: Upvoted things get nowhere, 
3) Stunning: How prod decisions get made is same as it was 40 yrs ago: imposible number of groups, depts, committees, 
4) disppointing: He came across as the old man shaking his fist at the sky. He's the flak catcher: Mau-Mauing the Flak Catchers.

Paul: Our CIOs fork over $100ks without pairing with any requirements

SZ: If we compose a doc, there are people at M$ who will read it.

NIH

- - -
_2024-04-04 15:25 plan, seq, work_

https://docs.google.com/document/d/1wf3-YVNBc4uIXnj97CNu3ompgYWrtKdZ3KinnHTTNqQ/edit[] < Ann Arbor Planning Meeting May 21-23 (Tu We 1/2 Th) 

https://docs.google.com/document/d/13Pjn8jjic9HJAOOBXmpFU9qGc1sDVuGvlibhNwgvJUU/edit[] <- project review F2 +

"Project Framing Blueprint Refresh".pdf <- !!

- - -
_2024-03-26 10:00 plan, seq, work_

SZ: we need to bring in add'l resources around outreach, but we can't say that out loud

Bill: here’s one version: https://evolveum.com/wp-content/uploads/evolveum-a-focus-on-the-cio.pdf

Ann & Romy will start to hear about the COmanage issue

- - -
_2024-03-21 15:00 plan, seq, work_

] mention use case focus on FedMgr for next ERP to Access Policies TF

Hi All - Can you please each take a few minutes to look at the attached document - and provide feedback (or comment/contribute/edit in the source document: 

Why Use Cases +
https://ucaid-my.sharepoint.com/:w:/g/personal/szoppi_internet2_edu/EeKzxv8X-lBBrqMCWmsKSzEBiYwue_FqHwqTMYSs9n9OSQ?e=l6tZBV[]

SEE useCase.adoc

https://ms-cc.org/[] <- MS-CC Home +
This includes HBCU (Historically black colleges and universities).
swath of new communities that will be accessing I2 services

- - -
_2024-03-12 10:28 plan, seq, work_

SZ: everyone sees us as a vendor, we need them to be seeking the good of the commmuity
me: Where in their lives do they practice such a thing? Nowhere.
SZ: Professional communities of practice do this.
me: IdPro?...

- - -
_2024-03-07 15:00  plan, seq, work_

Here are links to several midPoint webinars from late last year until now. We could show some at the next midpoint user group meeting;. the actual videos are from 20 minutes to an hour each. (edited) 

https://github.internet2.edu/ICP-OPs/guest-account-creation-api/blob/v0.0.2/README.md

https://evolveum.com/unlocking-accessibility-in-midpoint-webinar-summary/[] +
https://evolveum.com/midpoints-first-steps-methodology/[] <- Apr 9-12 +
https://evolveum.com/simulations-webinar-summary/[] +
https://evolveum.com/resource-wizard-in-midpoint-4-8/[] +
https://evolveum.com/convenient-docs-exploration-with-the-latest-enhancements/[] + (edited) 

https://docs.evolveum.com/midpoint/roadmap/[] +

SCIM 2 connector in development, Provision IAM +
https://drive.google.com/drive/folders/1Ar7nGJ3eMk2-DVljK44lT9Aa9lun8MZC[] +

- - -
_2024-02-23 10:00  mP subscription models for HE/R_

STEVEZ:

HE can't be subject to the kinds of abrupt changes in pricing models

IAM products generally are in feature stasis; IAM is getting a smaller chare of the capital pie.

Silent, extortional changes in pricing models are evil. (see Oracle, Adobe...)

TX legislature has biennial budget cycle...

SLAVEK: 

Loss of collaborative spirit is real. Evolveum Underestimated demand for clustering on HE side.

SZ: What kind of info do you need from us

[concerted effort at assessing prioritized list of features] 
- use mPUG and I2/Evol coordination venues for info sharing

all this is the case for push on telemetry 

[What are the fatal diseases for service offerings?]

Ananya Monday meeting plan

- Intro

- midPoint on perceived Need for change

- timeline for changes

- - -

[raise scope of discussion a couple levels: 
1) Open Source Providers
2] I2/InCommon
3) Catalyst Partners


- - -
_2024-02-22 15:00  plan, seq, work_

get requests for project funding in to SteveZ ASAP  √√

collab w Unicon/Paul  


- - -
_2024-02-13 10:00  plan, seq, work_

SteveZ: Moving federated identities into IAM, plus self-asserted, delegate-asserted, and FM-asserted attributes

Nicole: minimize what's needed beyond what comes front channel; and especially the remnants that FM systems need to repose



- - -
_2024-01-25 15:14 review TAC call bits on Futures2_

- enterprise data (CRM, HR): We could do better. Metadata == Attributes (data about other entities, so data bout data, so Metadata. Data on I2 staff is under-developed; attempt 1 couple years ago: data mgmt

who gets access to what? core question to Net+ for 4+ years; (meta)-advisory boards, lots of them. 
They have been unable to write down the rule set

data for administration of our projects, programs, and groups.

data about who defines schema and attrtibut value types

Committee Groups Use Cases:
https://docs.google.com/document/d/1IZb7Z62Goz0UzphVhiQczxhYI1U6jABTYKBVfdo9ZlA/edit?usp=sharing

order of work in MVC:

1 - model
2 - controller
3 - view $$$$

BillK: open to any comments on how to better assert some of these access right

DrewA: each group sees itself as a snowflake

EDUCAUSE has good ui for self-maintained attributes; but depends on individuals to update

admin delegated out is managed by I2, we need to be able to communicate that info to delegate-campus

Elaine can enter 'Tom Barton' and get a display of all the Resourcees he can access for which Elaine manages access policy.

- - -
_2024-01-16 13:28 plan, seq, work_

SteveZ: "self-asserted attributes with a good UI: Ongoing issue: COmanage can't do it, we have to do it ourselves...we've got to get our data story together for the community

Enrollment

requirements codification is an essential first step

- - -
_2023-12-12 11:00 plan, seq, work_

"attribute management" (claims and their vetting) as 2024 issue;  "badging and scorecarding" Came from Net+

data governance not getting attention it needs

a claims re b +
a claims re a +
I2 evaluating claims and those who claim (e.g. cloud svc provider) +

community offers campus drupal 'free' badging/scorecarding

when community member wants service x, how do we provide guidance about choice



- - -
_2023-11-03 13:00:00 Quarterly Advisory Committee Chairs_

- - -
_2023-10-31 11:00 plan, seq, work_

https://www.crunchbase.com/[] <-

https://www.msn.com/en-us/news/technology/update-4-google-ceo-acknowledges-importance-of-being-default-search-engine-in-us-trial/ar-AA1j6Gqd 

https://finance.yahoo.com/news/thoma-bravo-named-inc-2023-111500770.html?fr=yhssrp_catchall

- - -
_2023-10-26 15:03 plan, seq, work_

COm: Whither COmL BennO to say whether or not (NOT) he can meet the Feb deadline

SZ: whole lotta 'told you so' from me

1. Dev tools project discovery
2. TIER beacon / telemetry work

Bill / Internet2
GDrive for WSAs https://drive.google.com/drive/u/0/folders/0AFsLKAq3by13Uk9PVA[]
monday.com board https://internet2.monday.com/boards/3979353304[]

Drew: 
- - -
_2023-10-17 10:00 plan, seq, work_

https://spaces.at.internet2.edu/display/Grouper/Grouper+instrumentation+I2+telemetry[] +

https://docs.google.com/document/d/16nhw6dCDe6sbl-kzEEQY__iqu5sGfOsqx0wviJHInDk/edit?usp=sharing[] <- Steve Zoppi; This may be a no-brainer for everyone here - but ... this is a very good (and brief) article - it's not that long but it underscores some important concepts.  The title is misleading - It should read "5 reasons why the traditional view of the database is dead":

- - -
_2023-10-12 15:00:00 plan, seq, work_

SZ: 
- SoW is largely boilerplate
- Work Segments are agreed-upon, specific deliverables

*- Responses to Grouper Survey Initial Recommentations -*

https://github.internet2.edu/internet2/iam-knowledge-bits/blob/2995e7e53a15573c3dfa3fca61c3627f63a59ec7/grouperSurveyResponses.adoc[]  

Ensure that each 'page' or unit of documentation carries helpful metadata (tags, keywords, with a controlled vocabulary of primary terms) 

- type of documentation: How-to, tutorial, reference, explanation (ConOps)
- context: Deployment, Tech Dev & Integration, Administration, data structures, UI guides
- other keywords to support search terms
- versions to which documentation applies (e.g. Grouper >= 4.7)
- links to related documentation units
- date created, date last modified

The above categories align fairly well with the responses to the "Improvement Priority" question on the Grouper Survey

Keep in mind creation and maintenance costs when formulating documentation guidelines

*- Harvest Slack problem posed and solutions offered on Slack; Collect in a well-known documentation resource-*

cf www.mcknightcg.com presentation

Internal IAM projects on Monday.com

- - -
_2023-10-03 09:49 plan, seq, work_

SZ: "Features are a distant third for funding this year. DOCUMENTATION must be front & center"

TAP GAP ACamp session:  "Keep everything, and add these things"
 T&I: "Then we need more $; Do you want to pay?"

Dave: 

you should now have access to the space where this page is located. Is there anyone else here who doesn't have access? https://spaces.at.internet2.edu/display/TIO/Software+Development+Best+Practices
:heavy_check_mark:

Also, FYI, I started a draft to work out some ideas for documentation requirements. Everyone should have edit access, so feel free to add your thoughts. https://docs.google.com/document/d/1l8Jkx7fJhUL4XdNjjB6Ps3p0ku4Ycli2INVf4nnHcm8/edit?usp=sharing
https://aws.amazon.com/prescriptive-guidance/?apg-all-cards.sort-by=item.additionalFields.sortDate&apg-all-cards.sort-order=desc&awsf.apg-new-filter=*all&awsf.apg-content-type-filter=*all&awsf.apg-code-filter=*all&awsf.apg-category-filter=*all&awsf.apg-rtype-filter=*all&awsf.apg-isv-filter=*all&awsf.apg-product-filter=*all&awsf.apg-env-filter=*all[] <- Amazon Prescriptive Guidance 

https://awslabs.github.io/green-boost/overview/intro[] <- Green Boost toolkit as example from Amaz Prescrip Guidance

] Check w Drew on Prov. Cookbook supplemented with recipes / case studies

The next step for the Provisioning Cookbook is an ask to institutions to fill out some IDM Product Evaluation Metrics.   The Master is at https://docs.google.com/spreadsheets/d/1xYdVSQBCcjDCXwHiRlCewHCZ1exWrNf_jM0Bchn3nlo/edit?usp=drive_link

https://spaces.at.internet2.edu/display/Grouper/Documentation+Notes[] +

https://docs.google.com/spreadsheets/d/13JKJ79Ida95wLeeE4kxEfo41wQZSdJ3IhSDDrBzIcuI/edit#gid=0[] <- Shib IdP UI adoption/interest +


- - -
_2023-08-22 09:48:56 plan, seq, work_

CRM: We don't actively follow through after they finish a program/evemt

DaveSh: We need to develop a practice around what info goes where, what tools o we use. The 4 quadrands of documentation

- - -
_2023-08-08 10:00:00 plan, seq, work_


- - -
_2023-08-04 13:00:00 Quarterly Advisory Committee Chairs_

https://forms.monday.com/forms/d4029d18190a0cb2306dd4abe1444002?r=use1[] <- Using Monday.com for surveys and questionnaires +
https://support.monday.com/hc/en-us/articles/360000219209-Import-export-with-Excel[] <- Spreadsheet import/export +
https://support.monday.com/hc/en-us/categories/115000834105-Using-monday[] <- !! Online feature documentation =

https://docs.google.com/document/d/1LSdkYvTfaVDwQKMvFXQbgHOKR7D3oGuwnhtcwU6HCXk/edit[] <- this old house +


- - -
_2023-07-25 09:48:40 plan, seq, work_

- - -
_2023-07-06 15:00:00 plan, seq, work_
Keith Hazelton
SZ: Data Governance meeting tomorrow, hires pressure

SZ: Out both weeks after next week's BASE CAMP; July 17 - 28; will miss all meetings except CompArch on 24

- - -
_2023-06-13 10:37:08 plan, seq, work_

https://docs.google.com/spreadsheets/d/1duiGxvdVDBhKH60AHbzwAoZEpLpHgXA3poK-ptBYzRk/edit#gid=0 <- AA F2F component mini-orientation schedule +

- - -
_2023-05-30 10:30:00 plan, seq, work_

SZ: Going for more consistency in security measures, so a group meeting of concerned parties is being scheduled

Today we are 3 weeks from Ann Arbor Architects F2F meet; Waiting for MikeS

- - -
_2023-05-16 09:30:00 plan, seq, work_
https://github.internet2.edu/raw/ti/systems-architecture/main/iam/images/iam-signup.png?token=GHSAT0AAAAAAAAAAECN7T7FYCUJSHUNXZTGZDDUYCA
Chris Hubing - Internet2 to Everyone (May 16, 2023, 09:55)
https://github.com/IdentityPython/SATOSA/blob/master/doc/README.md#saml2-backend
Nicole Roy (Internet2) to Everyone (May 16, 2023, 09:55)
CILogon requires OIDC on both sides

See: sjz-directs-ext for diagrams on JIT enrollment flows with AuthN and deep linkng to the initially requested URL

Bill Kaufman: 
As a follow up to our Tuesday Architect call I have done some preliminary testing of the SATOSA Relay function we discussed.   The good news is that it basically works well, however, there are some things to consider.  I have documented early results here: +
https://docs.google.com/document/d/1uP3KDhJOLqAJrrS0lUrOJ2tR1rHIfVjj2A3w12fwMK0/edit?usp=sharing <- SATOSA Relay Back to Origin Link

- - -
_2023-05-12 08:20:17 Working Group Launch_

https://spaces.at.internet2.edu/x/VoRRBQ <- Guidelines for Trust and Identity Working Group Chairs and Flywheels +
https://spaces.at.internet2.edu/x/m4dRBQ <- Tools for Publicizing Working Groups, Recruiting New Members and Onboarding +
https://docs.google.com/spreadsheets/d/10WXvHGdJpN8-hAQxLrnh6b1y6RKRM5dZ85V_jR3OsKk/edit?usp=sharing <- Trust and Identity Working Group Support Levels +

- - -
_2023-05-05 13:45:20 Quarterly Advisory Committee Chairs_

https://docs.google.com/document/d/1onzxKckHmjjrOD5Axp6TQEz9NG9aZ5UlwaIHCWkhp8U/edit#heading=h.kjr77st37n90

KevinM: Roadmappy stuff: CommExch next week will feature update on 5 year roadmao preview across I2 programs; T&I
 Mark & Kev: Futures 2; need to get the info out;

 SueG: Rollover Process update

- - -
_2023-05-02 09:39:50 plan, seq, work_

Arch retreat: kick-off focus on how we do things; "What is working today?"" (Reg. sustems, Stova, Looking Glass); what's unique about our implementations of Grouper, midPoint, COmanage; Identity data flows, data usages, data management;
- mini Ted Talks on what we do, then move on to gap ID and gap filling.
- FM: Use of data for EduROAM, InC Federation.
- How data CAN flow: Stova (own repo) interchanges with Salesforce
- Telemetry in scope
- PaulC: Where does data go to die?
DrewA: high-level concepts and illustrative use cases
DaveS: structurizer light 

IJ: meeting w github.com: repository committers from community: support them using their own github credentials; (class for 1 year, then move into gh enterprise)

2 - 10 licenses for gh ent. per training/class

operational repos may be able to use gh.com in some cases vs gh ent.

DrewA: flip attr release in SATOSA to the SPs; default is nothng

PaulC: I'll do a mini-course (Tues, May 16), on Satosa: It can do a lot of stuff, is powerful, and is in the middle of the I2 stuff. 

ThomasP: Test data mgmt (TDM): genrocket.com/synthetic-data-generation; alternative: scrubbed prod data

- - -
] Get a demo from the Fanner folk at UIUC.

UIUC looking for cross-system mP;

*University of Illinois - Urbana-Champaign*:  *Erik Coleman*, *Chuck Geiger*, Jeremy Watson, Jeff Domeyer, Keith Wessell, Beth Vanichtheernont, Erica Ohman, Shim Ahmed, Josh Grier, Pat Schlehuber +

Banner for HR & SIS: both messaging and batch from SoRs; AD is primary dir & cred store

Primary focus on mP as registry and provisioning; plus access request & other processes
- - -

- - -
_2023-04-27 15:00:00 plan, seq, work_

commercial offerings lack: connectivity and latency

*- The week of June 19th: Data is the Thing -*
- sz all week +
- Tue will be the travel day (Meeting days: Wed, Thu) +

Wed
- existing data repos and connections (SalesF, FM)
- info gaps & needs (IAM data is the core, bio-demo (registration, etc; incl beacon)

Thu
*-- begin to design responses to the unmet needs -*
- sequence of work

*-Component Architecture meeting agenda -*

*- IIW Debrief -*

 Last session: Doc Searle: What AI will never do...

*- "Redirecting" the newbies on slack -*

*- Bill's movement to 'partial time' -*

*- Bench of Skills (Agency Partners & more) -*

*- Community Exchange: nope -*

- - -
_2023-04-13 15:00:00 plan, seq, work_

next] get SteveZ a skill set list to factor in to his agency conversations about more web dev, ui,...

SteveZ: 

` data mgmt writ large: Deaton(?)
`` data gap on eduroam side (Nicole: It's Mark, Margaret is his mgr); we WANT to work with agencies...if they work

https://docs.google.com/document/d/1VE0f1ZK9bcpaTqri96VIl0Zlz-eJJm15NR6Uirzi8dc/edit <- eduRoam infra op reqs +

- - -
_2023-04-04 09:37:24 plan, seq, work_

https://docs.google.com/document/d/1f_vIWWWR4UCmiEfD9ybO_COslDz012Ucwv9-Inf-YMA/edit#heading=h.ga5l5z3k1dna
 <- Template TAP Project Proposal +

- - -
_2023-03-30 15:40:54 plan, seq, work_

Arch F2F, Ann Arbor, 2 days mid-May 

What forms of info would actually help clarify the fuzzy wishes of folks looking at TAP

Ananya - The summary points I had for last meeting but didn’t get to. 

` Expand on fundamental use cases that you keep hearing about at requirement gathering sessions in multiple venues
` Provide support through expanded documentation
` Have a hierarchical structure. Lifecycle management as overarching theme and various use cases as leaf nodes
` Identify activity patterns based on Keith’s IAM attributes for each use cases
` Use tagging as one of the navigational aids

https://docs.google.com/presentation/d/1bOppoTQ4_sbCyxVv5de1Y-l0piHtp1cFb99bK-ZPMsE/edit#slide=id.g22112b12d33_0_7
 <- I2 IAM Case Study
 

- - -
_2023-03-21 09:30:00 plan, seq, work_

Chris Hubing - Internet2 to Everyone (Mar 21, 2023, 09:38)
This is the folder we created to store these things… https://drive.google.com/drive/u/1/folders/1U50vNTXZpy4uaoQZ2O3FlHnwrQHbMAXY
Some were update… and hyper started a wiki page based on it for grouper
https://spaces.at.internet2.edu/pages/viewpage.action?spaceKey=Grouper&title=Grouper+instrumentation+I2+telemetry
Scott seems to have update the shib doc… at the bottom: https://docs.google.com/document/d/1_sHzbPFLRVlwkQMefbETmhzMSXXmkACIgbZfV1_XG1M/edit

this: https://shibboleth.atlassian.net/wiki/spaces/IDP4/pages/1265631722/MetricsConfiguration

- - -
_2023-03-21 09:48:43 plan, seq, work_

Chris Hubing
This is the folder we created to store these things… 
https://drive.google.com/drive/u/1/folders/1U50vNTXZpy4uaoQZ2O3FlHnwrQHbMAXY

Some were update… and hyper started a wiki page based on it for grouper
https://spaces.at.internet2.edu/pages/viewpage.action?spaceKey=Grouper&title=Grouper+instrumentation+I2+telemetry

Scott seems to have update the shib doc… at the bottom: https://docs.google.com/document/d/1_sHzbPFLRVlwkQMefbETmhzMSXXmkACIgbZfV1_XG1M/edit

https://spaces.at.internet2.edu/pages/viewpage.action?spaceKey=I2&title=Arroyo
 <- Mike Simpson NS console and adv. authZ support !! +

oess and global... replacement

protocol basis
Not OAuth, OIDC

uses
 jwt
 dojo?: prolog like policy language underlies the authZ portion.


ChrisHuL graphql for new approaches to '
api'
 nemo, picasso, bone,, (BioNeMo)

 sign uo for bionemo info

 inference platform: 4 offerings l4 l40 grace-hopper (grace hpu, hopper gpu) o ang bluefield


 nvidia l4 on GCP and nvidia SPARK-rapids

 pcie h100 (hopper gpu)

 omniverse: generalized integrated system: omniversification; digital to physiccal OS

 omniverse cloud on MS Azure 

no AWS connection










- - -
_2023-03-16 15:00:00 plan, seq, work_

Chris Hubing - Internet2 to Everyone (Mar 21, 2023, 09:38)
This is the folder we created to store these things… https://drive.google.com/drive/u/1/folders/1U50vNTXZpy4uaoQZ2O3FlHnwrQHbMAXY
Some were update… and hyper started a wiki page based on it for grouper
https://spaces.at.internet2.edu/pages/viewpage.action?spaceKey=Grouper&title=Grouper+instrumentation+I2+telemetry
Scott seems to have update the shib doc… at the bottom: https://docs.google.com/document/d/1_sHzbPFLRVlwkQMefbETmhzMSXXmkACIgbZfV1_XG1M/edit

` arch retreat: data modeling and management (telemetry, eduroam,...Thomas's Reporting Stack, Sara's eduroam stuff)

https://github.internet2.edu/ti/systems-architecture/tree/main/iam` <- !!

https://docs.google.com/presentation/d/1bOppoTQ4_sbCyxVv5de1Y-l0piHtp1cFb99bK-ZPMsE/edit#slide=id.p
 <- I2 IAM deck, Bill's initial draft 

- - -
_2023-03-07 09:30:00 plan, seq, work_

sz: metaphor flattening (shared terminology for taxonomies); this yr biggest challenge: help comm. navigate; Steve: Talking products gets us into the product's term/tax. We're most essentially providing navigation aids for the community.

First develop a pitch to the Catalyst partners

Sara: Cloud forum: execs; 1) it's not a magic box,  2) there is no grand architecture across the org need an accountant who understands cloud; have them watch and learn how to recommend. There is no 'cloud forum' for IAM

https://en.wikipedia.org/wiki/Jeanne_Liedtka
 <- 'design thinking' +

NicoleR: Sec/Engr position hiring for implementation: Andrew has pol/proc 


data mgmt, biz rules

simple simple use cases, then show next ring out and why/where the IAM for the simple simple case falls short and what needs to be added to cover the next ring

SZ: Give me documentation of what kinds of telemetry data is natural/valuable for each component. (ProvIAM, Graphana connector)

https://mindmajix.com/react-vs-vue
 <- Overall, Vue enables faster project growth and performance, but React. js has a more robust ecosystem, more templates, and more functionality. This is why teams on smaller projects where performance is crucial choose Vue, whereas React is better suited to complex web platforms.


SZ: SIWG issues around reporting/telemetry need to inform Beacon 2.0 discussions

- - -
_2023-03-16 15:00:00  plan, seq, work_



- - -
_2023-02-16 15:06:31 plan, seq, work_

Arch f2f ann arbor / denver: late of April: weeks of: 17th 24th

upconimg hires: +
` security
` data mgmt person
` softw engineer / solutions architect; (arbiter across projects, cat herding)

https://docs.google.com/document/d/1uZlzh7bUCEDWOY_H462yrn54PROG-AJ3Vu66M7WG23I/edit
 <- *- 2023 DevOps destinations: -* +

` github action runners across the enterprise; initiate a project on kubernetes ?)

` onboarding new contributors: engr, docum, easing their entry into tech aspects (new sw engr?); Dev containers: Make it easier to get the dev environment for newbies

` expand dev ops support for teams; outsourcing dev ops (Unicon,...); Embed dev ops with 
 projects (not a current high priority)
 tool shelves for multi-container packages, persistent environments; test data sets;


` imrpove deployment and mgmt of public cloud
 cloud platform team, next: cloud admin group


` improve observability and analytics
 Finish AWS feed to Splunk
 Telemetry (point to trace features in midPoint)
 https://docs.newrelic.com/docs/vulnerability-management/integrations/trivy/
 <- Trivy + Sarif
 Splunk adoption and growth 

- - -
_2023-02-02 15:21:06 plan, seq, work_

Ananya: delegated admin in COmanage; I2 can't provide Shayna@SCG with a test env. But we're running it....

- - -
_2023-01-24 09:53:56 plan, seq, work_

- - -
_2023-01-10 09:30:00 plan, seq, work_

- - -
_2022-12-13 10:04:14 plan, seq, work_

Gabor session: Detailed recipes for all his use cases; That's not what we do; Attempt to load shed; Today's overloaded sys admins;

See eduRoam reports (as sales tool) 

grafana / loki; or open telemetry

Hey @ascott check out the experimental feature around SBOM indexing in Docker Desktop: +
https://dependencytrack.org/
 <- SBOM indexing +


Write up stories with numbers

- - -
_2022-11-29 09:46 plan, seq, work_

Data work in 2023 Tom & Unicon plus some new hires.

] Let SZ know I have interest and experience-based views on data issues esp. in the area of IAM; Get it into my 2023 SoW

Steve Zoppi/Internet2 to Everyone (10:14)
As we've discussed, we will begin the Component Architecture hosting rotation starting the SECOND week of January.
My current thought is to have each architect build an agenda and lead it in rotation.  The way the current agenda is built is straightforward:

I scan previous meetings for unfinished topics (there are ALWAYS unfinished topics);
scan e-mail/Slack for the prior month to look for any "big topics" from any of the other advisory groups/working groups;
and identify three to four topics for us to discuss.

In general - I would like each of the architects to ensure that their assigned component and related activities are highlighted in their rotation.

We can talk about this more tomorrow - but I wanted to put it out here for your consideration and all other options / approaches are welcome.

Great partner: Painless Security

https://drive.google.com/file/d/1tgSAtiYGG7ygy6IongLClA19GU0uPnRF/view +
https://docs.google.com/presentation/d/1QEl81WNFWfV5xHefiqVtrnU2ylQfRhGwGuMCDH-zP1I/edit#slide=id.p1 +
https://docs.google.com/document/d/1EMnxMLFGCbRiq6BNwbRcqpHJ4ByaN9TTADsilNdst1Y/edit
 <- The AWS orgs proposal +

- - -
_2022-11-06 13:24 audiences and messaging_

- I don't have a lot of recent experience talking to CIOs, so I lack an intuitive sense of what their top tier issues are.
- If I were to try for NMTT I would start from the list of essential IAM capabilities that support a generic solution to end to end services
- Something grander than requirements tracing, connecting top level goals all the way to named components that come into play when addressing the goals
- can we formulate a list of the assumptions that are considered 'current received wisdom' by CIOs and decision makers
-- cloud is the preferred choice--with limited exceptions
-- local code and customization must be minimized
-- solution choice is limited to the research organizations' choice of products
-- IT is basically a cost center

- Is the following a more or less accurate summary of key CIO assumptions?
"Everything can be outsourced, skills can be contracted for. Our ultimate goal: no central IT staff or expenses, IT budget devoted exclusively to hardware, SaaS, professional services; Remaining indispensable on-site skills: Project Management, Contract negotiation. Externally provided training events for functional staff on the use of the applications"

- If so, then we need to clarify the parts of the solution that must be provided by local staff
-- Only your staff know the business rules, the relevant players, the data structures and semantics, and the lifecycle pathways to be supported.
- There is no easy button for this part of the problem
-- There is no monolithic one product solution: Application integration will be necessary no matter what products and services are chosen
-- The hard part also includes configuration of SaaS offerings. An SaaS comes as a blank slate with no knowledge of local context
-- These facts apply equally to InCommon IAM solutions and Commercial IAM solutions.

.

- - -

Thanks for the explanation.

How does this relate to the work that Cirrus did/is doing and our discussions on Components? My conversations with Keith are more along the lines of:

- CIO:  The org problem that a CIO wants to solve “student experience”

- CIO to Arch discussion: This is how IAM/TAP can help student experience and how it maps to “student lifecycle – business architecture/IAM functions”

Arch to Ops – Here are the specific technical services to be implemented and how they interact.

      -- Ann

- - -

One partial answer to myself is that csp applicants show up facing the need to convince their leaders to invest in the program.


Steve and all,

Today, as rarely happens, I am in a skeptical mood. so I will raise questions that might come across as not typical Keith-speak.

Let's imagine a time when the NMTTS's are complete. What are the situations in which they are brought up, and who are the typical speakers and listeners?

How many instances of big direction-setting decision points in a year will present an opportunity to bring up the NMTTS?

CSP office hours coming up. Will come back to this afterwards.

      -- Keith

- - -

Hi Ann (and Keith),

Ann – KH and I had a conversation yesterday about the “Abstract” of what he can contribute for next year and we’re trying to get it into “concrete” form.  Keith asked me to put together some language that might help illustrate our noodling yesterday – so here it is.

Keith – if I have veered away from where we were headed yesterday – please let me know so I can pull it back to where we were – but this is an initial ‘synthesis’ of what I believe the shape of our work needs to be for 2023.

Keith and Ann - Below is a starting point to explain what I think our objectives are and the interactions that will be required between:

- Software Integration Working Group

- Component Architects

- Marketing Communication / Digital Experience

- Catalysts

- (perhaps others …)

The current state of the union is that we need to (In addition to the documentation / architecture work we’ve been discussing in Component Architecture) establish a handful of canonical stories we can tell to “non-technical-practitioners” about use cases which express the “value of the community’s solutions to real-world IAM problems.”  I’m going to assert that we have “more than enough” documentation for the actual IAM Practitioner, but it needs to be better organized.  But from a programmatic standpoint, our biggest “gap” is in having stories to tell to the “non-technical practitioners and administrators.”

The current issue (as we’ve discussed) is that there is no “easy button” but rather than TELL people that (because they’ll just dismiss the claim out-of-hand as being hyperbolic), we want them to conclude it themselves by developing (no more than) three use cases which are fully-decomposed starting with the beginning / middle and end.

- BEGINNING: “the objective/use case that’s being sought. (User Story format)”

- MIDDLE: “this is how the solution to that objective needs to be broken down. (problem decomposition; solution options evaluated and accepted/discarded with rationale for WHY they were either accepted or discarded).”

- END: “This is the arising implementation that meets the initial objectives. (Picture worth 1000 words.  Perhaps accompanied by 1000 words, but ties off all of the threads presented in the User Story)”

Each with a natural conclusion: “That’s why there is no ‘easy button’.”

This will probably take some time to work through but will require the following from Keith *and probably* Apryl:


- Keith will need to vet the “no more than three stories” (NMTTS) with the Software Integration working group.

- The pain points will need to be evaluated from them (Software Integration Working Group):

  o    What stories are the hardest to communicate to your management and your constituents?

  o    What are the biggest gaps in that audiences understanding?

  o    What have you tried with success or failure, to communicate to them?

  o   Why do you think it succeeded or failed?

  o    (more exploratory/evaluative discussions)

- The resulting “NMTTS” will then need to have a canonical solution identified that then becomes “socialized” with Component Architecture and Internal communications teams (including MarComm and Digital Experience) so we’re all talking about / referencing the SAME EXACT STORIES and we all have a common understanding of what the stories are and the conclusions they describe.

- Keith will probably need to “synthesize” a “good enough” architecture; borrowing from what solutions have already been proven out by the CSP community participants and the Catalysts.

These NMTTS will be our “foundational” stories that start the ball rolling on the work that Mark Rank and Dedra started, but we need to translate into / insinuate through our general concept documentation in the new web site’s information architecture.

Thoughts about this will be welcome.

      -- Steve

- - -
_2022-11-04 10:00 Quarterly Advisory Committee Chairs_

https://docs.google.com/document/d/1XZjSE2wvyKXYC7rLRokrT-BKrXFQdASWjNJA8YwUvsU/edit?usp=sharing
 <- Agenda

Dear colleagues,

Hello! This is a quarterly check-in meeting with T&I advisory committee chairs and vice-chairs, so that we can coordinate + collaborate across committees.

Our quarterly Advisory Committee Chair meeting is this Friday, Nov 4th, from 2:00-3:00 ET. The agenda will focus on 2023 rosters for each group. BTW, we had a great turn out this year with a record number and quality of nominations. We hope this has made your job delightfully challenging. ☺

In a nutshell, we’ll be going around the virtual room and sharing the current ideas for your *2023 rosters* as well as doing our “draft picks” for individuals that were nominated for more than one group. We hope this will help you present a draft slate to your group for voting.

BTW, if you have an individual on your group’s draft slate who isn’t aware they have been nominated, please contact them before you put their name forward. The current process assumes that rosters sent to Steering/CACTI/Kevin (see below) include individuals that have agreed to serve.

As a reminder, there are considerations with the sequencing of nomination approvals that we need to be sensitive to:

    *TAC and CTAB nominations are approved by Steering*
        Committee chairs should send their slates to Brad Christ

    *CACTI nominations are approved by Kevin*
    *eAC nominations are approved by CACTI*
        Committee should send their slate to Rob Carter

    *Steering nominations are approved by Internet2’s President*
        Kevin will take the slate forward to Howard Pfeffer

InCommon Steering meets the first Monday of each month, with the next two meetings on November 7th and December 5th.  Ideally, all approvals for 2023 committee nominations will be confirmed shortly after TechEx, which takes place Dec 5-9th, with an announcement in January 2023 of new members.

If we get this far, we’ll also talk about recommended next steps for notifying new members and individuals who weren’t chosen as well as onboarding new folks. Sue G will be working on final appreciation for those rolling off in the new year.

Hope you can join us!

Best, Ann



Agenda:

https://docs.google.com/document/d/1XZjSE2wvyKXYC7rLRokrT-BKrXFQdASWjNJA8YwUvsU/edit?usp=sharing

Quarterly Advisory Committee w/ Chairs Notes
Quarterly Advisory Committee w/ Chairs Meeting Notes 2022 Location: https://internet2.zoom.us/my/annsroom Password: 2022 Time: 2:00pm ET Topics for Future Calls: Meetings in 2022: February 4, 2022 May 6, 2022 August 5, 2022 November 4, 2022 August 5, 2022 Attendees: CACTI: Rob Carter, Chri...
docs.google.com


 - - -
 _2022-11-01 12:47 SZ on 2023 SoW_
SZ

Today, as rarely happens, I am in a skeptical mood. so I will raise questions that might come across as not typical Keith-speak.

Let's imagine a time when the NMTTS's are complete. What are the situations in which they are brought up, and who are the typical speakers and listeners?

How many instances of big direction-setting decision points in a year will present an opportunity to bring up the NMTTS?

CSP office hours coming up. Will come back to this afterwards.

rather than monolithic Use Case, write up particular sub-system integration recipes: Grpr-mP; mP->(AD)->AzAd

get live database of CSP alums & current cohort

ask EricColemAN about R1 mP schools:
UIUC
UIUC System
UI Chicago

id resolution: ask new users to enter an email address for confirmation message

- - -

https://internet2-bunch.monday.com/boards/2516784927

 how-to docs for
 - grouper / mP integration
 - standard grouper connectors

DrewA

 banner/mP int wg deliverables

 case study solicitation and publication

 IAM Arch overlays of component / features / capabilities

 *Forward looking:*

 1. Async messaging: Generic change data capture as event-driven integration strategy
 2. Graph databases and GraphQL--comparison with REST

- - -
_2022-10-13 15:00 plan, seq, work_

DaveS: AWS SQS for I2 infra, moving off RabbitMQ after rationality checks

2023 SoWs


- - -
_2022-09-01 15:00  plan, seq, work_

Paul Howell, NWork, challenging to convince of the value of doing IAM the new way,

Nokia: Deepfield Cloud Genome tracks, maps and analyzes billions of internet endpoints to provide a dynamic supply map of the internet. It provides full visibility into how applications and content are delivered from all the sources across the internet to your network and across your network to your subscribers.

- - -
_2022-06-27 09:15 Bill & Keith: Intro to our workgroups in the T&I space for Andrew Scott_

* SIWG: http://bit.ly/siwg-01 Wed June 28, 3 pm Eastern, then the following Fri July 8, 10 am; Repeat cycle

* PS Integration WG:
** Charter: https://spaces.at.internet2.edu/display/DSAWG/InCommon+PeopleSoft+Integration+Working+Group
** Notes: https://docs.google.com/document/d/12UGDAuQ7YlX7szWd4heHyMUaTjPe3HyeWmrF174nQvc/edit

* midPoint Users Group:
** Charter:  https://docs.google.com/document/d/1Zp2OUWd0EYWndCFtoEqCoxPWT2jRRFxJh-94V1zfnrk/edit
** Notes: https://docs.google.com/document/d/1ERsYSxaPlPZRI5jq1l7puCCJnCt2sVuvI0xb_SBDlAc/edit

* TAP Suite: https://incommon.org/trusted-access/

* Collaboration Success Program: https://spaces.at.internet2.edu/display/TIERCSP/InCommon+Collaboration+Success+Program

.

- - -
_2022-05-26 15:47  plan, seq, work_

SZ: Democratizing Access2Data

We need to keep moving pieces to a minimum; e.g. databases: Today we can work with data where it lives; ReadOnlyReplicas
- right now paranoia is winning in terms of access to SaaS databases
- Rick Dalzell is the guy's name from Amazon/WalMart

https://gist.github.com/nckroy/d5d65046fb4fbcf645693a80e32a6989

“Rick is an ex-Armgy Ranger, West Point Academy graduate, ex-boxer, ex-Chief Torturer slash CIO at Wal*Mart, and is a big genial scary man who used the word "hardened interface" a lot. Rick was a walking, talking hardened interface himself, so needless to say, everyone made LOTS of forward progress and made sure Rick knew about it.”

The SQL view is the contract if there isn't a built-in data warehouse available.
And if something changes, the view breaks. Then we have to fix it.

[might GraphQL thread a new path through these conundra?]

I went down a Thinking Machines rathole last night, and discovered that the co-founder of TMC went on to found Ab Initio. So then I went down an Ab Initio rathole. A bunch of what we're talking about is stuff that Ab Initio specializes in, but I'm guessing it's wayyyyy too expensive and complex for us.

SZ: it's crazy expensive - and overkill.

Steve Zoppi/Internet2 to Everyone (16:16)
we just need to have a set of principles that we can consistently apply to triage  the patterns at which we arrive.

NS doing feature branching to spread the work. Automate dev env spinup of SP per feature branch; getting all that SAML metadata plugged in.

Yeah totally.
I looked at their product line and it was... daunting. Even just reading about it made my head hurt.

- - -
_2022-05-17 09:39   plan, seq, work_

Our Goals Tend toward

* qualitative
* aspirational

Our goals should be set with a mind to achievability, practicality

* Let SZ know what our personal goals are, so he can help
* SZ pulling together a list of goals we need to achieve: metrics on adoption and

E.g. Don't make a task list per goal;

Nicole for Dave: concrete but non-specific: Successful completion of RFP and deployment of DevOps...in order to...
* Offload non strategic work items so Dave has more free time to work on more important

Continuing our evolution toward solution provider (more prescriptive)

SZ is on the hook to help figure out how to map our personal goals onto T&I goals

Goals:

* Continue to follow through on commitments
* Making all we do easier understand, use and discover by new audiences
* Continuing our transition towards being a solutions provider
* Expanding and enriching IAM expertise across the community
* Investing in Automation / Enhancements to scaling our impact, operations
* Supporting other areas of Internet2

Inter-reliance on other divisions/department has grown tremendously

SZ "scan, select, discard, move on"

SZ: [Keith] Is transparency a critical success factor for work on instrumentation, telemetry?

- - -
_2022-04-19 09:30  plan, seq, work_

F2F next week, Denver

Day 1: Event system
Day 2: Projects to explore
Day 3: Continuing project dissection, the NS work,


Aventri links:
https://files.aventri.com/fl/V9RwJwmPV9
https://developer.aventri.com/
https://na.eventscloud.com/website/7872/events-calendar/
https://aventri.zoom.us/rec/share/Lcrnbm9EciX_yyfUGjsngY209qEH7NzoHfgJj7VfFqv0AsD3C9rDbfh6Qikcuyvl.hQbrLNVWI2kNlPdJ (passcode: E0VHMD#a)
https://files.aventri.com/dl/nlzRpQOq7r/video1587252968.mp4_


- - -
_2022-04-14 15:00  plan, seq, work_

April 24-28 F2F:

1: Mon: reg sys (sevent or ventry(?)) +
2: Tue. proj review seq/sizing +
3: Wed. am: netw svc provider switch;  seq/sizing timelines updates

attr mgmt work slotted elsewhile

- - -
_2022-04-11 15:55 portfolio architecture_

https://www.schabell.org/2022/03/portfolio-architecture-exmaples-telco-collection.html
 <- high level architecture of multi-project initiative +

- - -
_2022-04-08 15:11 ad hoc steve call_

steve's data entry for office staff: conceptual review

next] steve to set meeting for him, me and Drew to introduce the PoC app.

- - -
_2022-04-06 14:11 ad hoc call on project portfolio tool, Monday_


- - -
_2022-04-05 09:43 plan, seq, work_

] SteveZ on A2D issues & ChHy new data flows

Sellers of service products (IdP of LR) will want to charge for it. Albert is laying the groundwork; I2 will say get it from Catalyst partners; NS wants regionals to run the infrastructure, but that's hard to foster

BillK: I sat in on the recent Cirrus webinar and their bridge to Azure / AD to Federation is and amazing plug and play setup.  Testimonials from a few institutions were very compelling as to how easy things came together.

Dave: FYI, another potential topic for later-- Chris, IJ, and I met yesterday to talk about finding a DevOps contractor. We could give a quick update and talk about next steps.
  - Unicon, West Arete: DevOps + UI/UX experts

Bill: Interestingly enough I just got a Front ticket with this question:   Does the InCommon suite have the capacity to implement session time restrictions for AD users?

Nicole: if they mean SSO timeouts, the short answer is yes. The longer answer is that the Shibboleth IdP and SP have facilities for controlling session timeouts, but part of the challenge is that *both* a SAML IdP and SP can set their own separate session timeouts, and they can cause somewhat non-intuitive results. There is also the “force re-authenticate” thing that IdPs have at their disposal, but has to be supported by the SP.

- - -
_2022-03-21 11:00 Ethan's position_

BillK & Keith

!Labs need to introduce themselves to Ann, Netta re Catalyst; Start this year

Domesticate Wordpress, higher ed edition, for more fine-grained authZ per ChrisHu +
have Ethan run the SI meetings; help with agendas
Continued support for Workbench; Integrate Grouper connectors.
Sympa on hold this year. One for I2 one for community; Loading Canvas seems to work now.
Drive the Banner connector work

- - -
_2022-03-31 15:00 plan, seq, work_

https://docs.google.com/spreadsheets/d/1gz6RosFyyZMCg6YMwVUZwGu-GzbD2iH7R3fXw-1o_OA/edit#gid=0
  <- working project list +
https://spaces.at.internet2.edu/display/IIAMSP/.Development+Tracks+v0.2
  <- dev https://spaces.at.internet2.edu/display/IIAMSP/.Development+Tracks+v0.2
- - -
_2022-03-17 15:00 plan, seq. work_

https://docs.google.com/presentation/d/1Ip2DxWKxSAG3PORVpOUuZq59vf4BAVJostIpvVl_P6s/edit?usp=sharing
 <- slides, dec 2021 snapshot +
https://docs.google.com/spreadsheets/d/1gz6RosFyyZMCg6YMwVUZwGu-GzbD2iH7R3fXw-1o_OA/edit?usp=sharing
 <- spreadsheet, project scope and sizing +


ICP projects w impact on my workload
` domesticating applications for collaboration
` development and documentation of connectors
` define scope before adding a project

My Projects
` R&D graphql and (Grouper) data flows
` data payloads that are invariant across xport: REST, Async, GraphQL
` async patterns
` how-to documentation`


- - -
_2022-02-22 09:30 plan, seq, work_

Chris Hubing - Internet2 to Everyone (09:38)
https://github.internet2.edu/eduroam/loki-proxy/blob/loki-proxy-0.0.1-dev/Jenkinsfile
 <- this has the groovy declarative pipeline code that can assume a role and push to ECR +
https://github.internet2.edu/internet2/ti-systems-architecture/tree/main/iam#jits
 <- swimlane view of Login or Enroll process +

- - -
_2022-01-25 10:00 plan, seq, work_

Tuesday Jan. 25 2022, 9:30 am US Eastern 4:00 pm Bratislava
I2 AMS kh SpfZ5chHGa5FQVT

 - - -
 _2022-01-20 15:00 plan, seq. work_

 SZ while peeps are out (Feb-Mar): +
 ` picking up debt in biz ownership, distributed access management +

 ` CSP: I2 IAM arch presentation was great and showcased all the progress we made over the last year +


- - -
_2022-01-11 09:34 plan, seq. work_

Nicole: Hi all,

At our next architecture team call (next Tuesday, January 11th), we will be talking about a suggested direction for DevOps for our collective teams in 2022, authored by Dave Shafer, with some input from me and Mike LaHaye. We need to review this as a team and try to come to a very high-level agreement on the direction of this document (or otherwise) and what we need to do in order to free up some people’s time to be able to execute on at least some of this this year, if we think it’s the right direction. I’ve asked Dave to join us to help guide the conversation and represent the needs that he sees in this space. In preparation for next week’s call, please read and comment/add questions to the following document:

https://docs.google.com/document/d/1n8bVfAZwIX_Vfb7Gz5RqSccijvV1CVxHgLGuYB4e9wM/edit#heading=h.jnsobso5trd1

- - -
_2021-12-14 09:51 plan, seq. work_


2022: shake up of biz as normal: TSG can't be drawn back into 2 mo stints on event build-outs

1st thing in new year, propose which debt to buy-down;

2022: Focus on max of 3 things; 2 of which must be debt reduction, allows for 1 new thing

*insert our analyses in plan/seq/work notes*

- - -
_2021-11-30 10:22 plan, seq. work_

SZ's architecture: SoR > [can9tion] > SoRView > [grprLoad] > grRepo > [g/mp connect] > mp repo

[Id Xwalk: IID (reg internal id), XID (reg external id), AuthNIDs, SYSIDs]

BillK: trying to capture a few key parts of this at https://docs.google.com/document/d/16nhw6dCDe6sbl-kzEEQY__iqu5sGfOsqx0wviJHInDk/edit?usp=sharing

*Glue Suite from AWS for data munging*

https://aws.amazon.com/glue
 <- AWS Glue: Simple, scalable, and serverless data integration +

` data brew to fix up variants of institutional names +


- - -
_2021-11-11 15:00 plan, seq, work_

https://docs.google.com/presentation/d/1_bpRmVC4-x0T4XdLcdEEl4IJCATYPYe7qee-d0Mv4hg/edit#slide=id.p
 <- enrolling with I2, BillK +

https://docs.google.com/document/d/13t9KAlB2ITf1b49IhSw-H_rVVk_v3sldVfjk_MzlPYI/edit?usp=sharing
 <- HR IAM requirements +

 - - -
_2021-11-05 13:00 TI Quarterly Advisory Meeting_

CACTI:
` 1) subset wants maturity driven set of prescriptions;
` 2) another wants the easy button,
` 3) another wants deployment, operational guidance;

- T&I wants to put energy into growing the tent
- T&I wants to push the envelope forward from where we are now, R1 + RUCC + Ivy
- should we thread the middle, have a bi-modal approach;

SIWG:
` 1) PS Integration: https://docs.google.com/document/d/1eqRFaQHIGmdnLwuuJgp3Y8VFsL3O3Rv1jgUHqxQ1Gf0/edit#;
` 1) CICD guidance;
` 1) overlap/integration between TAC with Okta, Sailpoint;
` 1) risk analysis: security, reliability, recoverability of containerized, distributed services, IaaS

- - -

next steps for the Advisory Committee roll over process.
` Items of overlap that each group is working on and understanding where duplication of effort is warranted and where it is not. Those that come to mind include:

` Deployment Profile promulgation (TAC) and Baseline Expectations (CTAB)
` Seamless Access and Federation Discovery (TAC, CACTI)

Please bring or post your agenda items in the gdoc: https://docs.google.com/document/d/1kyvrSTwkeZ9O_R2P27NE3swWs_VG5vFW01twD9455aQ/edit?usp=sharing

- - -
_2021-11-02 09:45 Priorities and Roadmap_

SteveZ:

Community is focused on the tactical; but I2 T&I MUST ALSO be forward looking and investing in the future

Elephant/Room:

Nature of open source: I2 helps underwrite development, is accountable to funder-stakeholder;

church & state problem: OS project's self-image is of Church, but it expects $ from the State; But accountability suffers because of the separation.

BFD1: negotiation between project and I2 is essential: Shib: $100k/yr + $100k/yr in Shib UI; Gets lost in board conversations; Shib Consortium is not a legal entity; Scott Cantor is the LinusT of Shib

BFD2: Grouper: grant/i2 funded, based on U Chicago; I2 is now Grouper Project's sole funder; Arguably the easiest to manage: Narrow, specific focus, team is excellent; challenge: Never met a feature they didn't like

BFD2: COmanage is the weirdest of our OS projects; created for researchers so they could have autonomous control of 'their' resources; Primary arch holder (BennO and ScottK cannot agree), ScottK has left SCG for CILogon (SCG is A loose collection of independent developers); BennO is arch principle, burns ScottKs buns; Upcoming: SteveZ will call BennO: CakePHP framework was deprecated, headed to EoL; can kicked down the road; SteveZ: Not in favor of running on EoL software; I2 funded movement to new CakePHP framework, but it still hasn't happened; I2 Creating a bench for COmanage via AlfaJango and Unicon

(I2 pays AlfaJango and Unicon to be fixers and our bench); We are the beta testers so QA (CSP, I2); Bulk of customer base is Euro-centric and their $ drive priorities; They have a special rel w one EU regional, REFEDS; GEANT has backed away from COmanage entirely; EU: Competitors: Perun, Hexa (good enough); They're focused on regionals not on researchers; ScottK is 100% research focused.

Relationship mgmt is dicey for I2; Good results, hard to navigate;

SteveZ: Community is begging for a Roadmap, for more determinism so they can plan; Esp. established components; Projects see as interference

Nicholas: Will not tell you what features other people are paying for. Biz conundrum for COmanage: sign a client, the clients don't want anyone else to benefit from their work, so they need to be reminded of OS principles

Whereas mP has governance, and is for the most part non-problematic

I don't have a nefarious plan, but I do have a plan;

We need greater accountability, we need to understand our needs;

We architects have a challenging set of cross-currents from differing goals of different partners and projects;

Projects are still largely black boxs

No filter: Greater control over what we get for what we invest; filtered: greater determinism

Biggest imperative: Accountability
Next biggest: Sustainability

SZ calling on each of us to assume more direct accountability wrt specific projects

BillK:
Yannis fr. Greece: COmanage, Hexa, and Perun
Axel from Unicon: PHP

MikeL, SaraJ on (de-)prov.

ML: Notifications from HR on departure dates is way fuzzy; W Shannon's departure; Barry Randall: Deprovisioning through Grouper and COmanage; BarryR and ShannonR have footprints all over it; Nicole has a spreadsheet: Not everything is under Grouper's control

Should we have a group structure that differs from community so we can differentially manage staff rels vs community rels

Get all under Grouper's control;

- - -
_2021-10-28 17:28 plan, seq, work: data management ppt and sheets_

Has anyone ever created a brand new internal immutable ID and then went through the process of updating your shib integrations?  If so, how painful was it?  Offhand it sounds extremely painful...

Topic: Keith Hazelton's Personal Meeting Room
Date: Oct 27, 2021 01:58 PM Central Time (US and Canada)

Meeting Recording:


https://drive.google.com/drive/folders/1WDCTmL7YnXB-kwm0K-dcrwrBhJau6x7z
 <- Mode of work assignments: giving us less roundAnnual contract + specific 'work segment approvals' for each chunk of work +


- - -
_2021-09-30 15:00 plan, seq, work: data management ppt and sheets_

1. PRIOR TO THE MEETING – Please PREVIEW this deck: ​pptx icon Internet2 Data 101.pptx  - it should be good with ☕ 👀

  a. This is a preliminary work authored by Thomas P and Gary Gilbert of Unicon (my thanks to them for organizing thinking around this topic).

  b. You will need to view this deck in “presentation mode” because of the builds.

  c. Including the O.C.D. part, this whole deck shouldn’t take very long to peruse since the story I intend to tell (outside of our team) should take no more than an hour to our first recipients who are assumed to be largely uninitiated to many (if not all) of these concepts - therefore I expect it will take very little time for you.

  d. I have made a not-insignificant number of “localizations” which I want to ensure make sense PRIOR to us “taking this show on the road”.

  e. I wish (most of all) to ensure that everyone is properly signaled about the (slight) change of direction, and why.

  f.  We will spend no more than 30 minutes aligning around this.

kh: Challenges to the data product desiderata: System owners sometimes feel like their responsibilities are limited to their system and its needed functionality.

As a result, they may be averse to taking on responsibility for their data's

* Self-description +
* Interoperability +
* Security +

- - -

 
  a. This is mostly to refresh our collective memories about the most pressing (imminent) use cases that we’re trying to address

  b. It is also to ensure that our collective thinking is aligned around the functionality that each of the components serves in our architecture.

  c. It will also (probably) result in some follow-on discussions.  Good…

Driving use cases these days:

To SZ:

I have some bullets on the 2nd major topic of this afternoon’s meeting, priority use cases. Is this in any way aligned with what you hoped to discuss? (edited)

* Continue to develop provisioning solutions for cloud and SaaS (connectors and attribute mapping) +
** midPoint as primary provisioning engine, +
** Grouper’s growing provisioning capabilities, +
* Promote Grouper as TAP’s recommended access policy management service +
* Highlight differentiating features of TAP components vis-a-vis commercial alternatives* +
* Release a Free-standing ID Match component* +
* Make the case for SAML/Shibboleth +
** Publicize AzureAD as an option for Shib AuthN (courtesy of CirrusID) +
* Define our strategy WRT OpenID Connect and other AuthNZ protocols +
* Make recommendations on API AuthNZ and API gateway approaches +
* In cooperation with Catalyst Partners (and I2/InCommon subscribers?) Explore trends in HE IT infrastructure and initiatives +

- - -

https://ucaid-my.sharepoint.com/:x:/g/personal/szoppi_internet2_edu/ETES4MOJHndEmDt15Ji7jhcB3KpjOv0EFrg1gYjBRly1ng?e=9PtGqQ
 <- 'data sources and tools': I2 master data repo in .xls +

https://ucaid-my.sharepoint.com/:p:/r/personal/szoppi_internet2_edu/_layouts/15/guestaccess.aspx?e=gkdMsp&CID=a9c4f00f-62f0-923b-e9ee-7a7ed37c56e2&share=EVqDNiiJ_DFMoHJWZsnFD60BUILoq89zCNoPhSVQxPpLEA
 <- data mgmt slide deck +

https://www.office.com/?auth=2&home=1&section=recentdocs
 <- top folder

 - - -
 _2021-09-21 09:30 plan, seq, work_

All offices other than Ann Arbor have protocols: Proof of vacc. for access to any I2 space; Exceptions policy

ThomasP: Exploring AWS Glue: Data catalog crawler to detect change; Harvested COmanage, looking at dev vs prod; If you want in, have access to current data catalog; Date migration service, it can replicate (think EduRoam migration); CDC for csv files. Do some PoCs evaluating AWS data migration.
next]: ask for access to AWS Glue I2 data catalog; This is tee'd up for (probably) next week.

Thomas: Data Brew from GLUE

Nicole/Thomas:
data migration tools discussion, eduroam data migration leading to a retrospective
if we had tools earlier it may have saved effort
Data Catalog will track structural change
COmanage data harvested and looking first to compare Dev and Prod and also the stats on Pending enrollments over time etc. (Bill has done a tiny bit of hands on)
Steve: AWS documentation on these products does not necessarily point out all the sharp edges and pitfalls, Gary (Unicon) is very familiar with them so that is a help
FM data models and having analysis in place that could fire off messages that could be consumed and processed might be helpful.  Might be a Nice To Have
Exploration is good, but we need to use external resources as much as possible to help vs adopting/developing more tools
At this time Implementation is the highest priority and not exploration

Bill/Paul/Chris/Keith: recap current midPoint - Grouper connector discussions related to the Sympa connector work in particular

Keith/Sara: priority for developing a Slack connector
Should develop requirements around Use Cases, how Admin and Self-Admin might work

next] Connector requirements for now: CRUD for people, groups, memberships in Slack (and Canvas);

T&I Budget crunches coming next year
(not for me)

Steve: all offices but AA have a protocol for use now (following OSHA)
must have proof of vaccination with HR
some exceptions for someone who cannot be vaccination via neg testing

SZ: candor is good, drama is not

Next call: security discussion with Ryan and Shannon (see above future topics)

- - -
_2021-08-24 10:13 plan, seq, work_

SZ: crunchbase for sharp eyes on IT companies

Paul Caskey  09:07
I think there's also overlap sometimes between events (like courses).

Keith Hazelton  09:09
so maybe ..current-blue and ..current-green  or something (edited)
- - -
_2021-08-19 14:57 plan, seq, work_

https://security.psu.edu/awareness/icdt/
 <- +
https://security.psu.edu/awareness/storage/
 <- +

- - -
_2021-08-10 09:38 plan, seq, work_

See link in eduRoam Slack channel;

Here’s a link to the most recent demo from last Friday. Stick around to the end for additional techy stuff beyond the UI: https://internet2.zoom.us/rec/play/kdw_jYW60YqIfbH3JR44_3jPpKTrW_kxwn9c_QV-eKhO-tBu54KlPOvruNtU-7xcufvfGVjuEyQ3gVg.2PvwtIvE0bGUMkLX
 <- cheddarch33se! +

#eduroam-design
#eduroam-internal

Thomas Pratt: DMBOK; SteveZ has positions on data governance. Be prepared to debate.

 - - -
_2021-08-06 13:00 TI Quarterly Advisory Meeting_

*Software Integration WG*

https://spaces.at.internet2.edu/display/TI/Trust+and+Identity+Working+Groups+List
 <- Full? Listing of WGs; work w Netta on edits

next] SIWG Help RobC: CACTI hopes to spawn # of WGs

next] offer to help prep AnnW/MikeC IAM Discussions

help needed: Filter for high priority gaps

Sept. 15 IAM Online: take a task to inventory current, planned and candidate working groups


- - -

- COmanage/midPoint integration initiative

-- COmanage connector development; ID Match standalone under consideration by Evolveum for integration with midPoint

- Workbench experience w CSP

- Next steps for the West/Corn/Murtha IAM confabs

-- expand the list of participants sharing info and collaborating

- Scan Base CAMP artifacts for new and newly relevant projects and problem areas

-- Flat namespace service across

--- -- 1) IN2ID (INstitutional INternal ID, 'into ID', 'intuid' +
--- -- 2) LoginID/Username +
--- -- 3) Email Address

--- API Gateway

--- Overlays from Biz down with Cirrus

-- A functional model that can overlay COmanage, Grouper, and midPoint

--- Overlays from Biz down with Cirrus

KeithW: Webinar to get our workplan out in front of fellow workgroups and broader community. Transparency tool

.

- - -
_2021-08-05 15:04 plan/seq/work_

https://todos.internet2.edu/secure/RapidBoard.jspa?rapidView=117&quickFilter=391
 <- TAP Kanban Epics

- - -
_2021-07-22 15:32 planning/seq/work_

https://docs.google.com/document/d/13t9KAlB2ITf1b49IhSw-H_rVVk_v3sldVfjk_MzlPYI/edit#
 <- HR Identity Groups Draft Requirements v0.1 +
https://internet2.app.box.com/s/txvtjasizjta6azz5yit7ryoy5exr77r
 <- org chart +
https://drive.google.com/file/d/1HSa2v5RqMDT3Vte6nhCC2R0WT1guc_yv/view
 <- I2 org chart in Grouper +

'artifactory'
- - -
_2021-06-29 09:30 planning/seq/work_

https://docs.google.com/document/d/1Kru4X1Wu7wO7a5dXRUDbWLRAU2TCAJeAU4VyvXJNRB8/edit
 <- Provisioning to Canvas from midPoint (MVP.01)

 - - -
 _2021-06-24 15:00 planning/seq/work_

 No Component Architecture meeting Basecamp week Monday, July 12

 FINALIZING: Audience Identification

 (continuing) Successors/New Talent/Catalyst Partnerships - The Future Engagement / Support Model

 (standing item) Patterns discussions / issues for the team (Dedra C, Slavek L, Keith H)

 - - -
 _2021-06-01 10:00 planning/seq/work_

SZ: still editing a multi-page google sheet: User System Data Flows

https://docs.google.com/document/d/1dk5m08WwzNeNUq5oaiImHl4AujIDZGkDg7EDLwWU3sU/edit
 <- Enrolling Event Participants in T&I IAM: Plans +

- - -
_2021-05-27 15:09 planning/seq/work_

DW 1st round goals

1) lay in foundations
2) gain consolidated view of identity data in a place where we can look at what we've got and do some analysis
3) i2 has a long journey coming up through data management principles (PowerBI will be a practicum on dm)

ThomasPratt bus matrix from kimball

https://www.kimballgroup.com/data-warehouse-business-intelligence-resources/kimball-techniques/kimball-data-warehouse-bus-architecture/
 <- +

user flows are a blocker at present (See weekly planning notes from May 6)

https://docs.google.com/document/d/1dk5m08WwzNeNUq5oaiImHl4AujIDZGkDg7EDLwWU3sU/edit?usp=sharing
 <- +
https://docs.google.com/document/d/1Tl0UdhB8fCo5NVGg7-61NKMiGUb2Rqfe8P94kfVZLjM/edit?usp=sharing
 <- +

- - -
_2021-05-06 15:05 planning/seq/work_

Bill Kaufman:
Topics for planning and sequencing today folks?  Add your potential items:

next] review Internet2 Identity Services Program Update 2021
https://docs.google.com/document/d/1oe97XYtskCSWPuFl2kZMUoVsDUUteTSvSPswwfU7nco/edit

Agenda Bash:

Potential threads to address today

Data Architect status and plan for onboarding with team +
FM IAM update/status +
FreeRadius container image status +
Enrollment flows +
IdPoLR Plan to get to production +
Events registration including enjoining registrants to enroll +
Grouper group architecture update discussion +

- - -
_2021-04-22 15:00 planning/seq/work_

- - -
_2021-04-08 15:12 planning/seq/work_

SZ marker: actor enrollment flows done in two weeks; then there's system flows and data flows
- - -
_2021-04-07 13:30 define & launch a couple weekly processes_

a persistent queue of
- desired features; manage as backlog, seek dev. assistance for selected items.
- SIWG discussion-based how-to topics
- - -
_2021-04-01 14:34 planning/seq/work_

slides: https://docs.google.com/presentation/d/1jAPM6T1FRcKE0zg8WYJH5OLAXQFXh7tWbqWv-2MvHLI/edit#slide=id.p
 <- slides +
https://docs.google.com/presentation/d/1l-9z3sCh5ICHdySIUn1dq8zR4UEOJWiJYndi3OzWRSA/edit#slide=id.gc917c6f652_0_31
 <- front door mock-ups +

*BillK: cirrus idp ePPN cuid-6dd3feed-134a-4fc6-a222-bd61ead8d5fd@internet2.idp.cirrusidentity.com (eppn)*

- - -
Hello.

Thanks for visiting the Internet2 Collaborations SSO Check page. The fact that you're here is a great sign that things are at least minimally functioning properly.
***
Here are the results of a few basic checks:
ID:	present	(hazelton@internet2.edu)
Email Address: 	present	(hazelton@internet2.edu)
Name:	present	(Keith Hazelton)
Affiliation, scoped:	missing
***
This service is available in the InCommon Federation and also globally, via eduGain, and is classified as a REFEDS Research and Scholarship service. This classification makes it easy and trustworthy for IdPs to integrate with such services.

You can find information on configuring your IdP to support the R&S category here.

Additionally, more information on configuring your IdP for the new spaces wiki and the related transition can be found here.


Your results:
The IdP at (urn:mace:incommon:internet2.edu) is releasing the appropriate information for this service and you are ready to proceed!


***
Service Details
SAML EntityID: https://login.at.internet2.edu/Saml2/proxy_saml2_backend.xml

The R&S attribute set (which is required by this service) is as follows:
Friendly Name	SAML Attribute Name	Required?
eduPersonPrincipalName (ePPN)	urn:oid:1.3.6.1.4.1.1466.115.121.1.15	Yes
mail	urn:oid:0.9.2342.19200300.100.1.3	Yes
displayName	urn:oid:2.16.840.1.113730.3.1.241	Yes*
givenName	urn:oid:2.5.4.42	Yes*
sn (surname)	urn:oid:2.5.4.4	Yes*
affiliation (scoped)	urn:oid:1.3.6.1.4.1.5923.1.1.1.9	No

NOTE: This service requires signed responses and will reject assertions where only the assertion itself is signed. This is to help mitigate against signature wrapping attacks and is in compliance with the "SAML V2.0 Implementation Profile for Federation Interoperability" standard published here (specification IIP-SP13).

* Some form of name must be sent. The displayName attribute will be used if it is sent. Otherwise, givenName and sn must be sent and will be concatenated to form the 'Name' above.
***
- - -
_2021-03-22 12:00 planning/seq/work_

- - -
_2021-03-18 12:00 planning/seq/work_

https://docs.google.com/document/d/1a8cg4B-cgkg4rBA33nhHBgBwKRCjMHVlOcvj7HHj3yc/edit
 <- agenda, scribing

https://spaces.at.internet2.edu/x/DwAbCw
 <- Roadmap for the Trusted Access Platform created +

 Ethan, Keith, Bill: review

C4, Structurizr, PlantUML progress

actor/activity 1st, then sequence, then data flow <- we have created a gordian knot; can we id canonical flows that are shared,

ti-systems-architecture

Three flows to doc 1st:
. front-door: unsolicited self-sign up, first first
. back-door: invitation,
. back-door: conscription;

SZ: Blocker is xfer point after: Landing point
 activity, sequence (btween systems), data flow diagrams

SZ: I believe there are more than three flows from the actor PoV step;
SZ: Assuming s'thing like a COmanage-based portal; Kiosk,

in the entryway (1 time activity) then there are many choices

[these cases will come up in work w Dedra integrating Cirrus svcs w TAP infra]

primary I2 flow is: invite (x) to participate, do s'thing

https://docs.google.com/document/d/1a8cg4B-cgkg4rBA33nhHBgBwKRCjMHVlOcvj7HHj3yc/edit

https://internet2.zoom.us/rec/play/_zY82T8aP8VVkOGjGQsHIOnL-Jk4Nihhb7NyFSFmXwTEGLTxAKYmFGsXE6EPUu5DBLHAzmTp7CQchlK0.m5M63U6extuRWAmj?continueMode=true&_x_zm_rtaid=UqrtUKF6Rr--WLN3Dw2ntQ.1616097524917.0dc88bb42fd144e3aebe8221bd4c647f&_x_zm_rhtaid=150
 <- COmanage UI Demo  passcode: f^2$uSBK

give an Erin a way to put an invitee into the Grouper subject source before the person is a registered identity

- - -
_2021-03-18 15:00 Mo. planning/seq/work_

Topic #1: enrollment flows for invited, conscripted, opt-in; plus incumbent back-end system flows incl. AuthNZ

- - -
_2021-03-11 15:00 Mo. planning/seq/work_

1) IAM Roadmap: Operational priorities: BillK<, MikeL<, Nicole< Steve< 1/2 hr per week; produce a week's worth of tasks
ChrisHu, PaulC

IAM platform enrollment for guest system

- - -

2) Messaging Infrastructure: Fed Mgr & eduROAM: infrastructure integration; Dave, MarkD, Shannon, johnny, Sara, Keith, Bill;

eRoam assuming eR and Radius talking over a message bus. johnny, ... margaret,

So what's needed for their message bus use case. ChrisHu" Using RabbitMQ Visualizer app

15:34 screenshot of attendees

From Dave: (Example of Terraform config for Amazon MQ)
***
resource "aws_mq_configuration" "example"

{
  description    = "Example Configuration"
  name     = "example"
  engine_type    = "ActiveMQ"
  engine_version = "5.15.0"

  data = <<DATA
***
_______________________________________________________
***
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<broker xmlns="http://activemq.apache.org/schema/core">

  <plugins>
    <forcePersistencyModeBrokerPlugin persistenceFlag="true"/>
    <statisticsBrokerPlugin/>
    <timeStampingBrokerPlugin ttlCeiling="86400000" zeroExpirationOverride="86400000"/>
  </plugins>

</broker>
***
________________________________________________________
***
DATA

}
***
- - -

Registration flows (a blocking issue: SZ); Mike sez: ICP tech team will tackle this; ChrisHu: C4 stuff


Atlassian:  2nd TIER support chat on Atl. push to cloud; need to be in an "access domain"; Fed. SAML still very cloudy;
  Atlassian biz model is a software dev. company; No real interest in ed. market; email-address from a single domain;
  Only good news is we have 3 years to settle it. Per user license; so de-prov.



- - -
_2021-03-04 15:00 Mo. planning/seq/work https://docs.google.com/document/d/1a8cg4B-cgkg4rBA33nhHBgBwKRCjMHVlOcvj7HHj3yc/edit#_

https://docs.google.com/document/d/1RaTy4bNE0dvE7ADym7anpqH2sjTWo-eho47tXf_zVEY/edit#heading=h.gmqf14n7u9in <- I2 Identity Services Roadmap

C4 model, structurizr DSL

our process flows break esp at the human to human

paucity around rubric: needed docs vs docs for docs sake; Romy's helping get together a small library of tools;

NS has 2 PMs:  Ashley (on a dead channel from IU) & Alison (NG)

MikeS ^ Carl working on the next gen arch

AJ wants to use IAM as a fly-swatter for OESS problems

SZ: 1) interaction, 2) sequence, 3) activity; Often casually lumped together as swimlane diagrams

- - -
_2021-02-25 12:27 Mo. Plan/Sequence_

heads-down time too short

3 buckets:

* pers/admin
* 1 on 1 or nearly
* the hold-up: 3+ ppl needed to talk through subsystems;

** core common hours: US/EU only 4-5 hours; community obligations
** it's not get func x to next feature
** it's cross-component work that require multi-parties
** time-splitting, context-switching have reached their limit and broken down
** Slack gives illusion of us talking together all the time

=== Back to Basics time

Refactor ICP functionality into core components and µservices
- Functional decomposition as step 1,
- Defining interfaces as step 2

E.g. Canvas progress too slow; because we're getting pulled into things that are community-facing. SZ calls BS. Delivering artifacts so we don't have

Ideal result for TAP: Grouper, COmanage, midPoint, FedMgr,... can invoke any needed µservice from the collection
- Analyze by identifying the core features unique to a component {Grouper, COmanage, midPoint}

* ID Match UI/API as example
** Attribute mapping
** Invitation and Enrollment
** Multi-Credentialing
** Rich Authentication support
** Self-service profile svc
** Target-specific provisioning connectors
** SSH, invoke shell scripts

We ALL need to do the artifacts that will tie everything together (PM and product mgmt bits)

*Nic, MikeL, BillK will duke it out so our IAM queue is serialized*
e.g. deprovisioning for license cost mgmt

Thing 2: What's Nic's role; we want many scanners staring at what we're generating (incl necessary skills)

We need skills around directing/managing 3rd party engagements

has to work in Ops mode and needed skills

TSG: they have all the support & time we need from them; Everything we do is written "we'll get back into less than 24 hrs" Contxt Switch costs 15' min,

Let's lean more on the Catalyst partners

1st best use for Paul & Chris is to heads-together solve things and let us know.

Sara: EduRoam, & Net+ Cloud stuff

IJ has mega tribal knowledge, need to apply it to our home built; but we need him to help w biz flows re the data initiative

SZ: trying to get ahead of things in multiple areas;
back to basics Panics Mike to hear it

We need to true-up our understanding of Box (out of compliance? No), Confluence, Splunk, and not keep kicking the can down the road.

MikeL: we will start (from $0) giving $$$$ to M$ and Google;

1) Will have to get some time back from Erin & CSP
2) Block this Thurs 3:00 - 4:30 pm time slot, every week for *us*


.

- - -
_2021-01-28 12:46 Monthly Planning and Sequencing_

*src contr.*

gh ent vs gitlab +

csp how do we see our responsibilities wrt participants

ask SZ about the discussions of Arch diagram tools

what's our API/Message preferred architecture

dont know naught about the I2 takeover of eduRoam and domestication

https://docs.google.com/document/d/1EEDzcLWSw-qW32FTzTZEXxK1EhX2kMDtiBnMejnCLf0/edit <- SteveZ, Arch team "Radar" incl. notes from the 29 Oct. 2020 meeting

Key
a. Work Item in-flight and whether or not the project is INTERNET2 or COMMUNITY
b. Whether that work was planned or unplanned
c. Which team(s) was(were) affected
d. On whose behalf is that work is being done
e. Who approved/accepted or rejected that work (and date)
f. The accepted due-date on that work
g. Date that work began
h. Hours expected
i. Hours to-date
j. Completion State
k. Whether or not a requirements document existed for completion of that work
l. If the work was unplanned, what other work was negatively affected by the preemption
m Date Adjustments to the current work (if any)

TEMPLATE

The [a]  was [b] PLANNED and injected into [c]  work stream at the request of [d]  and [e] accepted by ?? on ?? for delivery on [f] ??, commenced on [g] ?? was expected to consume [h] ?? hours and has consumed [i] ?? hours of team time, is [j] not complete.  A requirements document was [k] not done.  This work [l] delayed work on all other projects.

KEITH

### 2021 CSP planning and preparation
The [a] 2021 CSP planning and preparation was [b] PLANNED and injected into the [c] SI WG work stream at the request of [d] ErimM and [e] accepted by Keith in summer 2021 for delivery in fall 2021, commenced on [g] ?? was expected to consume [h] ?? hours and has consumed [i] ~450 hours of team time, is [j]  complete.  A requirements document was [k] not done.  This work [l] delayed work on all other projects.

### TAP Workbench
The [a] TAP Workbench development was [b] PLANNED and injected into [c] SI WG  work stream at the request of [d] all and [e] accepted by KeithH in Oct. 2020 for delivery in [f] January 2021, commenced in [g] Fall, 2020, was expected to consume [h] ?? hours and has consumed [i] ?? hours of team time, V1.0 is [j] complete.  A requirements document was [k] not formally done.  This work [l] delayed work on all other projects.

### ID Match API Specification
The [a] ID Match API Specification was [b] PLANNED and injected into [c] the SI WG work stream at the request of [d] BennO and [e] accepted by KeithH in summer 2020 for delivery [f] in early 2021, commenced on [g] ?? was expected to consume [h] ?? hours and has consumed [i] ?? hours of team time, is [j] not complete.  A requirements document was [k] done.  This work [l] delayed work on all other projects.

###
The [a]  was [b] PLANNED and injected into [c]  work stream at the request of [d]  and [e] accepted by ?? on ?? for delivery on [f] ??, commenced on [g] ?? was expected to consume [h] ?? hours and has consumed [i] ?? hours of team time, is [j] not complete.  A requirements document was [k] not done.  This work [l] delayed work on all other projects.

###
The [a]  was [b] PLANNED and injected into [c]  work stream at the request of [d]  and [e] accepted by ?? on ?? for delivery on [f] ??, commenced on [g] ?? was expected to consume [h] ?? hours and has consumed [i] ?? hours of team time, is [j] not complete.  A requirements document was [k] not done.  This work [l] delayed work on all other projects.

###
The [a]  was [b] PLANNED and injected into [c]  work stream at the request of [d]  and [e] accepted by ?? on ?? for delivery on [f] ??, commenced on [g] ?? was expected to consume [h] ?? hours and has consumed [i] ?? hours of team time, is [j] not complete.  A requirements document was [k] not done.  This work [l] delayed work on all other projects.

###
The [a]  was [b] PLANNED and injected into [c]  work stream at the request of [d]  and [e] accepted by ?? on ?? for delivery on [f] ??, commenced on [g] ?? was expected to consume [h] ?? hours and has consumed [i] ?? hours of team time, is [j] not complete.  A requirements document was [k] not done.  This work [l] delayed work on all other projects.



- - -
_2020-12-04 13:03 TI Quarterly Advisory Meeting_

TAP visibility: (A)CAMP Training, CSP, IAM Online,

NIH requested IdPs to support: R&S, MFA profile (signaling), Assurance F'work 'level 2' proofing and credentials

SoftwIntegr WG: TAP software in use;  2021: Workbench(es) / training environments, Bring Catalyst partners in for mutual ed: TAP interfacing patterns to C; from C: In the wild IAM situations and gaps; Proselytize for Assurance profiles, Baseline expectations as ppl are building their systems;
DevOps crawl,walk,run advice; Schema work, async + reconciliation pattern;

- - -
_2020-11-12 14:25 Ethan's 2021 SOW_

https://docs.google.com/document/d/1PlOfZn-Nsjf0DRgnbQZVd1vBOxvNPiJw5PBNgSAk4Bc/edit

General SME for CSP & Keith tasks (documentation, connector specs, event-driven arch)
COmanage / midPoint
- integration possibilities
- functional checklist

- - -
_2020-11-02 08:00 TI Project Radar_

*I2 FedMgr Async API Project*

The I2 Federation Manager Async API specification and design project was unplanned. It affects the Federation Manager team, the Software Integration team, the Dev team and Alfa-Jango. Nic Roy requested and approved this work in July, 2020 with an expectation that this will be done by the time Alfa-Jango was ready to code to the specification. This work took 40-45 hours to complete. The documented requirements guided the work. See https://github.internet2.edu/internet2/fed-mgr-msg. This emerging work item took some time away from other API and schema work around Id Match and TAP core schema development. ID Match API work is now likely to be completed in the month of November 2020.

- - -

a) The [I2 / Community] project / work item

b) was planned or unplanned

c) affected team(s) __

d) done on behalf of __

e) and approved/accepted or rejected that work (and date) by __

f) The accepted due-date on that work

g) Date that work began

h) Hours expected

i) Hours to-date

j) Completion State

k) Whether or not a requirements document existed for completion of that work

l) If the work was unplanned, what other work was negatively affected by the preemption

m) Date Adjustments to the current work (if any)

- - -
_2020-10-29 15:00 monthly planning and sequencing_

[Once they exist, created entities roam the minds of their creators]
- need to create entities to think and speak about the intrinsically inchoate reality
- but we then take the entity or even just its label to represent a real thing and since it's a thing, it becomes subject to cause and effect

Confirmed- Monthly planning/sequencing & work assignments oh my +
Occurs every last Thursday from 3:00 PM to 4:30 PM effective Thu 1/30/2020 until Fri 12/31/2021

https://internet2.zoom.us/j/4152791650

https://docs.google.com/document/d/1EEDzcLWSw-qW32FTzTZEXxK1EhX2kMDtiBnMejnCLf0/edit <- SteveZ, Arch team "Radar" incl. notes from this meeting

Hi All,

This is long – PLEASE take time to read it and think about it before our meeting at 1PM PT / 4pm ET today.  It is in direct response to the conversations we have been pursuing for the last week - and is intended for our collective discussion.

I’m adding Mike and IJ to these planning meetings.

(I know Mike is out and apologies to IJ for the short notice – if you cannot make it today, that’s fine but I’m making these changes starting today regardless.  An invitation update will follow shortly. )

We are all working to remedy some things that have caused the injection of too much ‘noise’ in our collective signal.

The following are from Harvard Business Review and summarize nicely, reminders of things we already do and I will continue to encourage us to develop.

*Here are 8 Rules that we can keep in mind, not only for this meeting but for all of our meetings*

·   State views and ask genuine questions. This enables the team to shift from monologues and arguments to a conversation in which members can understand everyone’s point of view and be curious about the differences in their views.

·   Share all relevant information. This enables the team to develop a comprehensive, common set of information with which to solve problems and make decisions.

·   Use specific examples and agree on what important words mean. This ensures that all team members are using the same words to mean the same thing.

·   Explain reasoning and intent. This enables members to understand how others reached their conclusions and see where team members’ reasoning differs.

·   Focus on interests, not positions. By moving from arguing about solutions to identifying needs that must be met in order to solve a problem, you reduce unproductive conflict and increase your ability to develop solutions that the full team is committed to.

·   Test assumptions and inferences. This ensures that the team is making decisions with valid information rather than with members’ private stories about what other team members believe and what their motives are.

·   Jointly design next steps. This ensures that everyone is committed to moving forward together as a team.

·   Discuss undiscussable issues. This ensures that the team addresses the important but undiscussed issues that are hindering its results and that can only be resolved in a team meeting.

We have our planning session today and I need to make some changes to how it will work and to establish better accountability for everyone.

We are going to discuss the formal addition of the following preamble/rubrik, +
https://docs.google.com/document/d/1yMqj182pzt5mBpCdOcGZEy62_e0NGDusvqEhsW0nzag/edit?usp=sharing +
to every future meeting; and the creation of a *single paragraph for EVERY major work item we undertake*:

a) The [I2 / Community] project / work item

b) was planned or unplanned

c) affected team(s) __

d) done on behalf of __

e) and approved/accepted or rejected that work (and date) by __

f) The accepted due-date on that work

g) Date that work began

h) Hours expected

i) Hours to-date

j) Completion State

k) Whether or not a requirements document existed for completion of that work

l) If the work was unplanned, what other work was negatively affected by the preemption

m) Date Adjustments to the current work (if any)

*Examples*

    The
    [a] IPV6 remediation project for INTERNET2 was
    [b] UNPLANNED and injected into the
    [c] ARCHITECTS and TSG work stream at the request of
    [d] Ana Hunsinger and Meredith Lovelace and
    [e] accepted by Steve Zoppi on 10/23/2020 for delivery on
    [f] <TBD>, commenced on
    [g] 10/23/2020 was expected to consume
    [h] 20 hours and has consumed
    [i] 10 hours of team time, is
    [j] not complete.  A requirements document was
    [k] unnecessary.  This work
    [l] delayed work on <Grouper implementation>, <Containerization>, etc. and
    [m] [will |will not] require a modification to the delivery dates of a, b, c…

    The
    [a] “Training Workbench” project for COMMUNITY TRAINING was
    [b] UNPLANNED and injected into the
    [c] ARCHITECTS work stream at the request of
    [d] Erin Murtha and
    [e] <accepted by [name] on [date]| not accepted | rejected by [name] on [date]> for delivery on
    [f] {the first day of Grouper training}, commenced on
    [g] {can’t find this date} was expected to consume
    [h] {can’t find this estimate} and has consumed
    [i] {don’t know} of team time, is
    [j] complete.  A requirements document was
    [k] not submitted.  This work
    [l] delayed work on <Grouper implementation>, <Containerization>, etc. and
    [m] [will |will not] require a modification to the delivery dates of a, b, c…

Template


Also – because we need to CLEARLY separate discussions into the INTERNET2 v COMMUNITY WORK buckets.  We will divide our discussion time as follows:

Part I – Internet2 (Internal) Projects +
Part II – Community (External) Projects

These meetings (starting today) are intended to establish better role definition so we aren’t all trying to spin each-others’ plates.  Primary Role Definitions need to be worked out.  These are the PRIMARY ROLES for this team as I currently see them:


. Product & Project Requirements Origination, Definition and Management
. Resource Management
. Solutions Design and Crafting
. Task Management and Progress Tracking
. Operational Support (Q/A, Test, Deployment, etc.)
. Event Operations Support


Talk to you all soon …

Regards, Steve

- - -
_2020-09-18 13:00 quarterly Advisory Committee Chairs_

https://docs.google.com/document/d/1kyvrSTwkeZ9O_R2P27NE3swWs_VG5vFW01twD9455aQ/edit

*Qtrly community update*

* TomJ: A forward-looking "here's what's coming in the next year or so"

* SIWG should hear from other advisory groups as guidelines and recommendations come out


*Software Integration WG update*

* Twice weekly WG meetings that bring together I2 staff and campus technologists
* Forum for conducting work and for cross-project coordination
* ICP, CSP, and InC Academy as drivers on a set of integration and enhancement efforts
* This Qtr: main areas of progress
**   IAM inbound and outbound APIs,
**   shared data models,
**   event-driven architecture,
**   ID Match,
**   provisioning & deprovisioning

.

- - -
_2020-08-27 15:00 monthly planning and sequencing_
https://internet2.zoom.us/j/7343238623 +
https://docs.google.com/spreadsheets/d/1Be-haluuxgpNaMQ9uL7Ft9Lj71LPsl2kZOzFNIIvYQM/edit#gid=1953682322 <- TAP Initiatives and Epics ODS +
https://drive.google.com/drive/u/4/folders/1FiXCC07TmXm0FABO8O6rATxN-4M6mES9 +
https://todos.internet2.edu/browse/TAP-115?src=confmacro +

- - -
_2020-08-27 15:00 monthly planning and sequencing_

- - -
_2020-07-30 15:00 monthly planning and sequencing_

https://cloudcheckr.com/ <- SaraJ: CloudCheckr total visibility delivers 30% savings on public cloud costs while managing the risks of cloud security and regulatory compliance

- - -
_2020-06-24 10:11 TAP 2020-2021_

*TAP Objectives for 2020 - 2021 in support of ease of use and adoption:*

*Minimize the campus challenges involved in a TAP roll-out*

* Continue to refine the container packages for as much consistency as possible across components and releases
* Develop “sandbox” implementations of components for use in local testing and InCommon Academy training courses
* Reorganize code repositories on Internet2 Enterprise GitHub; make it the authoritative source for TAP components and utilities

*Document and provide training on TAP integration patterns*

* Document context and examples of integration between components and between Grouper / midPoint, COmanage / midPoint, and COmanage / Grouper
* Expand integration capabilities between TAP and commercial software to support mix-and-match IAM architectures
* Broaden provisioning and deprovisioning support to additional academic applications and services
* Augment “how-to” documentation along the lines of the Grouper Deployment Guide (already published) with straightforward examples of patterns that can be evaluated and adopted
* Document easy techniques for schema extension
* Publish well-established API development guidelines


*Reduce the complexity of user interfaces designed for non-technical staff*

* Augment the COmanage core development team to advance the User Interface to easily adopt for “casual users”.   An example use case would be a simple Guest System for sponsored users such as student families or institutional donors
* Explore the development of more “wizard-like” capabilities for common user tasks

.

- - -
_2020-06-23 13:04 agenda mongering_

Review changes to TAP Kanban board

- - -
_2020-06-23 11:08 rethinking in progress items_

* IAM suite apples to apples: midPoint vs Sailpoint, Forgerock,...
* api security advice
* ID Match API spec
* person schema
* db table connector how-to
* midPriv Axiom and schema / data model languages white paper
* provisioning 101 for Base CAMP July 20-24
* BTAA provisioning cookbook

- - -
_2020-06-01 10:30 Cleaning up TAP Kanban_

- - -
Bill Kaufman  08:43
cool…  in reworking the work flow and adding Backlog some things got in there but we just need to have a look see.   It would be good to have full epics in the Backlog for easy CA/CACTI review using this link https://todos.internet2.edu/browse/TAP-115?src=confmacro in the TAP Project Portfolio

Ethan Kromhout  08:51
Thanks Bill, I think I will be available then.

Bill Kaufman  08:54
If you hit the backlog button it shows epics, but not it a good way to move them around… lemme see if I can create a better view

Keith Hazelton  08:55
If I open up tap-115 I see the epics list at the bottom as ‘child pages’

Bill Kaufman  08:56
right, they are all associated with it to roll up on the project page
but we want to see them in the kanban board to move them around easily

Keith Hazelton  08:57
right. I’ll focus on that.

Bill Kaufman  09:00
in the view with Epics on the left (backlog button way) if you
- click the little pointer to show the Epic details then
- click on the issue number it will open the full Epic.
Then we can select a different status in the Workflow, like TAP-22 is the only one in the Backlog.  TAP-23 is Selected for Dev and it’s other stories are in the backlog.

The ToDo column shows a status of Selected for Development.  So I was thinking those are things approved but on hold vs In Progress

Bill Kaufman  09:28
i added an Epic Filter to the Quick Filters on the top of the board.  They we can see Epics in Columns
09:28
Add Ethan to the invite

- - -
_2020-05-28 15:06 Sequencing etc._

SZ:

* COmanage packaging: reconciling ldap servers, containerization

* Adopting CILogon: conversations dried up; AAF is looking to instantiate a CILogon for their research organizations.

** Diff of views btween us and ScottK: Community demand for consolidation (from the EU) not obvious to him
** Hyzer's ALL IN on containers, bugging crap out of ChrisHu; Probably a clash or two with ScottK
** SK burr re nonRoot user stuff, grrr more work for me on containerization; Still being looked at; PC: That's when Scott got salty.
** Ethan's openshift special challenges...;
** SZ 100 channel summary: It's all still under discussion. SK thinks it was decided, but NO.
** SK complains but won't participate. His heart is with CILogon, so we get less of him; SZ; need to get SK out of containeriz.

* How do we accommodate eduroam/FedMgr?

* NetSvc: Gee, we need data mgmt (billing); Jay: 2 repl in TSG, one can be a data person;

* Coming together as predicted but requirements are still coming in

* State of data for ICP
** IAM Program (Collab Platf); drinking our own; get infra to interoperate (leverage Grouper, etc); I2's on a par with institutions in terms of our complexity.
** W absorption of TSG there are a couple slots; what do we most need? Biggest blocker of all is a deep enough understanding of the tie-in between parts of the system; we don't have a deep enough picture of SoR identity sources. Binding to apps: e.g. Sympa.; impedance matches between Sympa vs Confluence/JIRA.
** Barry's real world challenges; He needs supplemental data mgmt resource. The full picture of the data resources. Kabitha will come back as a data analyst.

* 3 upcoming hires: Nick for JamesB engineer repl.; Chris, Paul, Dave need some pressure relief; (PaulC: that means replacing JeffH); RyanMartin: should dump vms, puppet, LDAP; Needs to come up to speed with containers, we will give him support and time.
* Sara: Don't conflate ICP and TAP: Different need sets; Engineering vs Operations; needed skill troubleshooting testing, performance fixes; Different than layers 4 - 7 (engineering); Less of a need for defining and running infra; Capability deployment need is greater. Administration layers. Engineering products need ongoing deployment and administration
* SZ: Retrain TSG, narrower & deeper; DevOps us + Shannon and Dave: Implementing the operations that can go to TSG peeps. Drop some existing ongoing work;

Nick gets a Babb, Paul/Chris gets a Ryan Martin, we need a Data specialist, desperately

.

- - -
_20200526 13:30 agenda planning_

tr & id Platform Program

Howdy @channel I hope to show a quick overview of the refactored TAP project this afternoon in prep for tomorrow’s WG meeting.  Basically I think I will create 1 Initiative, will move the current ones to Epics, Epics to Stories, and Stories to Subtasks under Stories.

So we should have basically the same structure, but shifted down a level.  I have found that subtasks under Stories is not a bad way to manage work and that is already how I have the ICP project(s).

So TAP as a PROGRAM will include the Component software projects and the Software Integration WG project with Epics around what we have in flight and also building a backlog for Component Architect and CACTI review

- - -
_2020-05-05 13:48 agenda planning_

lucidchart from Chris Hu on ICP architecture: https://www.lucidchart.com/documents/edit/74366e7cd8254fc1b470daedecb22e72/0_0

NickR has stuff in the wiki:

- - -
_2020-05-01 08:04 planning docs from BillK_

https://docs.google.com/document/d/1g10qkbLwKEdXC8J9OZg9_uXIbGmM0S9ljXFQ8FaKwg/edit?usp=sharing_eil&ts=5eab402d <- ICP Program Plan, JessicaC

https://docs.google.com/document/d/1eEXRXs2lJsISo5QPJ3N4vBx14Eiy4xxKtFcZJScjysI/edit?usp=sharing <- ICP Functional Design, JessicaC

- - -
_2020-04-30 14:24  planning, sequencing & assignments_

Sched for Fri: BillK has two holds on cal.
Markdown to Confluence: https://bobswift.atlassian.net/wiki/spaces/MARKDOWN/overview
Confluence is our go to doc tool and place to search find anything
Send tech writer candidates to SZ
to many // threads on ICP and everywhere
Settle on Mysql 8, PostgreSQL 12 (but repl targets from informatica are MySQL, and repl goes out from there); ON RDS and that can handle repl.

- - -
_2020-04-24 20:26 John O'Brien, new developer_

https://onedrive.live.com/?authkey=%21AEq5ESlm9Khk8Io&cid=9F7166CBDEEF361B&id=9F7166CBDEEF361B%2163262&parId=9F7166CBDEEF361B%2163250&o=OneUp

- - -
_2020-04-24 20:28 IAM evaluation WG_

https://docs.google.com/document/d/17dIcV18VwNYZoeWGcEL00cQ2MhkpINYJ8bswa0lPg/edit#heading=h.tofkw2awgyuq <- Evaluating IAM Software Working Group Charter

- - -
_2020-04-23 07:32 ICP Resource Heatmap_

I have started a heat map to help get a general idea of effort for all the folks working in different areas on the ICP.  It is not precise, but we are using this tool on several T&I Projects for general visibility.

I would appreciate it if you can take a few minutes to update your row.  If you are unsure about certain things like the ICP Data work just put in ? as Paul and Chris did.  I expect that everyone will have some role to play there as we work with Barry to evolve an identity data warehouse.

https://docs.google.com/spreadsheets/d/1HziJHWC4QUnPxnCeEhaBOM_EafHe3YKbWAvpns61wQ/edit?usp=sharing

- - -
_2020-03-04 10:13 TAP Issues_

See tapInitsEpics.pdf for list of TAP Initiatives and Epics

- - -
_2020-03-03 13:12 JIRA and 2 week sprints_

*Initiatives*

https://todos.internet2.edu/secure/PortfolioPlanView.jspa?id=3&sid=3#plan/backlog

***
TAP97 midPoint Implementation      Repos for both cases: ICP and TAP
TAP98 midPoint Integrations  Catalog the existing integrations
TAP99 SORs & Identities      How does COmanage identity data get into Grouper, midPoint?
TAP100 General Component Integration     Documented messaging infrastructure
TAP102 Documentation   Build mP Integration Manual; driven by current needs
TAP101 APIs      Start with Grouper SCIM APIs and move on to FM
TAP103 Schema & Extensions   List domain objects; construct conceptual models for each; map to JSON
TAP106 Testing & Adoption    CSP 2020 results
***

- - -
_2020-03-02 09:03 JIRA Portfolio for Trusted Access Platform_
https://todos.internet2.edu/secure/PortfolioProgramView.jspa?id=1

- - -
_2020-02-27 15:02 planning, sequencing & assignments_

SZ: Work Package approach

√
ConnID connectors +
ICP: COmanage, IDmatch, Slack, FedMgr*, Sympa* (SCIM4all) +
1 story per 2 weeks cadence: Each Monday: WHAT NEEDS TO GET DONE IN 2 WEEKS +
] Get extract schema from NickR +
] Get Sympa data properly into Grouper & COmanage +
(Schema for the minimal person) is done +
netplusadmdev0.internet2.edu via VPN; Sympa & Salesforce +

√ API specs: IDmatch; FM; API AuthNZ;

√ Schema specifications (Banner Integr)

√ Data Registry

√ Messaging: Document Ethan's approach todate

https://1drv.ms/b/s!Ahs2797LZnGfg4eSrkRKWb0qGTwig?e=2YlZ4o  <- That is John O'Brien's Resume he can dev anything I can dream

- - -
_2020-02-25 12:31 component integration effort management_

* CompArch
 A) Surface, prioritize crosscomponent interdependencies
 A) Maintain backlog of crosscomponent issues
 C) Approves TF charters
 F) Rules on TF recommendations

* PM
 B) Arranges for charter drafting by concerned parties
 D) Recruits, Launches, Coordinates Task Forces

* TF
 E) Analyzes issue
 E) Recommends course of action as choice points are surfaced

* What are the current, hot, crosscomponent issues?
 SCIM capabilities for FM via Rails and for mP via SCIM connector;
 COm/mP integration for Guest System use case
 ?
 AuthNZ for APIs
 Core EDA/messaging architecture

- - -
_2019-08-06 12:06 API refocus, configuration awareness_

Configuration awareness:
  1) What you see in the UI is shaped by your group memberships and entitlements
  2) For a published API, the client can invoke the service interface without knowing which implementation is being used behind the scenes (it's in the configured environment)


Starting from a different viewpoint:

   What would have the most impact on the cadence of ICP solution delivery for priority use cases?
   Delegated admin of application role assignments
   Freestanding invitation management service
   Freestanding selfservice accountlinking and profile management
   Connector configuration


fm to RabbitMQ mP mP to

attestation tbrown to chrisHy;

gets us an operating pub/sub transport; tie through normal connector to mP

- - -
_2019-08-05 08:30 Service Registry_

Bill, Keith

selected use cases from Denver F2F

* Development of a primary taxonomy for our Groups and associated roles
* Implement midPoint to consume/store FM identity information and inject groups back to Grouper
* Implement ID Match Container with COmanage
* Determine an integration pattern for apps that have high value for (De)Provisioning like FM, OESS, Box, Slack, GitHub, etc (lucidchart, Mailman?)
* User SelfService UI
* Devise an implementation Pattern for Delegated administration/authority
* Modifying this to be focused on Attestation Patterns with the initial task to be a general pattern.  Specifics will follow related to specific application/group requirements.
* Need for identifying an Identity’s origin to be checked against known groups for Authorization
* Create Data Dictionary / META Data Information base (Identity Data)
* Establish A Pattern for Policy enforcement  Policy Access | Decision | Enforcement Points (Also serves as the Resulting Set of Policy Calculation)
* Protecting API’s  We need to build a Specific Qualitative/Quantitative Descriptor of OUR means and methods of setting requirements for ALL APIs we onboard and how they are protected. For APIs of different types (SOAP, RESTful, CLI, etc.)
* Implement a Messaging Bus
* Implementation of Resulting Set of Policy Calculation (How do services ask policy questions and get an answer)

.

- - -
_20190801 16:00 API refocus, Issue triage_

Discussion starter gist: https://gist.github.com/khazelton/9871626c93af1a40ded4a022cc87ea2d

==== goals:

* make it easier for I2 developers and contractors to spin up tailormade UIs for specific use cases
* make it easier for technical staff at adopting campuses to easily generate UIs to meet local needs

==== design lifcycle:

* Take userexperience as point of reference
* Take taskspecific use cases as project drivers
* Advertise a URL that anyone (I2 staff, InCommon members) can use to request (or offer) a "UI to do X"
* Manage the submission queue as an issue backlog
* Sketch MVC models for a "UI doing X"
* Using the sketch, Identify 'that which must be controlled' in domain object terminology
* Identify serverside interfaces to services or service mashups that the UI could invoke to realize the use case.
* Implement or reuse the required service interfaces
* Code the UI
* Publish the code to Internet2's github or dockerhub (T&I: github jenkins step moves a copy to dockerhub)
* Announce availability through all the usual channels


==== development enablers:

* Recommend development frameworks for building UIs that invoke backend services
 DERN (Database*, Express, React, Node)    *SQL and/or noSQL as appropriate
 Java (Spring Boot + Vaadin + Thymeleaf)
 PHP?
 ???

==== references and links

https://obsproject.com/
 <- OBS Studio: Free and open source software for video recording and live streaming +
https://vaadin.com/ +
https://www.thymeleaf.org/

* SZ: Formalizing the
 creation,
 delivery and
 socialization of APIs that are needed for things like
* 'eliminating the need to train peeps on GROUPER in favor of creating simpler interfaces

===== Steve Zoppi 14:15

In (further) efforts to refocus and narrow things so we can make more visible progress, the three of us should get on a call sometime in the next week or so to talk about how to

* dialdown some of the 'noisy' things on your plate and
* dialup some of the more focused activities around
  'codification of publicly consumable APIs' and
  'intersystem APIs' for the pile of "stuff"'

===== Keith Hazelton 14:16

* I’m down with that.
I’ll make sure everything is tied to an

 issue in the JIRA TAP before we meet.
 Then we can triage

.

- - -
_2018-08-30 19:58 BillK / KeithH checkpoint_

 nw/cloud connect
 TSG infra support
 Tech Architects in T&I have good rapport with TSG; need a who's on 1st

cloud connect
net + scaleback

SaraJ reports to SteveZ as cloud architect GCP; D__ the broker for AWS

SoW is in Evolveum's court as of earlier this week; See

'Consulting Agreement.Consultant EVO draft (82718)'.docx <- consulting agreement with attachment SoW 1

pdf/"TIER report jul_aug 2018.pdf" <- report jul_aug 2018

***
Martina Benckova <martina.benckova@evolveum.com>
Tue 8/28, 8:58 AM
Keith Hazelton;Igor Farinic <ifarinic@evolveum.com>;William Kaufman;Steven Zoppi <szoppi@internet2.edu>
Hi Keith,

please, see attached file.
Based on your communication with Igor yesterday, I am sending you promised report.

In case of additional questions do not hesitate contact me directly.

Best regards,
Martina Benckova | Relationship & Project Manager

martina.benckova@evolveum.com | www.evolveum.com
Skype: mbenckova
tel: +421 948 940 888
____________________________
RE: ATTACHMENT A STATEMENT OF WORK 1.0

Steven Zoppi <szoppi@internet2.edu>
Mon 8/27, 12:03 PM
Martina Benckova <martina.benckova@evolveum.com>;ifarinic@evolveum.com;Keith Hazelton;Katarina Chovancova <kchovancova@evolveum.com>;William Kaufman
Hi Martina,

I’ve addressed the concerns/misunderstandings that that you mentioned below.  I think we’re ready (finally) to press forward with your review of the attached document.

Please leave any comments/annotations in review mode so I can get through them quickly
____________________________

 Direct xref of our footnote 1 deliverable list w Steve's doc from GS

Thank you for your patience and thoroughness!  If you don’t see anything major – I think we can get through it this week – and then you can invoice us! 😊

Regards, Steve


:: Steven Zoppi
:: AVP, Services Integration and Architecture
:: szoppi@internet2.edu

:: Internet2®
:: 59 Damonte Ranch Parkway
:: Suite B#188
:: Reno, NV  89521

:: p: 510 858 0884 ▪ m: 415 279 1650 ▪ f(office): 510 858 0894 ▪ f(digital): 877 313 2002 x708

:: SJZoppi @ [ Skype :: MSN :: AIM :: Y! :: GTalk ]
***

https://docs.google.com/spreadsheets/u/2/d/18W0PlD6-MSH5o6UQg3TODUOVu8kMGgroeUkPtYXheUs/edit?usp=sharing_eip&ts=5b88143d  <- Evolveum time report 2018-08

- - -
