=== mpTraining-2023-04.adoc 
https://learning.internet2.edu/courses/131
opt/mpTraining/

- - -
_2023-04-25 10:42:26 references and links_

ssh -L8443:localhost:8443 -L10443:localhost:443 -L4443:localhost:4443 -L15672:localhost:15672 -L10389:localhost:389 -l student  18.222.1.96

https://learning.internet2.edu/courses/131/modules <- Syllabus

https://learning.internet2.edu/courses/131/assignments/754 <- prerequisites

https://learning.internet2.edu/courses/131/pages/module-1?module_item_id=6113 <- module 1

file:///Users/khazelton/Downloads/LABS-basics-module1-2.PDF <- module 1 Labs

[[ BREAK ]]

file:///Users/khazelton/Downloads/midpoint-basics-slides-module2s-1-1.PDF <- module 2 slides 

file:///Users/khazelton/Downloads/LABS-basics-module2-2.PDF <- module 2 Labs

https://docs.google.com/spreadsheets/d/1mvD3kXYy64BjvKuJragG_vt59cWE6yusDhnmGPMDpAM/edit#gid=585713312 <- vm assignment sheet 

- - -
_2023-04-28 17:59:50 duplicate training environment on personal bost_

- - -
_2023-04-28 10:15:26 mP 101 day 4 module 5_


- - -
_2023-04-27 10:57:21 mP 101 day 3 modules 4 & 5_

] hooks and scripts as means to run a chain of tasks

correlation can invoke ID Match
correlation step can create a review case

use Axion queries in correlation expression; also in mP Studio

cleanup option with downloaded objects--gets rid of metadata

- - -
_2023-04-26 08:39:23 mP 101 day 2 modules 3 & 4_

midpoint-basics-slides-module4s-1.pdf +
LABS-basics-module4-1.pdf

https://docs.evolveum.com/midpoint/tools/studio/usage +
https://docs.evolveum.com/midpoint/tools/studio/usage/#environment-or-project-specific-properties <- Esp. +
https://docs.evolveum.com/midpoint/tools/studio/usage/#using-properties-within-groovy-code <- [this is what i forgot]

file:///Users/khazelton/Downloads/LABS-basics-module3-1.pdf

- - -
_2023-04-25 09:00:00 mP 101 Day 1_

27 students 

] ssh tunnel step just before docker-compose: See Env setup in 6 steps

https://devangtomar.medium.com/colima-containers-on-linux-on-mac-f6396c27e39b <- colima: container-linux-on-mac

Module 1, Slide 11

This material may be used under terms of agreed license
between Internet2 and Evolveum.
Environment Setup in 6 Steps
# clone git repository and checkout proper branch (training)
git clone -b training https://github.internet2.edu/docker/midPoint_container.git
# get to the cloned repository
cd midPoint_container
# build midPoint image
./build.sh
# change directory to demo/grouper
cd demo/grouper
# modify the hard-coded hostnames for our tunneled training setup
# notice the final . (dot) argument of the script
./ssh-tunnel-redir-fix.sh .
# build and run the whole show in background!
docker-compose up -d --build

- - -
_2023-04-24 13:44:32 mP training prep_

Keith's vm:	18.222.1.96	67dd4345

ssh -L8443:localhost:8443 -L10443:localhost:443 -L4443:localhost:4443 -L15672:localhost:15672 -L10389:localhost:389 -l student  18.222.1.96

https://docs.google.com/spreadsheets/d/1mvD3kXYy64BjvKuJragG_vt59cWE6yusDhnmGPMDpAM/edit#gid=585713312

```
[student@ip-172-31-13-33 ~]$ pwd
/home/student

[student@ip-172-31-13-33 ~]$ git clone -b training https://github.internet2.edu/docker/midPoint_container.git

Cloning into 'midPoint_container'...
remote: Enumerating objects: 4161, done.
remote: Counting objects: 100% (114/114), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 4161 (delta 36), reused 78 (delta 21), pack-reused 4047
Receiving objects: 100% (4161/4161), 16.27 MiB | 32.86 MiB/s, done.
Resolving deltas: 100% (2236/2236), done.

[student@ip-172-31-13-33 ~]$ cd midPoint_container

[student@ip-172-31-13-33 midPoint_container]$ ls -la
total 60
drwxrwxr-x 6 student student   242 Apr 24 22:17 .
drwx------ 3 student student   134 Apr 24 22:17 ..
-rwxrwxr-x 1 student student  1478 Apr 24 22:17 build.sh
-rw-rw-r-- 1 student student    71 Apr 24 22:17 common.bash
drwxrwxr-x 7 student student    88 Apr 24 22:17 container_files
drwxrwxr-x 5 student student    53 Apr 24 22:17 demo
-rw-rw-r-- 1 student student  3394 Apr 24 22:17 Dockerfile
-rw-rw-r-- 1 student student    16 Apr 24 22:17 .dockerignore
-rwxrwxr-x 1 student student  1105 Apr 24 22:17 download-midpoint.sh
drwxrwxr-x 8 student student   163 Apr 24 22:17 .git
-rw-rw-r-- 1 student student    26 Apr 24 22:17 .gitignore
-rw-rw-r-- 1 student student  4763 Apr 24 22:17 Jenkinsfile
-rw-rw-r-- 1 student student 23068 Apr 24 22:17 library.bash
-rw-rw-r-- 1 student student  1475 Apr 24 22:17 README.md
drwxrwxr-x 2 student student    23 Apr 24 22:17 test
